### ISSUE TITLE
Error saving series format (API returns 400)

### ISSUE THREAD

**Issue by Anzumatsuri** [Kareadita/Kavita#1145]
**Describe the bug**
Getting HTTP status 400 response from the API when trying to update series format.

**To Reproduce**
1. Go to any series
2. Select on "Ongoing" or "Archive", the edit form will appear.
3. Update format (or any field actually) field and select apply to save
4. Nothing happens
5. Opening developer's console on the network tab, repeat 3 to see the API returns a 400 status code upon saving

**Expected behavior**
The format should be changed successfully.

**Screenshots**
![image](https://user-images.githubusercontent.com/52699436/158364038-4868138b-51ab-49a1-9e82-14cfd8e53e20.png)
![image](https://user-images.githubusercontent.com/52699436/158364342-a4d7cc0d-ee59-406e-a7dc-35e0771e7c12.png)

**Desktop (please complete the following information):**
 - OS: Linux Docker
 - Browser: Chrome
 - Version: 0.5.1.1

**Additional context**
Access via lan IP, it is not public. I tried deleting the docker configs and start from scratch, but I am still getting the same issue.

Nothing much on logs except this line:
`INFO	[Microsoft.AspNetCore.Hosting.Diagnostics]	[2]	Request finished HTTP/1.1 POST http://192.168.1.90:33400/api/series?libraryId=0&pageNumber=1&pageSize=30 application/json 416 - 400 - application/problem+json;+charset=utf-8 2.1970ms`

On developer's console preview tab, it does give more info:
![image](https://user-images.githubusercontent.com/52699436/158364818-5e6d7b7a-a6f4-499d-95e8-931fb0d33f60.png)

I'm not sure if I should create a new issue since its still under the same edit form. Selecting **Publication Status** text field fails to load and will return a 500 status code as well:
![image](https://user-images.githubusercontent.com/52699436/158366354-9e59d251-c189-47d8-a56c-7e71ba9897e2.png)
![image](https://user-images.githubusercontent.com/52699436/158366492-25423762-f7f2-44d9-88d4-cbac55e74b9f.png)

The details error message:
>    at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.<VisitMethodCall>g__CheckTranslated|15_0(ShapedQueryExpression translated, <>c__DisplayClass15_0& )
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.ExecuteAsync[TResult](Expression query, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.ConfiguredCancelableAsyncEnumerable`1.GetAsyncEnumerator()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at API.Data.Repositories.SeriesRepository.GetAllPublicationStatusesDtosForLibrariesAsync(List`1 libraryIds) in /home/runner/work/Kavita/Kavita/API/Data/Repositories/SeriesRepository.cs:line 873
   at API.Controllers.MetadataController.GetAllPublicationStatus(String libraryIds) in /home/runner/work/Kavita/Kavita/API/Controllers/MetadataController.cs:line 107
   at lambda_method797(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at API.Startup.<>c.<<Configure>b__4_3>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 241
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 53

**Comment by majora2007** [comment]
What version of Kavita is this happening on?

**Comment by majora2007** [comment]
This was found in v0.5.1 and fixed in v0.5.2.
