### ISSUE TITLE
Kavita 0.5.2.5 errors while scanning a library - cannot parse covers

### ISSUE THREAD

**Issue by cormacj** [Kareadita/Kavita#1232]
**Describe the bug**
I have a docker install of Kavita v0.5.2.5

I have it scanning my books library and it's erroring on every book with this type of error:

```
2022-04-26T04:16:43.9119415+00:00	WARN	[API.Services.BookService]	[0]	[BookService] There was an exception when opening epub book:  /books/Authors/authorname/bookname.epub
System.AggregateException: One or more errors occurred. (Incorrect EPUB manifest: item with ID = "images/cover.jpg" is missing.)
 ---> System.Exception: Incorrect EPUB manifest: item with ID = "images/cover.jpg" is missing.
   at VersOne.Epub.Internal.BookCoverReader.ReadBookCover(EpubSchema epubSchema, Dictionary`2 imageContentRefs)
   at VersOne.Epub.Internal.ContentReader.ParseContentMap(EpubBookRef bookRef)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at VersOne.Epub.EpubReader.OpenBookAsync(ZipArchive zipArchive, String filePath)
   --- End of inner exception stack trace ---
   at API.Services.BookService.ParseInfo(String filePath) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 507
```

The book structure is this:
```
   Date      Time    Attr         Size   Compressed  Name
------------------- ----- ------------ ------------  ------------------------
2010-09-17 13:28:44 .....           22           22  mimetype
2010-09-17 13:28:44 D....            0            0  OEBPS
2010-09-17 13:28:44 D....            0            0  OEBPS/images
2010-09-17 13:28:44 .....        24796        24627  OEBPS/images/cover.jpg
2010-09-17 13:28:44 D....            0            0  OEBPS/fonts
2010-09-17 13:28:44 .....       156076        96458  OEBPS/fonts/LiberationSerif-Regular.ttf
2010-09-17 13:28:44 .....       100420        61773  OEBPS/fonts/LiberationSerif-Italic.ttf
2010-09-17 13:28:44 .....       129416        73567  OEBPS/fonts/LiberationSerif-Bold.ttf
2010-09-17 13:28:44 .....       100392        61837  OEBPS/fonts/LiberationSerif-BoldItalic.ttf
2010-09-17 13:28:44 D....            0            0  OEBPS/css
2010-09-17 13:28:44 .....         3514          811  OEBPS/css/main.css
2010-09-17 13:28:44 .....          452          288  OEBPS/cover.xhtml
2010-09-17 13:28:44 .....          544          335  OEBPS/title.xhtml
2010-09-17 13:28:44 .....          733          462  OEBPS/annotation.xhtml
2010-09-17 13:28:44 .....          508          300  OEBPS/section1.xhtml
2010-09-17 13:28:44 .....        27595        10523  OEBPS/section2.xhtml
2010-09-17 13:28:44 .....        29397        11613  OEBPS/section3.xhtml
2010-09-17 13:28:44 .....        37695        14312  OEBPS/section4.xhtml
2010-09-17 13:28:44 .....        47868        17659  OEBPS/section5.xhtml
2010-09-17 13:28:44 .....        50200        18787  OEBPS/section6.xhtml
2010-09-17 13:28:44 .....        55960        21241  OEBPS/section7.xhtml
2010-09-17 13:28:44 .....        41637        15855  OEBPS/section8.xhtml
2010-09-17 13:28:44 .....        35416        13484  OEBPS/section9.xhtml
2010-09-17 13:28:44 .....        48951        18196  OEBPS/section10.xhtml
2010-09-17 13:28:44 .....        27101        10417  OEBPS/section11.xhtml
2010-09-17 13:28:44 .....        26000        10229  OEBPS/section12.xhtml
2010-09-17 13:28:44 .....        57216        20564  OEBPS/section13.xhtml
2010-09-17 13:28:44 .....        29853        11324  OEBPS/section14.xhtml
2010-09-17 13:28:44 .....        57534        20330  OEBPS/section15.xhtml
2010-09-17 13:28:44 .....         9005         3796  OEBPS/section16.xhtml
2010-09-17 13:28:44 .....          984          548  OEBPS/fb2info.xhtml
2010-09-17 13:28:44 .....          644          423  OEBPS/about.xhtml
2010-09-17 13:28:44 .....         3179          573  OEBPS/toc.ncx
2010-09-17 13:28:44 .....         6452         1261  OEBPS/Content.opf
2010-09-17 13:28:44 D....            0            0  META-INF
2010-09-17 13:28:44 .....          260          182  META-INF/container.xml
2011-06-12 19:46:12 .....           95           73  META-INF/calibre_bookmarks.txt
------------------- ----- ------------ ------------  ------------------------
2011-06-12 19:46:12            1109915       541870  32 files, 5 folders
```

**Comment by majora2007** [comment]
Hi, this is a problem with the metadata within the opf file. It says in the error that it's looking for cover image with a certain path and in the list of files below, you see it's in a slightly different path. 

You can use calibre to fix. The downstream library has loosened restrictions but they haven't pushed a new version yet.
