### ISSUE TITLE
Can't open the Kavita webpage on Firefox

### ISSUE THREAD

**Issue by parthshahp** [Kareadita/Kavita#1394]
**Describe the bug**
Can't open the Kavita webpage in Firefox

**To Reproduce**
My Steps:
Create docker-compose.yml file using the instructions in the documentation.
Run the docker container.
Go to correct port, screen shows blank screen and perpetually loads.

**Works correctly on Chromium, but does not work on Firefox.**

Already tried:
- Restarting container
- Restarting computer
- Deleting image and container completely and redownloading

**Expected behavior**
To see the correct webpage.

**Screenshots**
![image](https://user-images.githubusercontent.com/48393781/182443903-7481efa4-4a51-4e6b-a5af-20e73c1fcb5f.png)

**Desktop (please complete the following information):**
 - OS: Docker (Compose)
 - Browser: Firefox and Chromium
 - Version: Latest

**Additional context**
Logs from docker container show this failure, not sure if it's relevant:
```
fail: Microsoft.EntityFrameworkCore.Query[10100]

      An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.

      System.InvalidOperationException: Sequence contains no elements.

         at lambda_method252(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )

         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

      System.InvalidOperationException: Sequence contains no elements.

         at lambda_method252(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )

         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

warn: Hangfire.AutomaticRetryAttribute[0]

      Failed to process the job 'a2f77f8f-85f0-4d11-8e8d-428ea9f4c821': an exception occurred. Retry attempt 5 of 10 will be performed in 00:04:51.

      System.InvalidOperationException: Sequence contains no elements.

         at lambda_method252(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )

         at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)

         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)

         at API.Services.Tasks.StatsService.GetServerInfo() in /home/runner/work/Kavita/Kavita/API/Services/Tasks/StatsService.cs:line 111

         at API.Services.Tasks.StatsService.SendData() in /home/runner/work/Kavita/Kavita/API/Services/Tasks/StatsService.cs:line 63

         at API.Services.Tasks.StatsService.Send() in /home/runner/work/Kavita/Kavita/API/Services/Tasks/StatsService.cs:line 54

         at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

**Comment by parthshahp** [comment]
Have to add /login at the end. Closing.
