### ISSUE TITLE
Series with mix of formats creates 2 conflicting series

### ISSUE THREAD

**Issue by tjarls** [Kareadita/Kavita#1465]
**Describe the bug**
Single series mixing formats (PDF, CBR/CBZ, JPG) create seperate series sharing a name and eventually trigger an exception due to their name colliding.

**To Reproduce**
1. Have a single series that mixes PDF and CBR/CBZ in one folder.
2. Scan library
3. Widget should show an exception about finding exisiting series with the same Localized name.

**Expected behavior**
Previous versions created two series with the same name.

**Screenshots**
![Screenshot 2022-08-23 at 11 11 45](https://user-images.githubusercontent.com/2511889/186140927-c88f7e81-f76b-413d-9897-7f7e1c01e604.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Docker]
 - Version [e.g. 22] (can be found on Server Settings -> System tab)

**Smartphone (please complete the following information):**

**Additional context**
Seen in 0.5.5.7, likely introduced in 0.5.5.6. Not present in 0.5.5

**Comment by tjarls** [comment]
I have just created a minimal library where I can reproduce the issue. The library is like this:
```
tree /shared/Books/TestLibrary
/shared/Books/TestLibrary
└── dBD
    ├── dBD - #001.cbz
    └── dBD - #084.pdf

1 directory, 2 files
```
The steps to reproduce the issue on a brand new instance:
1. Create a library with a single series with one pdf and one cbz under version 0.5.5
2. Upgrade to 0.5.5.9
3. Use "touch" on folder and files to update their timestamps
4. Scan library

**Comment by tjarls** [comment]
The error from the logs:
```
fail: API.Services.Tasks.Scanner.ProcessSeries[0]
      There was an exception finding existing series for dBD with Localized name of  for library 1. This indicates you have duplicate series with same name or localized name in the library. Correct this and rescan
      System.InvalidOperationException: Sequence contains more than one element.
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
         at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library) in /shared/devel/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 94
```
