### ISSUE TITLE
Can't modify metadata of a serie

### ISSUE THREAD

**Issue by Selid** [Kareadita/Kavita#1571]
**Describe the bug**
Some series can't have their metadata updated. The server respond with a 400 and the logs seems to indicate two series with the same name. It might have been because I change the edition of the serie and deleted the old files, or because I convert them with comicrack after some changes in the info, and so replacing the files.

**To Reproduce**
Not sure. My guess would be to add files as .cbr, having Kavita to load them and create a serie, convert the cbr to cbz (maybe changing some metada info like the volume) and having kavita rescan the librairie. 

**Expected behavior**
Changing metada should work

**Screenshots**
Here are the logs ending with a 400 : 

2022-10-04T18:15:57.9253999+02:00	INFO	[Microsoft.AspNetCore.Hosting.Diagnostics]	[1]	Request starting HTTP/1.1 POST http://localhost:5000/api/series/metadata application/json 4890
2022-10-04T18:15:57.9258532+02:00	INFO	[Microsoft.AspNetCore.Routing.EndpointMiddleware]	[ExecutingEndpoint]	Executing endpoint 'API.Controllers.SeriesController.UpdateSeriesMetadata (API)'
2022-10-04T18:15:57.9258942+02:00	INFO	[Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker]	[ControllerActionExecuting]	Route matched with {action = "UpdateSeriesMetadata", controller = "Series"}. Executing controller action with signature System.Threading.Tasks.Task`1[Microsoft.AspNetCore.Mvc.ActionResult] UpdateSeriesMetadata(API.DTOs.UpdateSeriesMetadataDto) on controller API.Controllers.SeriesController (API).
2022-10-04T18:15:57.9264940+02:00	INFO	[Microsoft.EntityFrameworkCore.Infrastructure]	[Microsoft.EntityFrameworkCore.Infrastructure.ContextInitialized]	Entity Framework Core 6.0.7 initialized 'DataContext' using provider 'Microsoft.EntityFrameworkCore.Sqlite:6.0.7' with options: DetailedErrorsEnabled 
2022-10-04T18:15:57.9273392+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (0ms) [Parameters=[@__seriesId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT "s"."Id", "s"."AppUserId", "s"."AvgHoursToRead", "s"."CoverImage", "s"."CoverImageLocked", "s"."Created", "s"."Format", "s"."LastChapterAdded", "s"."LastModified", "s"."LibraryId", "s"."LocalizedName", "s"."LocalizedNameLocked", "s"."MaxHoursToRead", "s"."MinHoursToRead", "s"."Name", "s"."NameLocked", "s"."NormalizedName", "s"."OriginalName", "s"."Pages", "s"."SortName", "s"."SortNameLocked", "s"."WordCount", "s0"."Id", "s0"."AgeRating", "s0"."AgeRatingLocked", "s0"."CharacterLocked", "s0"."ColoristLocked", "s0"."CoverArtistLocked", "s0"."EditorLocked", "s0"."GenresLocked", "s0"."InkerLocked", "s0"."Language", "s0"."LanguageLocked", "s0"."LettererLocked", "s0"."MaxCount", "s0"."PencillerLocked", "s0"."PublicationStatus", "s0"."PublicationStatusLocked", "s0"."PublisherLocked", "s0"."ReleaseYear", "s0"."RowVersion", "s0"."SeriesId", "s0"."Summary", "s0"."SummaryLocked", "s0"."TagsLocked", "s0"."TotalCount", "s0"."TranslatorLocked", "s0"."WriterLocked"
FROM "Series" AS "s"
LEFT JOIN "SeriesMetadata" AS "s0" ON "s"."Id" = "s0"."SeriesId"
WHERE "s"."Id" = @__seriesId_0
ORDER BY "s"."Id", "s0"."Id"
LIMIT 2
2022-10-04T18:15:57.9275910+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (0ms) [Parameters=[@__seriesId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT "v"."Id", "v"."AvgHoursToRead", "v"."CoverImage", "v"."Created", "v"."LastModified", "v"."MaxHoursToRead", "v"."MinHoursToRead", "v"."Name", "v"."Number", "v"."Pages", "v"."SeriesId", "v"."WordCount", "t"."Id", "t"."Id0"
FROM (
    SELECT "s"."Id", "s0"."Id" AS "Id0"
    FROM "Series" AS "s"
    LEFT JOIN "SeriesMetadata" AS "s0" ON "s"."Id" = "s0"."SeriesId"
    WHERE "s"."Id" = @__seriesId_0
    LIMIT 1
) AS "t"
INNER JOIN "Volume" AS "v" ON "t"."Id" = "v"."SeriesId"
ORDER BY "t"."Id", "t"."Id0"
2022-10-04T18:15:57.9277652+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (0ms) [Parameters=[@__seriesId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT "t0"."CollectionTagsId", "t0"."SeriesMetadatasId", "t0"."Id", "t0"."CoverImage", "t0"."CoverImageLocked", "t0"."NormalizedTitle", "t0"."Promoted", "t0"."RowVersion", "t0"."Summary", "t0"."Title", "t"."Id", "t"."Id0"
FROM (
    SELECT "s"."Id", "s0"."Id" AS "Id0"
    FROM "Series" AS "s"
    LEFT JOIN "SeriesMetadata" AS "s0" ON "s"."Id" = "s0"."SeriesId"
    WHERE "s"."Id" = @__seriesId_0
    LIMIT 1
) AS "t"
INNER JOIN (
    SELECT "c"."CollectionTagsId", "c"."SeriesMetadatasId", "c0"."Id", "c0"."CoverImage", "c0"."CoverImageLocked", "c0"."NormalizedTitle", "c0"."Promoted", "c0"."RowVersion", "c0"."Summary", "c0"."Title"
    FROM "CollectionTagSeriesMetadata" AS "c"
    INNER JOIN "CollectionTag" AS "c0" ON "c"."CollectionTagsId" = "c0"."Id"
) AS "t0" ON "t"."Id0" = "t0"."SeriesMetadatasId"
ORDER BY "t"."Id", "t"."Id0"
2022-10-04T18:15:57.9278699+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (0ms) [Parameters=[@__seriesId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT "t0"."GenresId", "t0"."SeriesMetadatasId", "t0"."Id", "t0"."ExternalTag", "t0"."NormalizedTitle", "t0"."Title", "t"."Id", "t"."Id0"
FROM (
    SELECT "s"."Id", "s0"."Id" AS "Id0"
    FROM "Series" AS "s"
    LEFT JOIN "SeriesMetadata" AS "s0" ON "s"."Id" = "s0"."SeriesId"
    WHERE "s"."Id" = @__seriesId_0
    LIMIT 1
) AS "t"
INNER JOIN (
    SELECT "g"."GenresId", "g"."SeriesMetadatasId", "g0"."Id", "g0"."ExternalTag", "g0"."NormalizedTitle", "g0"."Title"
    FROM "GenreSeriesMetadata" AS "g"
    INNER JOIN "Genre" AS "g0" ON "g"."GenresId" = "g0"."Id"
) AS "t0" ON "t"."Id0" = "t0"."SeriesMetadatasId"
ORDER BY "t"."Id", "t"."Id0"
2022-10-04T18:15:57.9279820+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (0ms) [Parameters=[@__seriesId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT "t0"."PeopleId", "t0"."SeriesMetadatasId", "t0"."Id", "t0"."Name", "t0"."NormalizedName", "t0"."Role", "t"."Id", "t"."Id0"
FROM (
    SELECT "s"."Id", "s0"."Id" AS "Id0"
    FROM "Series" AS "s"
    LEFT JOIN "SeriesMetadata" AS "s0" ON "s"."Id" = "s0"."SeriesId"
    WHERE "s"."Id" = @__seriesId_0
    LIMIT 1
) AS "t"
INNER JOIN (
    SELECT "p"."PeopleId", "p"."SeriesMetadatasId", "p0"."Id", "p0"."Name", "p0"."NormalizedName", "p0"."Role"
    FROM "PersonSeriesMetadata" AS "p"
    INNER JOIN "Person" AS "p0" ON "p"."PeopleId" = "p0"."Id"
) AS "t0" ON "t"."Id0" = "t0"."SeriesMetadatasId"
ORDER BY "t"."Id", "t"."Id0"
2022-10-04T18:15:57.9296587+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (0ms) [Parameters=[@__seriesId_0='?' (DbType = Int32)], CommandType='Text', CommandTimeout='30']
SELECT "t0"."SeriesMetadatasId", "t0"."TagsId", "t0"."Id", "t0"."ExternalTag", "t0"."NormalizedTitle", "t0"."Title", "t"."Id", "t"."Id0"
FROM (
    SELECT "s"."Id", "s0"."Id" AS "Id0"
    FROM "Series" AS "s"
    LEFT JOIN "SeriesMetadata" AS "s0" ON "s"."Id" = "s0"."SeriesId"
    WHERE "s"."Id" = @__seriesId_0
    LIMIT 1
) AS "t"
INNER JOIN (
    SELECT "s1"."SeriesMetadatasId", "s1"."TagsId", "t1"."Id", "t1"."ExternalTag", "t1"."NormalizedTitle", "t1"."Title"
    FROM "SeriesMetadataTag" AS "s1"
    INNER JOIN "Tag" AS "t1" ON "s1"."TagsId" = "t1"."Id"
) AS "t0" ON "t"."Id0" = "t0"."SeriesMetadatasId"
ORDER BY "t"."Id", "t"."Id0"
2022-10-04T18:15:57.9300398+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "c"."Id", "c"."CoverImage", "c"."CoverImageLocked", "c"."NormalizedTitle", "c"."Promoted", "c"."RowVersion", "c"."Summary", "c"."Title"
FROM "CollectionTag" AS "c"
ORDER BY "c"."NormalizedTitle"
2022-10-04T18:15:57.9303574+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "g"."Id", "g"."ExternalTag", "g"."NormalizedTitle", "g"."Title"
FROM "Genre" AS "g"
2022-10-04T18:15:57.9373077+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (7ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "p"."Id", "p"."Name", "p"."NormalizedName", "p"."Role"
FROM "Person" AS "p"
ORDER BY "p"."Name"
2022-10-04T18:15:58.0362199+02:00	INFO	[Microsoft.EntityFrameworkCore.Database.Command]	[Microsoft.EntityFrameworkCore.Database.Command.CommandExecuted]	Executed DbCommand (0ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
SELECT "t"."Id", "t"."ExternalTag", "t"."NormalizedTitle", "t"."Title"
FROM "Tag" AS "t"
2022-10-04T18:15:58.0454907+02:00	FAIL	[API.Services.SeriesService]	[0]	There was an exception when updating metadataSystem.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at API.Services.SeriesService.UpdatePeopleList(PersonRole role, ICollection`1 tags, Series series, IReadOnlyCollection`1 allTags, Action`1 handleAdd, Action onModified) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\SeriesService.cs:line 344
   at API.Services.SeriesService.UpdateSeriesMetadata(UpdateSeriesMetadataDto updateSeriesMetadataDto) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\SeriesService.cs:line 135

2022-10-04T18:15:58.0456362+02:00	INFO	[Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor]	[ObjectResultExecuting]	Executing BadRequestObjectResult, writing value of type 'System.String'.
2022-10-04T18:15:58.0457224+02:00	INFO	[Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker]	[ActionExecuted]	Executed action API.Controllers.SeriesController.UpdateSeriesMetadata (API) in 119.8167ms
2022-10-04T18:15:58.0457410+02:00	INFO	[Microsoft.AspNetCore.Routing.EndpointMiddleware]	[ExecutedEndpoint]	Executed endpoint 'API.Controllers.SeriesController.UpdateSeriesMetadata (API)'
2022-10-04T18:15:58.0457677+02:00	INFO	[Microsoft.AspNetCore.Hosting.Diagnostics]	[2]	Request finished HTTP/1.1 POST http://localhost:5000/api/series/metadata application/json 4890 - 400 - text/plain;+charset=utf-8 120.4051ms

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome latest
 - Version 0.5.5.0

**Additional context**
I have at least two series thar are impacted.

**Comment by majora2007** [comment]
I'm going to guess, since the logs don't provide much info, that the issue is with the scan loop. I've identified some bugs where it could, in rare occasions, create duplicates or corrupt some entries in the DB due to concurrency. I've fixed these in the nightly and am in testing with our testers. 

But since this is a dupe issue, you would likely want to identify the files in questions, ensure you are adhering to the Folder structure requirements (on the wiki) and rescan.

**Comment by Selid** [comment]
Okay I'm going to be specific for one of the concerned serie : Akira.
It was in a folder "Akira (1990)" at the root of the folder librairie, so i rename it "Akira", delete from kavita, rescan --> no change
I change the name of each issue to be "Akira XX" instead of "Akira - name of the edition - XX", delete and rescan --> no change
I reconvert the file from cbz to cbz with comicrack and rescan --> no change
I tried to change some metadat with comickrack, rescan --> no change

I'm not sure what I can do. What language is used for the db ? Should I try to directly look and edit it ?

**Comment by majora2007** [comment]
First off, why are you deleting from Kavita after you make changes? If you do a library scan afterwards then Kavita will just update the path or handle deleting for you. 

Some of the changes you made shouldn't result in changes. The only one that should elicit a change would be changing the issues, and that is only if you're filling the correct field. 

What field in the comicinfo.xml are you altering?

**Comment by Selid** [comment]
I was deleting from Kavita to be sure the deletion would happen. Since this is a dupe issue, I'm guessing that a previous deletion did not occur when it should have.

I've changed the age limit and language, since it is one of the few serie that have those set in comicrack directly, I was trying to see if that was the issue (all metadata from comicrack are in the cbz archive).

So now I have Akira/Akira XX.cbz structure which should work. But I still can't make any change to the serie. I'm mainly trying to put the story, age, genre, completed and tag.

**Comment by majora2007** [comment]
I just noticed you're on an outdated version of Kavita. Can you please update to v0.5.6 and retest? I don't support older versions of Kavita. Your issue is likely already solved in the latest.

**Comment by Selid** [comment]
So... I've tried some things without success : 
- Deleting the librairie and readding it
- Deleting the serie, renaming the folder, the file and the serie name inside the metada to Akira Test
- Looking into the db for some duplicate id/name

I have no clue as to why some series are impacted and the other aren't. At this point I am tempted to do a clean install of Kavita and see if it changes something...

**Comment by majora2007** [comment]
You still haven't answered my question as to what field you are editing. It's hard to provide support without a way to reproduce or the source files. Reach out to me via discord and update this ticket with the needed details and I can help you.

**Comment by Selid** [comment]
>  I'm mainly trying to put the story, age, genre, completed and tag.

I thought it was clear in my answer, but since I'm not english native, maybe not. So it was the publication status, summarry, language, Age rating, genre and tags. Each of those fails individually, and from my tests, any changes is refused. 

I've made a new folder with a clean kavita in it, rescan my manga folder and I can edit the serie in this instance, so it's not file related.

**Comment by majora2007** [comment]
I'm not really sure how to help you because I'm not fully grasping the issue. The scan loop however has bugs in it in the v0.5.6 release and many changes and fixes have been applied in the nightly. A new release is right around the corner, so I'd say, let's hold off on this and revisit after v0.6.0

**Comment by majora2007** [comment]
Hi, with v0.6.0 out, can you please retest and close the issue if your issue was fixed?

**Comment by Selid** [comment]
It is now fixed yeah. Thanks for the support.
