### ISSUE TITLE
Access to DbContext is not synchronized for multithreaded case

### ISSUE THREAD

**Issue by raminrahimzada** [Kareadita/Kavita#1593]
**P.S.**
Hi everyone, thank you all, such a nice library

**Describe the bug**
Access to DbContext is not synchronized for multithreaded case

**To Reproduce**
Add a folder than have many files inside

 - OS: Windows
 - Browser: Chrome
 - Version 0.5.6.0

```
FAIL	[API.Services.Tasks.Scanner.ProcessSeries]	

There was an exception finding existing series for 23410500150840-257876 with Localized name of  for library 1. 

This indicates you have duplicate series with same name or localized name in the library.  
Correct this and rescan -- (probably false positive error message, see the error below)

System.InvalidOperationException: A second operation was started on this context instance before a previous operation completed. 
This is usually caused by different threads concurrently using the same instance of DbContext.
 For more information on how to avoid threading issues with DbContext, see https://go.microsoft.com/fwlink/?linkid=2097913.

   at Microsoft.EntityFrameworkCore.Infrastructure.Internal.ConcurrencyDetector.EnterCriticalSection()
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.cs:line 193

```

**Comment by majora2007** [comment]
This is already solved for, on the upcoming release. Thanks for reporting.
