### ISSUE TITLE
BUG: announcement markdown parsing broken in nightly 

### ISSUE THREAD

**Issue by vbpal** [Kareadita/Kavita#1753]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
Clicking on the announcements page in 0.6.1.29 results in an error where it does not load any announcements and just has a spinning green arrow

Below is the log error:  

[Kavita] [2023-01-21 03:54:27.766 +00:00  119] [Error] API.Middleware.ExceptionMiddleware There was an exception

System.IO.FileNotFoundException: Could not load file or assembly 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

File name: 'System.Drawing.Common, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

   at MarkdownDeep.Markdown.OnGetImageSize(String url, Boolean TitledImage, Int32& width, Int32& height)

   at MarkdownDeep.Markdown.OnPrepareImage(HtmlTag tag, Boolean TitledImage)

   at MarkdownDeep.LinkDefinition.RenderImg(Markdown m, StringBuilder b, String alt_text)

   at MarkdownDeep.SpanFormatter.Render(StringBuilder sb, String str)

   at MarkdownDeep.SpanFormatter.FormatParagraph(StringBuilder dest, String str, Int32 start, Int32 len)

   at MarkdownDeep.Block.Render(Markdown m, StringBuilder b)

   at MarkdownDeep.Markdown.Transform(String str, Dictionary`2& definitions)

   at MarkdownDeep.Markdown.Transform(String str)

   at API.Services.Tasks.VersionUpdaterService.CreateDto(GithubReleaseMetadata update) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/VersionUpdaterService.cs:line 97

   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()

   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.Serialization.JsonConverter`1.WriteCoreAsObject(Utf8JsonWriter writer, Object value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)

   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)

   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)

   at System.Text.Json.JsonSerializer.WriteStreamAsync[TValue](Stream utf8Json, TValue value, JsonTypeInfo jsonTypeInfo, CancellationToken cancellationToken)

   at Microsoft.AspNetCore.Mvc.Formatters.SystemTextJsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|30_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)

   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)

   at API.Startup.<>c.<<Configure>b__4_4>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 316

--- End of stack trace from previous location ---

   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)

   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)

   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)

   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 53

[Kavita] [2023-01-21 03:54:27.771 +00:00  119] [Error] Microsoft.AspNetCore.Server.Kestrel Connection id "0HMNRC2IDNO7V", Request id "0HMNRC2IDNO7V:00000002": An unhandled exception was thrown by the application.

System.InvalidOperationException: Headers are read-only, response has already started.

   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpHeaders.ThrowHeadersReadOnlyException()

   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpResponseHeaders.Microsoft.AspNetCore.Http.IHeaderDictionary.set_ContentType(StringValues value)

   at Microsoft.AspNetCore.Http.DefaultHttpResponse.set_ContentType(String value)

   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 53

   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

**To Reproduce**
1. Go to announcements page

**Expected behavior**
A list of announcements

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser Chrome
 - Version: 108

**Comment by majora2007** [comment]
Nice find. This is my fault for removing a library needed for markdown parsing.
