### ISSUE TITLE
Error when sending invitations but resend works

### ISSUE THREAD

**Issue by 1024mb** [Kareadita/Kavita#1763]
I was trying to send invitations and noticed that no emails were being sent unless I clicked "Resend", then I found this in Kavita's log -there is nothing in the email server's log.

```
[Kavita] [2023-01-28 18:30:48.365 -05:00  4] [Fatal] API.Controllers.AccountController [Invite User]: Email Link for REDACTED.com: http://192.168.191.110:6002/registration/confirm-email?token=REDACTED&email=REDACTED.com
[Kavita] [2023-01-28 18:30:48.367 -05:00  4] [Fatal] API.Controllers.AccountController [Invite User]: Token REDACTED.com: REDACTED
```

I got that for 2 users I tried inviting, then for a third one I got this:

```
[Kavita] [2023-01-28 23:25:46.829 -05:00  68] [Error] API.Services.EmailService There was an exception when interacting with Email Service
Flurl.Http.FlurlHttpException: Call failed with status code 500 (Internal Server Error): POST http://192.168.191.110:5003/api/invite/email-migration
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at API.Services.EmailService.SendEmailWithPost(String url, Object data, Int32 timeoutSecs) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\EmailService.cs:line 171
```
As I said, the email server's log has nothing.

**Comment by majora2007** [comment]
I know this is quite old, but recently I added better logging to the KavitaEmail service along with some fixes on the UI side, so hopefully it's fixed. I'm not able to reproduce myself. 

I do know that our email service we host is under heavy load, so sometimes it can reject sending emails. The logs should reflect that.

**Comment by HammyHavoc** [comment]
Think I'm seeing this problem too.

I'm using KavitaEmail as a separate container, it *can* function, but generally only after both Kavita and KavitaEmail containers are restarted, and it generally only works temporarily, i.e., after sending the first invite, you're back to needing to restart them to proceed any further.

When a bad invite happens, the user does not appear in the list of users in the admin area, however, an email is still sent.

The email that is sent during a bad invite process does not contain a token in the URL to be able to confirm the email address.

IMO, it's some kind of problem with adding users to the database, thus no token is generated to include in the email.

An example of a URL included in the email: `https://kavita.mydomainiscensoredinfo.com/registration/confirm-email?token=&email=usernameiscensored%40censoreddomain.com`

Functioning invites send the token in the URL as expected, and the user also appears in the list of the admin area.

I also don't see why we can't just add an account without an email address, it seems strange to force the requirement of an email address for something designed for personal use. Sure, password resets, OK, but if someone is on a Kavita server, I'm assuming it's a relative of the admin, so asking to have the password reset is always an option. Sure, it's nice that it can do it, but seems there's a lot of complexity that could be made much more simplistic and reliable.
