### ISSUE TITLE
Bug with "Sequence contains more than one matching element"

### ISSUE THREAD

**Issue by zeedif** [Kareadita/Kavita#1772]
Ayudame a actualizar el siguiente formato de reporte para github en ingles:
**Describe the bug**
When attempting to open volume 1 and 2 of the series "Violet Evergarden" in epub format using Kavita, an error occurs when clicking the "Read" button in either volume.

**To Reproduce**
1. Upload the two new epubs to the "drive" folder
2. Go to Libraries
3. Click the "Scan Library" button
4. Find the "Violet Evergarden" series
5. Go to Books
6. Click the "Read" button for each volume
7. Error message "Sequence contains more than one matching element" is displayed in red.

**Expected behavior**
The volumes should open and be able to be read.

**Screenshots**
```kavita          | [Kavita] [2023-02-02 20:25:32.022 +00:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access responded 200 in 3.1577 ms
kavita          | [Kavita] [2023-02-02 20:25:32.373 +00:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/readinglist/lists-for-series responded 200 in 2.9753 ms
kavita          | [Kavita] [2023-02-02 20:25:32.374 +00:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/want-to-read responded 200 in 4.1172 ms
kavita          | [Kavita] [2023-02-02 20:25:32.381 +00:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/type responded 200 in 6.5399 ms
kavita          | [Kavita] [2023-02-02 20:25:32.382 +00:00  45] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/metadata responded 200 in 21.0030 ms
kavita          | [Kavita] [2023-02-02 20:25:32.383 +00:00  6] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/has-progress responded 200 in 8.7662 ms
kavita          | [Kavita] [2023-02-02 20:25:32.383 +00:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/continue-point responded 200 in 9.1397 ms
kavita          | [Kavita] [2023-02-02 20:25:32.394 +00:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/538 responded 200 in 12.1076 ms
kavita          | [Kavita] [2023-02-02 20:25:32.693 +00:00  6] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/series-detail responded 200 in 20.7949 ms
kavita          | [Kavita] [2023-02-02 20:25:32.704 +00:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/time-left responded 200 in 18.7229 ms
kavita          | [Kavita] [2023-02-02 20:25:32.710 +00:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/all-related responded 200 in 38.0642 ms
kavita          | [Kavita] [2023-02-02 20:25:32.735 +00:00  6] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/metadata/all-languages responded 200 in 31.8666 ms
kavita          | [Kavita] [2023-02-02 20:25:33.063 +00:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/volume-cover responded 304 in 3.2500 ms
kavita          | [Kavita] [2023-02-02 20:25:33.064 +00:00  6] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/volume-cover responded 304 in 1.3442 ms
kavita          | [Kavita] [2023-02-02 20:25:33.065 +00:00  45] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/volume-cover responded 304 in 1.2986 ms
kavita          | [Kavita] [2023-02-02 20:25:33.071 +00:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/volume-cover responded 304 in 5.8549 ms
kavita          | [Kavita] [2023-02-02 20:25:35.313 +00:00  120] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access responded 200 in 2.0505 ms
kavita          | [Kavita] [2023-02-02 20:25:35.662 +00:00  120] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-reading-progress responded 200 in 8.0830 ms
kavita          | [Kavita] [2023-02-02 20:25:35.671 +00:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/book/2603/book-info responded 200 in 9.1261 ms
kavita          | [Kavita] [2023-02-02 20:25:35.913 +00:00  57] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/chapter responded 200 in 2.1408 ms
kavita          | [Kavita] [2023-02-02 20:25:35.922 +00:00  72] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/get-progress responded 200 in 6.6551 ms
kavita          | [Kavita] [2023-02-02 20:25:35.953 +00:00  45] [Error] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/book/2603/chapters responded 500 in 38.2446 ms
kavita          | System.InvalidOperationException: Sequence contains more than one matching element
kavita          |    at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
kavita          |    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
kavita          |    at API.Services.BookService.CoalesceKey(EpubBookRef book, IDictionary`2 mappings, String key) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 740
kavita          |    at API.Services.BookService.GenerateTableOfContents(Chapter chapter) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 786
kavita          |    at API.Controllers.BookController.GetBookChapters(Int32 chapterId) in /home/runner/work/Kavita/Kavita/API/Controllers/BookController.cs:line 129
kavita          |    at lambda_method2428(Closure , Object )
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
kavita          |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
kavita          |    at API.Startup.<>c.<<Configure>b__4_4>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 316
kavita          | --- End of stack trace from previous location ---
kavita          |    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
kavita          | [Kavita] [2023-02-02 20:25:35.963 +00:00  45] [Error] API.Middleware.ExceptionMiddleware There was an exception
kavita          | System.InvalidOperationException: Sequence contains more than one matching element
kavita          |    at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
kavita          |    at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
kavita          |    at API.Services.BookService.CoalesceKey(EpubBookRef book, IDictionary`2 mappings, String key) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 740
kavita          |    at API.Services.BookService.GenerateTableOfContents(Chapter chapter) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 786
kavita          |    at API.Controllers.BookController.GetBookChapters(Int32 chapterId) in /home/runner/work/Kavita/Kavita/API/Controllers/BookController.cs:line 129
kavita          |    at lambda_method2428(Closure , Object )
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
kavita          |    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
kavita          |    at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
kavita          |    at API.Startup.<>c.<<Configure>b__4_4>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 316
kavita          | --- End of stack trace from previous location ---
kavita          |    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
kavita          |    at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
kavita          |    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
kavita          |    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
kavita          |    at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
kavita          |    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
kavita          |    at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 53
kavita          | [Kavita] [2023-02-02 20:25:36.534 +00:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/users/has-library-access responded 200 in 2.6428 ms
kavita          | [Kavita] [2023-02-02 20:25:36.825 +00:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 3.1560 ms
kavita          | [Kavita] [2023-02-02 20:25:36.833 +00:00  57] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/has-progress responded 200 in 1.4925 ms
kavita          | [Kavita] [2023-02-02 20:25:36.833 +00:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/readinglist/lists-for-series responded 200 in 1.6497 ms
kavita          | [Kavita] [2023-02-02 20:25:36.841 +00:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/want-to-read responded 200 in 7.1085 ms
kavita          | [Kavita] [2023-02-02 20:25:36.842 +00:00  57] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/continue-point responded 200 in 8.6986 ms
kavita          | [Kavita] [2023-02-02 20:25:36.845 +00:00  45] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/538 responded 200 in 9.5381 ms
kavita          | [Kavita] [2023-02-02 20:25:36.851 +00:00  72] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/metadata responded 200 in 19.4465 ms
kavita          | [Kavita] [2023-02-02 20:25:37.142 +00:00  6] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/series-detail responded 200 in 36.4314 ms
kavita          | [Kavita] [2023-02-02 20:25:37.145 +00:00  54] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/reader/time-left responded 200 in 13.2719 ms
kavita          | [Kavita] [2023-02-02 20:25:37.174 +00:00  72] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/all-related responded 200 in 69.6186 ms
kavita          | [Kavita] [2023-02-02 20:25:37.482 +00:00  6] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/volume-cover responded 304 in 1.2241 ms
kavita          | [Kavita] [2023-02-02 20:25:37.482 +00:00  45] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/volume-cover responded 304 in 1.2722 ms
kavita          | [Kavita] [2023-02-02 20:25:37.482 +00:00  72] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/volume-cover responded 304 in 1.2019 ms
kavita          | [Kavita] [2023-02-02 20:25:37.483 +00:00  54] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/volume-cover responded 304 in 1.3714 ms
```

**Desktop (please complete the following information):**
 - OS: Debian 11
 - Running Kavita in a Docker 
 - Browser: Microsoft Edge (Chromium)
 - Kavita version: 0.6.1.34

**Additional context**
The volumes should open and be able to be read.
I updated Kavita today from version 0.6.1.30 to 0.6.1.34.

**Comment by majora2007** [comment]
This looks like an issue where the code to fallback when there are bad metadata keys is actually finding multiple. 

var correctedKey = book.Content.Html.Keys.SingleOrDefault(s => s.EndsWith(key));

I can change this to FirstOrDefault instead to handle this case better.
