### ISSUE TITLE
Kavita container isn't starting

### ISSUE THREAD

**Issue by Richugireesh** [Kareadita/Kavita#1808]
I am having the same issue, except this is my first time installing kavita reader. This is almost same as #is1806.

`[Kavita] [2023-02-19 09:04:49.851 +00:00  1] [Fatal] API.Program A migration failed during startup. Restoring backup from /kavita/config/temp/migration/vUnknown and exiting
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at API.Program.Main(String[] args) in /home/runner/work/Kavita/Kavita/API/Program.cs:line 94`

My appsettings.json  is

`{
  "TokenKey": ,
  "Port": 5000,
  "IpAddresses": null
}`

**Comment by majora2007** [comment]
This issue is saying that Kavita cannot open the database file we created. Can you check the permissions of where Kavita is installed?

**Comment by Richugireesh** [comment]
I have changed the permissions to allow everything, but no change in the situation.

.rwxrwxrwx.  261 B Sun Feb 19 14:32:28 2023  appsettings.json
drwxrwxrwx.    0 B Sun Feb 19 14:32:28 2023  bookmarks
drwxrwxrwx.    0 B Sun Feb 19 14:32:28 2023  cache
drwxrwxrwx.    0 B Sun Feb 19 14:32:28 2023  covers
.rwxrwxrwx.   0 B Sun Feb 19 14:32:29 2023  kavita.db
drwxrwxrwx.   36 B Sun Feb 19 14:32:29 2023  logs
drwxrwxrwx.  18 B Sun Feb 19 14:32:29 2023  temp
drwxrwxrwx.    0 B Sun Feb 19 14:32:28 2023  themes

**Comment by therobbiedavis** [comment]
Can you confirm this actually /kavita/config/temp/migration/vUnknown

**Comment by majora2007** [comment]
And please confirm what version you are upgrading from?

**Comment by Richugireesh** [comment]
One important detail that I forgot to mention is that I am using podman. I have installed docker and tried the same, and it's starting fine, but It is not finding the e-books (EPUB & PDF). But I believe that's an issue of not following the naming convention, which I am attempting to fix now. 

Thank you for your time.
