### ISSUE TITLE
Error when trying to open Comic or Manga

### ISSUE THREAD

**Issue by Jestern** [Kareadita/Kavita#1811]
**If this is a feature request, request [here](https://feats.kavitareader.com/) instead. Feature requests will be deleted from Github.**

Please put as much information as possible to help me understand your issue. OS, browser, version are very important!

**Describe the bug**
When trying to read some comics or manga I got an error related to Manga.CreatedUtc (please see attached screenshot). Looking in the container logs the following exception is shown.

`
[Kavita] [2023-02-19 14:25:47.332 +01:00  61] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.InvalidOperationException: An error occurred while reading a database value for property 'MangaFile.CreatedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 23:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1022(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1022(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.PopulateSplitIncludeCollectionAsync[TIncludingEntity,TIncludedEntity](Int32 collectionId, RelationalQueryContext queryContext, IExecutionStrategy executionStrategy, Boolean detailedErrorsEnabled, SplitQueryResultCoordinator resultCoordinator, RelationalCommandCache relationalCommandCache, Func`3 childIdentifier, IReadOnlyList`1 identifierValueComparers, Func`5 innerShaper, Func`4 relatedDataLoaders, INavigationBase inverseNavigation, Action`2 fixup, Boolean trackingQuery)
   at Microsoft.EntityFrameworkCore.Query.RelationalShapedQueryCompilingExpressionVisitor.ShaperProcessingExpressionVisitor.TaskAwaiter(Func`1[] taskFactories)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at API.Data.Repositories.ChapterRepository.GetChapterAsync(Int32 chapterId, ChapterIncludes includes) in /home/runner/work/Kavita/Kavita/API/Data/Repositories/ChapterRepository.cs:line 172
   at API.Services.CacheService.Ensure(Int32 chapterId, Boolean extractPdfToImages) in /home/runner/work/Kavita/Kavita/API/Services/CacheService.cs:line 145
   at API.Controllers.ReaderController.GetChapterInfo(Int32 chapterId, Boolean extractPdf, Boolean includeDimensions) in /home/runner/work/Kavita/Kavita/API/Controllers/ReaderController.cs:line 185
   at lambda_method987(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at API.Startup.<>c.<<Configure>b__4_4>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 324
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 53
`

**To Reproduce**
1. Go to Kavita
2. Click on a manga or comic book
3. Click on read

**Expected behavior**
The books opens and can be read.

**Screenshots**
![image](https://user-images.githubusercontent.com/3172340/219951200-4e71e9a1-9204-4ef1-926e-34c24f3c9bcf.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Server: Docker
 - Browser Vivaldi (or any other)
 - Version 0.7.0

**Additional context**
It seems this issue can be solved updating the kavita database with the following query
`
UPDATE MangaFile SET CreatedUtc = '0001-01-01 00:00:00' WHERE CreatedUtc = '0000-12-31 23:00:00'
`

It seems the error comes from some mangas which have the CreatedUtc column filled with '0000-12-31 23:00:00'
![image](https://user-images.githubusercontent.com/3172340/219951674-3f3c13b4-ba87-4e4f-9757-e8c9258ed826.png)

**Comment by majora2007** [comment]
Can you please go into your config/backups and grab a backup from before the release and send me just the db file? I've seen one other user have this issue. 

Please also confirm your timezone for me.

**Comment by Jestern** [comment]
Hi @majora2007, I´ve just sent an email with the db file. My timezone is GMT+1 or CET

**Comment by HerrFrutti** [comment]
While marking a manga as read or unread and then opening  the info tab in settings.
![PNG-Bild](https://user-images.githubusercontent.com/6975702/219956760-ba92a870-f916-4490-913f-fa26b7fc7e38.png)
This error when opening the statistics:
![PNG-Bild](https://user-images.githubusercontent.com/6975702/219956776-12550c0f-e16d-48c1-8e99-fd68113bf68c.png)

I'm getting those errors from the db. I can send you my db backup too, if needed.

**Comment by majora2007** [comment]
@HerrFrutti are you also in GMT+1 timezone? This issue seems pretty confined to that timezone, but unable to figure out why UTC conversion (which is done completely by the DB) is failing.

**Comment by majora2007** [comment]
Okay I wasn't able to figure out why this occurred, but I have a fix ready for the upcoming hotfix. It will be release either today or tomorrow.

**Comment by majora2007** [comment]
This was closed in v0.7.1

**Comment by by275** [comment]
This issue also appears to GMT+9 timezone. You may need to db update something like `UPDATE Series SET CreatedUtc = '0001-01-01 00:00:00' WHERE CreatedUtc = '0000-12-31 15:00:00';`
