### ISSUE TITLE
clean install won't startup stuck on db migration

### ISSUE THREAD

**Issue by benpoe** [Kareadita/Kavita#1826]
I had to reinstall my docker environment, but get stuck on kavita which refuses to startup, proclaiming a mallformed database. I've deleted the config folder and cache hoping for a clean install.

trying an new image :latest and nightly-0.7.1.3 kavita fails to startup. the log says it's doing db migration (on a new db?) and then nothing

```
[Kavita] [2023-02-22 10:47:30.045 +00:00  1] [Information] API.Program Database backed up to vUnknown
[Kavita] [2023-02-22 10:47:30.516 +00:00  1] [Fatal] API.Program Running MigrateSeriesRelationsExport migration - Please be patient, this may take some time. This is not an error
[Kavita] [2023-02-22 10:47:30.907 +00:00  1] [Fatal] API.Program Running MigrateSeriesRelationsExport migration - complete. Nothing to do
CREATE TABLE "ef_temp_ServerSetting" (
    "RowVersion" INTEGER NOT NULL,
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'table "ef_temp_ServerSetting" already exists'.
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.MigrationCommandExecutor.ExecuteNonQueryAsync(IEnumerable`1 migrationCommands, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
[Kavita] [2023-02-22 10:47:29.439 +00:00  1] [Information] API.Program Performing backup as migrations are needed. Backup will be kavita.db in temp folder
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at API.Program.Main(String[] args) in /home/runner/work/Kavita/Kavita/API/Program.cs:line 93
```

**Comment by majora2007** [comment]
I'm closing this out. If you still have an issue, please comment and I will reopen and engage in support with you.
