### ISSUE TITLE
No file is added to the library after updating to v0.7.1.4

### ISSUE THREAD

**Issue by AshDevFr** [Kareadita/Kavita#1864]
**Describe the bug**

I had an old (probably `v0.5.x`) version of Kavita running on a Ubutu VM. 
It was working nicely and I decided to update to `v0.7.1.4` to get the latest features and bug fixes.

After restarting the server, my manga library was present but empty. I thought it just needed a re-scan so I scanned the library again but it did not find anything.

I tried to delete and recreate the library and it did not work.

I decided to reinstall the app and restart from scratch but it did not help, no matter what I do the page shows `0 Series`.

The log shows a lot of `file found` but nothing appears in the library.

Some logs:
```
Mar 08 01:05:10 kavita Kavita[1182]: [Kavita] [2023-03-08 01:05:10.821 +00:00  44] [Debug] API.Services.DirectoryService [ScanFiles] called on /mnt/Mangas/King of Hell
Mar 08 01:05:10 kavita Kavita[1182]: [Kavita] [2023-03-08 01:05:10.823 +00:00  44] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 50 files for /mnt/Mangas/King of Hell
```

The `King of Hell` folder is organized like this

```
<library_root_directory>
|
--- King of Hell
     |
     --- King of Hell - v01.cbz
     --- King of Hell - v02.cbz
     --- King of Hell - v03.cbz
     --- ...
```

**To Reproduce**
1. Create a Manga library with `cbz` files
2. Scan
3. `0 Series`

**Expected behavior**
It used to find all my mangas so I expect it to still find them

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.4 LTS
 - Browser: Chrome
 - Version: 110.0.5481.177 (Official Build) (arm64)

**Comment by scare376** [comment]
https://wiki.kavitareader.com/en/guides/managing-your-files/scanner The scan loop was upgraded a while back. I would check that link and see if your library follows the new requirements. (Note library root means the folder you selected for the library on the libraries settings page in kavita)

**Comment by therobbiedavis** [comment]
@AshDevFr This is a known issue with stable 0.7.1.x and has already been fixed in the nightly releases AFAIK. I would recommend using [v0.6.1](https://github.com/Kareadita/Kavita/releases/tag/v0.6.1) until the next stable release.

**Comment by therobbiedavis** [comment]
I apologize, I got it mixed up with another known issue. For this we need more information.
Can you provide a couple things while on v0.7.1.4:
- The full logs of the scan after performing a "Force Scan" located in the modal after clicking what you see here.
![image](https://user-images.githubusercontent.com/7907265/223736500-1cfe0b4a-1576-4d27-b0cb-55215c7e653e.png)
- The comicinfo.xml that is inside one of the .cbz (if there is one)

**Comment by AshDevFr** [comment]
I moved a subset of files in a different directory to test so the logs would be smaller.

I also removed the `ComicInfo.xml` file from the volume 1 and re-scanned.

Now it picks up volume 1 and 2, not 3 and 4.
I have not changed the volume 2 so it's weird that it's picking it up this time

<details>
  <summary>Logs</summary>

```
Mar 08 16:06:02 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:02.986 +00:00  25] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/settings/library-types responded 200 in 2.3493 ms
Mar 08 16:06:03 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:03.091 +00:00  25] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/name-exists responded 200 in 3.8612 ms
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.558 +00:00  51] [Information] API.Services.TaskScheduler Enqueuing library scan for: 1
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.564 +00:00  18] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.564 +00:00  18] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.565 +00:00  51] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/scan responded 200 in 8.8608 ms
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.567 +00:00  25] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Mangas
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.570 +00:00  25] [Debug] API.Services.DirectoryService [ScanFiles] called on /mnt/Mangas/_tests/King of Hell
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.573 +00:00  25] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 4 files for /mnt/Mangas/_tests/King of Hell
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.601 +00:00  25] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on King of Hell
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.606 +00:00  25] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series King of Hell
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.607 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Updating 2 volumes on King of Hell
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.607 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Looking up volume for 2003
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.608 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing King of Hell - Volume 2003
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.608 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, King of Hell - Vol 2003 Ch 2
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.614 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, King of Hell - Vol 2003 Ch 3
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.620 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, King of Hell - Vol 2003 Ch 4
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.625 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Read ComicInfo for /mnt/Mangas/_tests/King of Hell/King of Hell - v02.cbz
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.626 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Read ComicInfo for /mnt/Mangas/_tests/King of Hell/King of Hell - v03.cbz
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.627 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Read ComicInfo for /mnt/Mangas/_tests/King of Hell/King of Hell - v04.cbz
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.627 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Looking up volume for 1
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.628 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing King of Hell - Volume 1
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.628 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, King of Hell - Vol 1 Ch 0
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.647 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Updated King of Hell volumes from count of 0 to 2
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.648 +00:00  25] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating King of Hell FolderPath to /mnt/Mangas/_tests/King of Hell
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.669 +00:00  25] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Finished series update on King of Hell in 69 ms
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.670 +00:00  25] [Debug] API.Services.MetadataService [MetadataService] Processing cover image generation for series: King of Hell
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.671 +00:00  25] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /mnt/Mangas/_tests/King of Hell/King of Hell - v02.cbz
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.687 +00:00  51] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/2 responded 200 in 11.0820 ms
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.752 +00:00  25] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /mnt/Mangas/_tests/King of Hell/King of Hell - v03.cbz
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.896 +00:00  25] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /mnt/Mangas/_tests/King of Hell/King of Hell - v04.cbz
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.921 +00:00  25] [Debug] API.Services.MetadataService [MetadataService] Generating cover image for /mnt/Mangas/_tests/King of Hell/King of Hell - v01.cbz
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.973 +00:00  25] [Information] API.Services.MetadataService [MetadataService] Updated covers for King of Hell in 303 milliseconds
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.974 +00:00  25] [Debug] API.Services.MetadataService Dispatching 7 update events
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.976 +00:00  25] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 31 milliseconds. Updating database
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.980 +00:00  25] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 4 files and 1 series in 418 milliseconds for Mangas
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.980 +00:00  25] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.981 +00:00  25] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: []
Mar 08 16:06:04 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:04.981 +00:00  25] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete
Mar 08 16:06:05 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:05.010 +00:00  25] [Information] API.Services.Tasks.Metadata.WordCountAnalyzerService [WordCountAnalyzerService] Updated metadata for King of Hell in 13 milliseconds
Mar 08 16:06:05 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:05.011 +00:00  25] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/series-cover responded 200 in 16.8917 ms
Mar 08 16:06:05 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:05.148 +00:00  25] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/image/series-cover responded 200 in 1.9703 ms
Mar 08 16:06:05 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:05.835 +00:00  25] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/library/update responded 200 in 9.4935 ms
Mar 08 16:06:05 kavita Kavita[1182]: [Kavita] [2023-03-08 16:06:05.841 +00:00  25] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library responded 200 in 1.2921 ms
```
</details>

<details>
  <summary>ComicInfo.xml</summary>

```xml
<?xml version="1.0"?>
<ComicInfo xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <Title>Vol. 1</Title>
  <Series>King of Hell</Series>
  <Number>1</Number>
  <Volume>2003</Volume>
  <Summary>In life, Majeh was a gifted swordsman. In death he acts as a whimsical reaper for the King of Hell, collecting the souls of the dead to bring them to the netherworld. All this changes when a mysterious rift opens up between Hell and Earth and evil spirits begin escaping into the mortal realm. Now Majeh must hunt down and destroy these mischievous demons before the rift is permanently opened.</Summary>
  <Notes>Scraped metadata from ComicVine [CVDB247003].</Notes>
  <Year>2003</Year>
  <Month>6</Month>
  <Writer>Ra In-soo</Writer>
  <Penciller>Kim Jae-Hwan</Penciller>
  <Inker>Kim Jae-Hwan</Inker>
  <CoverArtist>Kim Jae-Hwan</CoverArtist>
  <Publisher>Tokyopop</Publisher>
  <Web>https://comicvine.gamespot.com/king-of-hell-1-vol-1/4000-247003/</Web>
  <PageCount>190</PageCount>
  <Characters>Majeh</Characters>
  <Pages>
    <Page Image="0" ImageWidth="728" ImageHeight="1100" Type="FrontCover" />
    <Page Image="1" ImageWidth="734" ImageHeight="1100" />
    <Page Image="2" />
    <Page Image="3" />
    <Page Image="4" />
    <Page Image="5" />
    <Page Image="6" />
    <Page Image="7" />
    <Page Image="8" />
    <Page Image="9" />
    <Page Image="10" />
    <Page Image="11" />
    <Page Image="12" />
    <Page Image="13" />
    <Page Image="14" />
    <Page Image="15" />
    <Page Image="16" />
    <Page Image="17" />
    <Page Image="18" />
    <Page Image="19" />
    <Page Image="20" />
    <Page Image="21" />
    <Page Image="22" />
    <Page Image="23" />
    <Page Image="24" />
    <Page Image="25" />
    <Page Image="26" />
    <Page Image="27" />
    <Page Image="28" />
    <Page Image="29" />
    <Page Image="30" />
    <Page Image="31" />
    <Page Image="32" />
    <Page Image="33" />
    <Page Image="34" />
    <Page Image="35" />
    <Page Image="36" />
    <Page Image="37" />
    <Page Image="38" />
    <Page Image="39" />
    <Page Image="40" />
    <Page Image="41" />
    <Page Image="42" />
    <Page Image="43" />
    <Page Image="44" />
    <Page Image="45" />
    <Page Image="46" />
    <Page Image="47" />
    <Page Image="48" />
    <Page Image="49" />
    <Page Image="50" />
    <Page Image="51" />
    <Page Image="52" />
    <Page Image="53" />
    <Page Image="54" />
    <Page Image="55" />
    <Page Image="56" />
    <Page Image="57" />
    <Page Image="58" />
    <Page Image="59" />
    <Page Image="60" />
    <Page Image="61" />
    <Page Image="62" />
    <Page Image="63" />
    <Page Image="64" />
    <Page Image="65" />
    <Page Image="66" />
    <Page Image="67" />
    <Page Image="68" />
    <Page Image="69" />
    <Page Image="70" />
    <Page Image="71" />
    <Page Image="72" />
    <Page Image="73" />
    <Page Image="74" />
    <Page Image="75" />
    <Page Image="76" />
    <Page Image="77" />
    <Page Image="78" />
    <Page Image="79" />
    <Page Image="80" />
    <Page Image="81" />
    <Page Image="82" />
    <Page Image="83" />
    <Page Image="84" />
    <Page Image="85" />
    <Page Image="86" />
    <Page Image="87" />
    <Page Image="88" />
    <Page Image="89" />
    <Page Image="90" />
    <Page Image="91" />
    <Page Image="92" />
    <Page Image="93" />
    <Page Image="94" />
    <Page Image="95" />
    <Page Image="96" />
    <Page Image="97" />
    <Page Image="98" />
    <Page Image="99" />
    <Page Image="100" />
    <Page Image="101" />
    <Page Image="102" />
    <Page Image="103" />
    <Page Image="104" />
    <Page Image="105" />
    <Page Image="106" />
    <Page Image="107" />
    <Page Image="108" />
    <Page Image="109" />
    <Page Image="110" />
    <Page Image="111" />
    <Page Image="112" />
    <Page Image="113" />
    <Page Image="114" />
    <Page Image="115" />
    <Page Image="116" />
    <Page Image="117" />
    <Page Image="118" />
    <Page Image="119" />
    <Page Image="120" />
    <Page Image="121" />
    <Page Image="122" />
    <Page Image="123" />
    <Page Image="124" />
    <Page Image="125" />
    <Page Image="126" />
    <Page Image="127" />
    <Page Image="128" />
    <Page Image="129" />
    <Page Image="130" />
    <Page Image="131" />
    <Page Image="132" />
    <Page Image="133" />
    <Page Image="134" />
    <Page Image="135" />
    <Page Image="136" />
    <Page Image="137" />
    <Page Image="138" />
    <Page Image="139" />
    <Page Image="140" />
    <Page Image="141" />
    <Page Image="142" />
    <Page Image="143" />
    <Page Image="144" />
    <Page Image="145" />
    <Page Image="146" />
    <Page Image="147" />
    <Page Image="148" />
    <Page Image="149" />
    <Page Image="150" />
    <Page Image="151" />
    <Page Image="152" />
    <Page Image="153" />
    <Page Image="154" />
    <Page Image="155" />
    <Page Image="156" />
    <Page Image="157" />
    <Page Image="158" />
    <Page Image="159" />
    <Page Image="160" />
    <Page Image="161" />
    <Page Image="162" />
    <Page Image="163" />
    <Page Image="164" />
    <Page Image="165" />
    <Page Image="166" />
    <Page Image="167" />
    <Page Image="168" />
    <Page Image="169" />
    <Page Image="170" />
    <Page Image="171" />
    <Page Image="172" />
    <Page Image="173" />
    <Page Image="174" />
    <Page Image="175" />
    <Page Image="176" />
    <Page Image="177" />
    <Page Image="178" />
    <Page Image="179" />
    <Page Image="180" />
    <Page Image="181" />
    <Page Image="182" />
    <Page Image="183" />
    <Page Image="184" />
    <Page Image="185" />
    <Page Image="186" />
    <Page Image="187" />
    <Page Image="188" />
    <Page Image="189" />
  </Pages>
</ComicInfo>
```
</details>

**Comment by therobbiedavis** [comment]
@AshDevFr So what the logs so is that It picked up Volume 1 and Volume 2003. From the comic info I can see the volume is called 2003, which I am assuming is the same for all 4 volumes.

We group chapters of the same volume. So I would imagine if you look at the volume details for 2003 you will see the others group inside like the following:
![image](https://user-images.githubusercontent.com/7907265/223794811-566ee031-a5c5-4ae2-88d8-cb364a746b84.png)

**Comment by AshDevFr** [comment]
Just check and it's what is happening.
Even if it's what's happening for my whole library, should I at least get 1 volume per Serie instead of nothing?

Right now it's working in a small folder with only one serie with only 4 volumes instead of 254 Series with thousands of volumes?

Also I tried searching but nothing was in the search.

![image](https://user-images.githubusercontent.com/7372540/223795546-680c6a10-96e6-4465-98bc-11f9de5a4bf8.png)

**Comment by therobbiedavis** [comment]
> Just check and it's what is happening. Even if it's what's happening for my whole library, should I at least get 1 volume per Serie instead of nothing?
Yes, that should be the case.

If you set the library root for this in Kavita to be `/mnt/Mangas` then it should be working as such (unless you have the same series in multiple locations off the root). If it is still not working as such then I would recommend the Force Scan I mentioned earlier. The force scan bypasses our optimizations to speed up scan times and instead scan everything for that library regardless.

**Comment by AshDevFr** [comment]
I tried the force scan a couple of time and nothing appears.
In the logs I was able to see this but I don't know if it's what is failing the whole scan:

```
Mar 08 18:44:13 kavita Kavita[1182]: System.Xml.XmlException: Data at the root level is invalid. Line 1, position 1.                                                                                                                                                                                                        [94/18261]
Mar 08 18:44:13 kavita Kavita[1182]:    at VersOne.Epub.Utils.TaskExtensionMethods.ExecuteAndUnwrapAggregateException[T](Task`1 task)
Mar 08 18:44:13 kavita Kavita[1182]:    at API.Services.BookService.ParseInfo(String filePath) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 581
Mar 08 18:44:13 kavita Kavita[1182]: [Kavita] [2023-03-08 18:44:13.298 +00:00  53] [Warning] API.Services.BookService [BookService] There was an exception when opening epub book: /mnt/Mangas/Fate Stay Night FR/Fate stay Night - Volume 9.epub
```

**Comment by AshDevFr** [comment]
Ok I was able to import everything after removing a directory.

I had a messed up directory that had a weird name because of an old ssh mistake.

The folder name was `'Kekkaishi\ \(Digital\)'` so `Kekkaishi\\\ \\\(Digital\\\)` without the quotes. It's the only thing I found
