### ISSUE TITLE
Unable to Open Database File (arm64)

### ISSUE THREAD

**Issue by user112200** [Kareadita/Kavita#1914]
**To Reproduce**
Download arm64 version from here via wget. Unzip `tar -xzf kavita-linux-arm64.tar.gz`.
`sudo chmod +x ./Kavita/Kativa` and then `./Kavita/Kavita`

```
Generating JWT TokenKey for encrypting user sessions...
[Kavita] [2023-04-04 21:50:44.551 +09:00  1] [Information] API.Program Performing backup as migrations are needed. Backup will be kavita.db in temp folder
[Kavita] [2023-04-04 21:50:46.059 +09:00  1] [Error] Microsoft.EntityFrameworkCore.Database.Connection An error occurred using the connection to database 'main' on server 'config/kavita.db'.
[Kavita] [2023-04-04 21:50:46.135 +09:00  1] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-04-04 21:50:46.154 +09:00  1] [Information] API.Program Database backed up to /home/user/Kavita/config/temp/migration/vUnknown
[Kavita] [2023-04-04 21:50:46.221 +09:00  1] [Fatal] API.Program Running MigrateSeriesRelationsExport migration - Please be patient, this may take some time. This is not an error
[Kavita] [2023-04-04 21:50:46.222 +09:00  1] [Fatal] API.Program Running MigrateSeriesRelationsExport migration - complete. Nothing to do
[Kavita] [2023-04-04 21:50:46.257 +09:00  1] [Error] Microsoft.EntityFrameworkCore.Database.Connection An error occurred using the connection to database 'main' on server 'config/kavita.db'.
[Kavita] [2023-04-04 21:50:46.264 +09:00  1] [Error] Microsoft.EntityFrameworkCore.Database.Connection An error occurred using the connection to database 'main' on server 'config/kavita.db'.
[Kavita] [2023-04-04 21:50:46.270 +09:00  1] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternalAsync(Boolean errorsExpected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenAsync(CancellationToken cancellationToken, Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.InitializeReaderAsync(AsyncEnumerator enumerator, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-04-04 21:50:46.280 +09:00  1] [Fatal] API.Program A migration failed during startup. Restoring backup from /home/user/Kavita/config/temp/migration/vUnknown and exiting
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteConnectionInternal..ctor(SqliteConnectionStringBuilder connectionOptions, SqliteConnectionPool pool)
   at Microsoft.Data.Sqlite.SqliteConnectionPool.GetConnection()
   at Microsoft.Data.Sqlite.SqliteConnectionFactory.GetConnection(SqliteConnection outerConnection)
   at Microsoft.Data.Sqlite.SqliteConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenInternal(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Sqlite.Storage.Internal.SqliteDatabaseCreator.Create()
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabaseCreator.CreateAsync(CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
   at API.Program.Main(String[] args) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Program.cs:line 93
```

**Information**
 - Device: Raspberry pi 4 and Odroid M1
 - OS: Debian GNU/Linux 11 (bullseye)
 - Kavita Version: v0.7.1.4 and v0.7.1 (both same result)
 - Sqlite3 Version: 3.34.1

**Comment by MrHugojuggernot** [comment]
I've had Kavita since 1 year until database goes corrupted (for unknow reason), same issue by trying to reinstall Kavita (in lastest release or 5.0v)

**Comment by user112200** [comment]
> Your database should not be corrupt, this is usually due to some contention with the OS and the file is locked while Kavita is trying to open it. Is your database on a networked drive (that's something that causes issues like this) or perhaps you have 2 programs opening the db at once?

Database is on internal drive(M.2 NVMe). I'm only running PiHole other than Kavita, so I don't think any other programs would access to the db file.

Anyways, I've deleted everything and installed Kavita again following this [instruction](https://www.makeuseof.com/raspberry-pi-self-host-kavita-access-ebooks-comics-anywhere/) and now I get new errors. Couldn't figure out what's the problem...

Error log when accessing to ip.address:5000
```
Error writing app settings: Could not find file '/home/user/Kavita/config/appsettings.json'.
[Kavita] [2023-04-17 15:19:00.105 +09:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2023-04-17 15:19:00.135 +09:00  1] [Debug] API.Services.TaskScheduler Scheduling Scan Library Task for daily
[Kavita] [2023-04-17 15:19:00.844 +09:00  1] [Debug] API.Services.TaskScheduler Scheduling Backup Task for daily
[Kavita] [2023-04-17 15:19:00.868 +09:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2023-04-17 15:19:00.878 +09:00  1] [Debug] API.Services.TaskScheduler Scheduling stat collection daily
[Kavita] [2023-04-17 15:19:01.413 +09:00  14] [Information] API.Program Running Migrations
[Kavita] [2023-04-17 15:19:01.894 +09:00  14] [Fatal] API.Program Running MigrateChangeRestrictionRoles migration
[Kavita] [2023-04-17 15:19:01.896 +09:00  14] [Information] API.Program MigrateChangeRestrictionRoles migration complete
[Kavita] [2023-04-17 15:19:01.953 +09:00  14] [Fatal] API.Program Running MigrateSeriesRelationsImport migration - Please be patient, this may take some time. This is not an error
[Kavita] [2023-04-17 15:19:01.954 +09:00  14] [Fatal] API.Program Running MigrateSeriesRelationsImport migration - complete. Nothing to do
[Kavita] [2023-04-17 15:19:01.970 +09:00  14] [Fatal] API.Program Running MigrateUserProgressLibraryId migration - Please be patient, this may take some time. This is not an error
[Kavita] [2023-04-17 15:19:01.999 +09:00  14] [Warning] Microsoft.EntityFrameworkCore.Query The query uses the 'First'/'FirstOrDefault' operator without 'OrderBy' and filter operators. This may lead to unpredictable results.
[Kavita] [2023-04-17 15:19:02.035 +09:00  14] [Fatal] API.Program Running MigrateUserProgressLibraryId migration - complete. Nothing to do
[Kavita] [2023-04-17 15:19:02.555 +09:00  14] [Information] API.Program Running Migrations - done
[Kavita] [2023-04-17 15:19:03.418 +09:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://0.0.0.0:5000
[Kavita] [2023-04-17 15:19:03.419 +09:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://[::]:5000
Kavita - v0.7.1.4
[Kavita] [2023-04-17 15:19:03.433 +09:00  1] [Information] Microsoft.Hosting.Lifetime Application started. Press Ctrl+C to shut down.
[Kavita] [2023-04-17 15:19:03.433 +09:00  1] [Information] Microsoft.Hosting.Lifetime Hosting environment: Production
[Kavita] [2023-04-17 15:19:03.434 +09:00  1] [Information] Microsoft.Hosting.Lifetime Content root path: /home/user/Kavita
[Kavita] [2023-04-17 15:21:40.490 +09:00  42] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)
   at API.Extensions.IdentityServiceExtensions.<>c__DisplayClass0_0.<AddIdentityServices>b__2(JwtBearerOptions options) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Extensions\IdentityServiceExtensions.cs:line 53
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.OptionsMonitor`1.<>c__DisplayClass10_0.<Get>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at Microsoft.Extensions.Options.OptionsCache`1.GetOrAdd(String name, Func`1 createOptions)
   at Microsoft.Extensions.Options.OptionsMonitor`1.Get(String name)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.InitializeAsync(AuthenticationScheme scheme, HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\ExceptionMiddleware.cs:line 30
```

Json response
```
{"status":500,"message":"String reference not set to an instance of a String. (Parameter \u0027s\u0027)","details":"   at System.Text.Encoding.GetBytes(String s)\n   at System.Text.UTF8Encoding.UTF8EncodingSealed.GetBytes(String s)\n   at API.Extensions.IdentityServiceExtensions.\u003C\u003Ec__DisplayClass0_0.\u003CAddIdentityServices\u003Eb__2(JwtBearerOptions options) in C:\\Users\\josep\\Documents\\Projects\\KavitaOrg\\Kavita\\API\\Extensions\\IdentityServiceExtensions.cs:line 53\n   at Microsoft.Extensions.Options.ConfigureNamedOptions\u00601.Configure(String name, TOptions options)\n   at Microsoft.Extensions.Options.OptionsFactory\u00601.Create(String name)\n   at Microsoft.Extensions.Options.OptionsMonitor\u00601.\u003C\u003Ec__DisplayClass10_0.\u003CGet\u003Eb__0()\n   at System.Lazy\u00601.ViaFactory(LazyThreadSafetyMode mode)\n--- End of stack trace from previous location ---\n   at System.Lazy\u00601.CreateValue()\n   at Microsoft.Extensions.Options.OptionsCache\u00601.GetOrAdd(String name, Func\u00601 createOptions)\n   at Microsoft.Extensions.Options.OptionsMonitor\u00601.Get(String name)\n   at Microsoft.AspNetCore.Authentication.AuthenticationHandler\u00601.InitializeAsync(AuthenticationScheme scheme, HttpContext context)\n   at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)\n   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)\n   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)\n   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)\n   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)\n   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\\Users\\josep\\Documents\\Projects\\KavitaOrg\\Kavita\\API\\Middleware\\ExceptionMiddleware.cs:line 30"}
```

**Comment by user112200** [comment]
Haven't solved the issue but I installed Kavita on docker and everything worked without problem.
