### ISSUE TITLE
Duplicates reported on manual library scan when there are none

### ISSUE THREAD

**Issue by enchained** [Kareadita/Kavita#1948]
**Describe the bug**
After updating from ~v0.5.2.5 to the latest v0.7.1.4 and manually triggering a library scan, scan errors started to appear, stating that I have duplicate entries in my manga library (library 1) and that I need to somehow correct it, but I can see no duplicates in my file structure and scans and the library worked fine before the update.
UPD: Added logs. From the logs it looks connected to another issue I got after updating: https://github.com/Kareadita/Kavita/issues/1949

**To Reproduce**
1. Manga library - '...' - Scan library
2. Activity turns red and lists errors:
```
There was an exception finding existing series for Tower of God with Localized name of for library 1
Click for more information

There was an exception finding existing series for Goodnight Punpun with Localized name of for library 1
Click for more information

There was an exception finding existing series for Loving Yamada at Lv999! with Localized name of for library 1
Click for more information

There was an exception finding existing series for The Masterful Cat Is Depressed Again Today with Localized name of for library 1
Click for more information

There was an exception finding existing series for Watashitachi no Shiawase na Jikan with Localized name of for library 1
Click for more information
```
4. Detailed error example:
```
There was an exception finding existing series for Watashitachi no Shiawase na Jikan with Localized name of for library 1

This indicates you have duplicate series with same name or localized name in the library. Correct this and rescan.
```
6. Manga library path: /data/libraries/books/manga/
7. Full /manga folder structure:
```
├── Goodnight Punpun
│   ├── Goodnight Punpun Omnibus v01 (2016) (Digital) (1r0n).cbz
│   ├── ...
│   └── Goodnight Punpun Omnibus v07 (2017) (Digital) (1r0n).cbz
├── HIRAETH - The End of the Journey
│   ├── HIRAETH - The End of the Journey v01 (2022) (Digital) (1r0n).cbz
│   ├── HIRAETH - The End of the Journey v02 (2022) (Digital) (1r0n).cbz
│   └── HIRAETH - The End of the Journey v03 (2023) (Digital) (1r0n).cbz
├── I am a Hero
│   ├── I Am a Hero - c001-011 (v01) [Illuminati-Manga & Gantz_Waitingroom].cbz
│   ├── I Am a Hero - c012-022 (v02) [Illuminati-Manga & Gantz_Waitingroom].cbz
│   ├── I Am a Hero - c023-034 (v03) [Illuminati-Manga & Gantz_Waitingroom].cbz
│   ├── I Am a Hero - c035-046 (v04) [Illuminati-Manga].cbz
│   ├── ...
│   ├── I Am a Hero - c180-191 (v16) [Illuminati-Manga].cbz
│   ├── I Am a Hero - c192-204 (v17) [batoto] [Todome!].cbz
│   ├── I Am a Hero - c205-216 (v18) [Todome!] [batoto].cbz
│   ├── I Am a Hero - c217-228 (v19) [Todome!] [batoto].cbz
│   ├── I Am a Hero - c229-238 (v20) [Todome!] [batoto].cbz
│   ├── I Am a Hero - c239-248 (v21) [batoto] [Todome!].cbz
│   ├── I Am a Hero - c249-264 (mix) [v22] [batoto] [Todome!].cbz
│   └── Side Stories
│       ├── I Am a Hero - SP01 - I Am a Hero in Osaka [Todome!].cbz
│       ├── I Am a Hero - SP02 - I Am a Hero in Ibaraki [Nameless].cbr
│       └── I Am a Hero - SP03 - I Am a Hero in Nagasaki [anon + Nameless].cbr
├── Loving Yamada at Lv999!
│   ├── Loving Yamada at Lv999! c063 (Digital) (Oak'n'Stick).cbz
│   ├── ...
│   ├── Loving Yamada at Lv999! c087 (Digital) (Oak'n'Stick).cbz
│   ├── Loving Yamada at Lv999! c088.5 (Digital) (Oak'n'Stick).cbz
│   ├── Loving Yamada at Lv999! c088 (Digital) (Oak'n'Stick).cbz
│   ├── ...
│   ├── Loving Yamada at Lv999! c092 (Digital) (Oak'n'Stick).cbz
│   ├── Loving Yamada at Lv999! v01 (Digital-Compilation) (Oak).cbz
│   ├── ...
│   └── Loving Yamada at Lv999! v06 (Digital-Compilation) (Oak'n'Stick).cbz
├── Machida-kun no Sekai
│   ├── Machida-kun no Sekai v01.cbz
│   ├── ...
│   ├── Machida-kun no Sekai v07.cbz
│   └── Vol.00 - Oneshot.cbz
├── Medalist
│   ├── Medalist v01 (2021) (Digital) (1r0n).cbz
│   ├── ...
│   └── Medalist v06 (2023) (Digital) (1r0n).cbz
├── Our Dreams at Dusk - Shimanami Tasogare
│   ├── Our Dreams at Dusk - Shimanami Tasogare v01 (2019) (Digital) (1r0n).cbz
│   ├── ...
│   └── Our Dreams at Dusk - Shimanami Tasogare v04 (2019) (Digital) (1r0n).cbz
├── The Masterful Cat Is Depressed Again Today
│   ├── The Masterful Cat Is Depressed Again Today v01 (2021) (Digital) (danke-Empire).cbz
│   ├── ...
│   └── The Masterful Cat Is Depressed Again Today v04 (2022) (Digital) (t3dio).cbz
├── Tower of God
│   ├── Tower of God S03 001.cbz
│   ├── ...
│   └── Tower of God S03 133 .cbz
└── Watashitachi no Shiawase na Jikan
    └── Watashitachi No Shiawase Na Jikan.cbz
```

**Expected behavior**
Library scan should be able to complete.

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Version: both latest v0.7.1.4 and nightly v0.7.1.44

**Logs after a scan:**
```
[Kavita] [2023-05-01 00:45:06.500 +03:00  125] [Information] API.Services.TaskScheduler Enqueuing library scan for: 1
[Kavita] [2023-05-01 00:45:06.502 +03:00  38] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories
[Kavita] [2023-05-01 00:45:06.502 +03:00  38] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
[Kavita] [2023-05-01 00:45:06.504 +03:00  120] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Manga
[Kavita] [2023-05-01 00:45:06.659 +03:00  120] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on Tower of God
[Kavita] [2023-05-01 00:45:06.660 +03:00  120] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-05-01 00:45:06.660 +03:00  120] [Error] API.Services.Tasks.Scanner.ProcessSeries There was an exception finding existing series for Tower of God with Localized name of  for library 1. This indicates you have duplicate series with same name or localized name in the library. Correct this and rescan
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 102
[Kavita] [2023-05-01 00:45:06.661 +03:00  120] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on Goodnight Punpun
[Kavita] [2023-05-01 00:45:06.661 +03:00  120] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-05-01 00:45:06.662 +03:00  120] [Error] API.Services.Tasks.Scanner.ProcessSeries There was an exception finding existing series for Goodnight Punpun with Localized name of  for library 1. This indicates you have duplicate series with same name or localized name in the library. Correct this and rescan
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 102
[Kavita] [2023-05-01 00:45:06.662 +03:00  120] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on Loving Yamada at Lv999!
[Kavita] [2023-05-01 00:45:06.663 +03:00  120] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-05-01 00:45:06.663 +03:00  120] [Error] API.Services.Tasks.Scanner.ProcessSeries There was an exception finding existing series for Loving Yamada at Lv999! with Localized name of  for library 1. This indicates you have duplicate series with same name or localized name in the library. Correct this and rescan
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 102
[Kavita] [2023-05-01 00:45:06.663 +03:00  120] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on The Masterful Cat Is Depressed Again Today
[Kavita] [2023-05-01 00:45:06.664 +03:00  120] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-05-01 00:45:06.664 +03:00  120] [Error] API.Services.Tasks.Scanner.ProcessSeries There was an exception finding existing series for The Masterful Cat Is Depressed Again Today with Localized name of  for library 1. This indicates you have duplicate series with same name or localized name in the library. Correct this and rescan
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 102
[Kavita] [2023-05-01 00:45:06.665 +03:00  120] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on Watashitachi no Shiawase na Jikan
[Kavita] [2023-05-01 00:45:06.665 +03:00  120] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-05-01 00:45:06.666 +03:00  120] [Error] API.Services.Tasks.Scanner.ProcessSeries There was an exception finding existing series for Watashitachi no Shiawase na Jikan with Localized name of  for library 1. This indicates you have duplicate series with same name or localized name in the library. Correct this and rescan
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1272(Closure , QueryContext , DbDataReader , ResultContext , SplitQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleOrDefaultAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 102
[Kavita] [2023-05-01 00:45:06.666 +03:00  120] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 152 milliseconds. Updating database
[Kavita] [2023-05-01 00:45:06.726 +03:00  120] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 182 files and 10 series in 223 milliseconds for Manga
[Kavita] [2023-05-01 00:45:06.729 +03:00  120] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1453(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1453(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1453(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1453(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-05-01 00:45:06.729 +03:00  120] [Fatal] API.Services.Tasks.ScannerService [ScannerService] There was an issue deleting series for cleanup. Please check logs and rescan
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at lambda_method1453(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method1453(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at API.Data.Repositories.SeriesRepository.RemoveSeriesNotInList(IList`1 seenSeries, Int32 libraryId) in /home/runner/work/Kavita/Kavita/API/Data/Repositories/SeriesRepository.cs:line 1341
   at API.Services.Tasks.ScannerService.ScanLibrary(Int32 libraryId, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/ScannerService.cs:line 561
```

**Comment by majora2007** [comment]
Closing as this is from the linked issue.
