### ISSUE TITLE
String '0000-12-31 21:00:00' was not recognized as a valid DateTime error for MangaFile.CreatedUtc/Series.LastChapterAddedUtc

### ISSUE THREAD

**Issue by enchained** [Kareadita/Kavita#1949]
**Describe the bug**
I updated today from ~0.5.2.5 to the latest v0.7.1.4 (and then nightly v0.7.1.44). I've got some bugs ([scan errors wrongly reporting duplicates](https://github.com/Kareadita/Kavita/issues/1948)), so I tried to check version to report, and got an error, then tried to delete a library to start from scratch, and got similar error. Everything was working fine back on 0.5.2.5.

**To Reproduce 1**
1. Open Settings
2. See red error toast "An error occurred while reading a database value for property 'MangaFile.CreatedUtc'. See the inner exception for more information."

**To Reproduce 2**
1. Open Settings, try to delete a library.
2. See red error toast "An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information."

**Expected behavior**
Error should not be happening, version should be visible in settings even if there's some database issue with metadata, same with library deletion.

```
[Kavita] [2023-04-30 23:36:22.349 +03:00  82] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.InvalidOperationException: An error occurred while reading a database value for property 'MangaFile.CreatedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteDataReader.GetDateTime(Int32 ordinal)
   at lambda_method1025(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   --- End of inner exception stack trace ---
   at lambda_method1025(Closure, QueryContext, DbDataReader, ResultContext, SingleQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.DistinctByIterator[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at API.Services.Tasks.StatsService.AllFormats() in /home/runner/work/Kavita/Kavita/API/Services/Tasks/StatsService.cs:line 296
   at API.Services.Tasks.StatsService.GetServerInfo() in /home/runner/work/Kavita/Kavita/API/Services/Tasks/StatsService.cs:line 116
   at API.Controllers.ServerController.GetVersion() in /home/runner/work/Kavita/Kavita/API/Controllers/ServerController.cs:line 130
   at lambda_method816(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at API.Startup.<>c.<<Configure>b__4_5>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 360
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 51
```

```
[Kavita] [2023-05-01 00:00:43.541 +03:00  64] [Information] API.Controllers.LibraryController Library 1 is being deleted by enchained
[Kavita] [2023-05-01 00:00:43.550 +03:00  64] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteDataReader.GetDateTime(Int32 ordinal)
   at lambda_method3098(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   --- End of inner exception stack trace ---
   at lambda_method3098(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteDataReader.GetDateTime(Int32 ordinal)
   at lambda_method3098(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   --- End of inner exception stack trace ---
   at lambda_method3098(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-05-01 00:00:43.551 +03:00  64] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at Microsoft.Data.Sqlite.SqliteDataReader.GetDateTime(Int32 ordinal)
   at lambda_method3098(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   --- End of inner exception stack trace ---
   at lambda_method3098(Closure, QueryContext, DbDataReader, ResultContext, SplitQueryResultCoordinator)
   at Microsoft.EntityFrameworkCore.Query.Internal.SplitQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at API.Data.Repositories.SeriesRepository.GetSeriesForLibraryIdAsync(Int32 libraryId, SeriesIncludes includes) in /home/runner/work/Kavita/Kavita/API/Data/Repositories/SeriesRepository.cs:line 197
   at API.Controllers.LibraryController.DeleteLibrary(Int32 libraryId) in /home/runner/work/Kavita/Kavita/API/Controllers/LibraryController.cs:line 271
   at lambda_method3093(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at API.Startup.<>c.<<Configure>b__4_5>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 360
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 51
```

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Chrome
 - Version: both latest v0.7.1.4 and nightly v0.7.1.44

**Comment by majora2007** [comment]
You can't make a jump that big and one go. See the wiki where we say that you need to go two versions at a time. This is because after so many updates I remove migrations as they are expensive to run every startup.

Please roll back and update two at a time.

**Comment by enchained** [comment]
Thanks. Looks like I misinterpreted 0.5 > 0.7 as two versions, should have read more carefully.

I rolled back to 0.5.2 and incrementally updated by 1 minor version tag just in case. DateTime error reappeared on 0.6.1>0.7.0 update and stayed on 0.7.1 and 0.7.1.4.

Container startup logs:
```
[Kavita] [2023-05-01 06:48:29.678 +03:00  1] [Fatal] API.Program Running MigrateSeriesRelationsExport migration - Please be patient, this may take some time. This is not an error
[Kavita] [2023-05-01 06:48:29.706 +03:00  1] [Fatal] API.Program Running MigrateSeriesRelationsExport migration - complete. Nothing to do
[Kavita] [2023-05-01 06:48:30.219 +03:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2023-05-01 06:48:30.297 +03:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2023-05-01 06:48:30.383 +03:00  1] [Information] API.Services.Tasks.Scanner.LibraryWatcher [LibraryWatcher] Starting file watchers for 3 library folders
[Kavita] [2023-05-01 06:48:30.386 +03:00  1] [Information] API.Services.Tasks.Scanner.LibraryWatcher [LibraryWatcher] Watching 3 folders
[Kavita] [2023-05-01 06:48:30.451 +03:00  16] [Information] API.Program Running Migrations
[Kavita] [2023-05-01 06:48:30.481 +03:00  16] [Fatal] API.Program Running MigrateNormalizedEverything migration. Please be patient, this may take some time depending on the size of your library. Do not abort, this can break your Database
[Kavita] [2023-05-01 06:48:30.481 +03:00  16] [Information] API.Program Updating Normalization on Series...
[Kavita] [2023-05-01 06:48:30.504 +03:00  16] [Error] Microsoft.EntityFrameworkCore.Query An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetDateTime(Int32 ordinal)
   at lambda_method490(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method490(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetDateTime(Int32 ordinal)
   at lambda_method490(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method490(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
[Kavita] [2023-05-01 06:48:30.505 +03:00  1] [Fatal] API.Program An error occurred during migration
System.InvalidOperationException: An error occurred while reading a database value for property 'Series.LastChapterAddedUtc'. See the inner exception for more information.
 ---> System.FormatException: String '0000-12-31 21:00:00' was not recognized as a valid DateTime.
   at System.DateTime.Parse(String s, IFormatProvider provider)
   at Microsoft.Data.Sqlite.SqliteValueReader.GetDateTime(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetDateTime(Int32 ordinal)
   at lambda_method490(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   --- End of inner exception stack trace ---
   at lambda_method490(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at API.Data.MigrateNormalizedEverything.Migrate(IUnitOfWork unitOfWork, DataContext dataContext, ILogger`1 logger) in /home/runner/work/Kavita/Kavita/API/Data/MigrateNormalizedEverything.cs:line 26
   at API.Startup.<>c__DisplayClass4_0.<<Configure>b__0>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 224
--- End of stack trace from previous location ---
   at API.Startup.Configure(IApplicationBuilder app, IBackgroundJobClient backgroundJobs, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime, IServiceProvider serviceProvider, ICacheService cacheService, IDirectoryService directoryService, IUnitOfWork unitOfWork, IBackupService backupService, IImageService imageService) in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 208
Kavita - v0.7.1.4
```

**Comment by majora2007** [comment]
Thanks for updating correctly, yes this project does not follow semver. So the issue you're facing came from v0.7.1 where some systems didn't properly apply the column update using the built-in DB Function. 

0000-12-31 21:00:00 should be an acceptable date actually. In #1811, we fixed it my manually by reapplying what's in the migration script: https://github.com/Kareadita/Kavita/blob/develop/API/Data/MigrateToUtcDates.cs

You can correct it manually (see migration for more manual steps):
`UPDATE MangaFile SET CreatedUtc = '0000-12-31 21:00:00' WHERE CreatedUtc = '0000-12-31 23:00:00'`

Worst case, you can remove the Series having this issue and re-add them via a scan.

**Comment by enchained** [comment]
Looks like `UPDATE MangaFile SET CreatedUtc = '0000-12-31 21:00:00' WHERE CreatedUtc = '0000-12-31 23:00:00'` does not affect any rows in my case - it's already `0000-12-31 21:00:00`.

From the logs above, it looks like `MangaFile.CreatedUtc` and `Series.LastChapterAddedUtc` both have issues with `String '0000-12-31 21:00:00' was not recognized as a valid DateTime`.

My container is in the UTC+3 timezone, and my database has those non-202X dates in it:
```
MangaFile.Created, MangaFile.LastFileAnalysis, Series.LastChapterAdded, Series.LastFolderScanned: 
0001-01-01 00:00:00
MangaFile.CreatedUtc, MangaFile.LastFileAnalysisUtc, Series.LastChapterAddedUtc, Series.LastFolderScannedUtc: 
0000-12-31 21:00:00
```
What should I change `0000-12-31 21:00:00` to?

**Comment by majora2007** [comment]
Are you passing timezone into the docker container?

**Comment by enchained** [comment]
> Are you passing timezone into the docker container?

Yes, my container has TZ env var. I don't see anything about it in the image docs, so I'm not sure how it got there. Should I remove it, or change it to UTC?

**Comment by majora2007** [comment]
No. I'm just not sure why this issue is affecting you. Can you just remove the Series from Kavita and re-scan to get them added back? This looks like the migration didn't take correctly and should sort itself once those rows are removed.
