### ISSUE TITLE
Error after update (Docker)

### ISSUE THREAD

**Issue by Tellsanguis** [Kareadita/Kavita#1974]
**Describe the bug**

After updating, Kavita no longer launches.

**Server:**

- Ubuntu 22.04.2 LTS arm64
- Kavita version: 0.7.2.0

**Stack trace:**

```
[Kavita] [2023-05-10 08:02:22.509 +02:00  1] [Fatal]  Host terminated unexpectedly

Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.

 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'UNIQUE constraint failed: Genre.NormalizedTitle'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)

   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)

   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)

   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

   --- End of inner exception stack trace ---

   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.Execute(IRelationalConnection connection)

   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)

   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChanges(IList`1 entries)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IList`1 entriesToSave)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(StateManager stateManager, Boolean acceptAllChangesOnSuccess)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.<>c.<SaveChanges>b__107_0(DbContext _, ValueTuple`2 t)

   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)

   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)

   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)

   at API.Data.DataContext.SaveChanges(Boolean acceptAllChangesOnSuccess) in /home/runner/work/Kavita/Kavita/API/Data/DataContext.cs:line 160

   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges()

   at API.Data.DataContext.SaveChanges() in /home/runner/work/Kavita/Kavita/API/Data/DataContext.cs:line 153

   at API.Startup.Configure(IApplicationBuilder app, IBackgroundJobClient backgroundJobs, IWebHostEnvironment env, IHostApplicationLifetime applicationLifetime, IServiceProvider serviceProvider, ICacheService cacheService, IDirectoryService directoryService, IUnitOfWork unitOfWork, IBackupService backupService, IImageService imageService) in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 307

   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)

   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

   at System.Reflection.RuntimeMethodInfo.InvokeWithManyArguments(RuntimeMethodInfo mi, Int32 argCount, Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)

   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)

   at API.Program.Main(String[] args) in /home/runner/work/Kavita/Kavita/API/Program.cs:line 117

[Kavita] [2023-05-10 08:02:34.782 +02:00  1] [Fatal] API.Program Running MigrateSeriesRelationsExport migration - Please be patient, this may take some time. This is not an error

[Kavita] [2023-05-10 08:02:34.930 +02:00  1] [Fatal] API.Program Running MigrateSeriesRelationsExport migration - complete. Nothing to do
```

**Comment by majora2007** [comment]
What version did you update from?

**Comment by Tellsanguis** [comment]
I was on the version 0.7.1

**Comment by chalgoon9** [comment]
same error after update.

**Comment by majora2007** [comment]
I'm not sure how to help honestly. This is saying the Genre normalized title (so Action -> action) is not unique. This should never be the case and might have occurred from a bug in older versions. So the Migration is failing to run, but to my knowledge Kavita should function still, can you confirm?

**Comment by chalgoon9** [comment]
> 

No, It is impossible to run kavita because it fails during the installation process. I downgraded to 0.7.1 and it works again. I found this issue has been there in the past as well. but I found out that it was solved by upgrading the version. It's slightly different from the log above, so I'm attaching mine as well. 

**Kavita | fail: Microsoft.EntityFrameworkCore.Query[10100]**

Kavita | An exception occurred while iterating over the results of a query for context type 'API.Data.DataContext'.

Kavita | System.InvalidOperationException: Sequence contains no elements.

Kavita | at lambda_method266(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )

Kavita | at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

Kavita | System.InvalidOperationException: Sequence contains no elements.

Kavita | at lambda_method266(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )

Kavita | at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

Kavita | warn: Hangfire. AutomaticRetryAttribute[0]

**Kavita | Failed to process the job '3d94c906-84a4-48f6-806f-91bdad9c0fe3': an exception occurred. Retry attempt 1 of 10 will be performed in 00:00:23.**

Kavita | System.InvalidOperationException: Sequence contains no elements.

Kavita | at lambda_method266(Closure , QueryContext , DbDataReader , ResultContext , SingleQueryResultCoordinator )

Kavita | at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.AsyncEnumerator.MoveNextAsync()

Kavita | at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)

Kavita | at Microsoft.EntityFrameworkCore.Query.ShapedQueryCompilingExpressionVisitor.SingleAsync[TSource](IAsyncEnumerable`1 asyncEnumerable, CancellationToken cancellationToken)

Kavita | at API.Services.Tasks.StatsService.GetServerInfo() in D:\Kavita\source\Kavita\API\Services\Tasks\StatsService.cs:line 111

Kavita | at API.Services.Tasks.StatsService.SendData() in D:\Kavita\source\Kavita\API\Services\Tasks\StatsService.cs:line 63

Kavita | at API.Services.Tasks.StatsService.Send() in D:\Kavita\source\Kavita\API\Services\Tasks\StatsService.cs:line 54

Kavita | at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Comment by Tellsanguis** [comment]
It is impossible to run kavita as well. I downgraded to 0.7.1 too and it works again.

**Comment by majora2007** [comment]
You might need to restart unfortunately. The migration that last dealt with genres is from prior to v0.7.1, meaning that in v0.7.1 the migration might have partially ran and now you're essentially stuck on that version. 

These things shouldn't happen, as I explicitly save a copy of each old version from my prod instance and manually test the upgrade, but everyone's system is different. I can't change old migrations, they must run in order and you're getting stuck on the newer ones as the older ones didn't run correctly for you. So I'm afraid there isn't much I can do other than say, remove all genres or manually validate in the DB and clean up those duplicates.

**Comment by AverageMarcus** [comment]
This happened to me when upgrading to 0.6.0. It turns out it was an issue with two of the same genre that had an accented character in it and the Normalized title before the upgrade was different. Not sure how exactly it ended up in this state but manually removing one of the genres from the database was enough for me to get past this issue.

**Comment by majora2007** [comment]
I'm going to close the issue as there is nothing I can do to fix the issue in code. If you need help with a manual db fix, please reach out.
