### ISSUE TITLE
Refresh token fails to renew, logs out user while reading

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#2082]
**Describe the bug**
The refresh token API call is failing to complete while active sessions are in use. This causes the user to be logged out.

**To Reproduce**
1. Be reading
2. Get logged out 

**Expected behavior**
If I understand the previous commits properly, the refresh token tries to renew every 10 minutes. That way the overall lifetime of the token keeps getting extended 2 days into the future. If the token fails to refresh, it should still be valid for some time yet. Don't expire the token right at renewal failure. 

**Desktop (please complete the following information):**
 - OS: Docker
 - Browser: Firefox
 - Version: 0.7.3.7

**Additional context**

```
[Kavita] [2023-06-18 02:20:37.172 -04:00  6] [Error] API.Services.TokenService Failed to validate refresh token
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See http://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at API.Data.UnitOfWork.CommitAsync() in /home/runner/work/Kavita/Kavita/API/Data/UnitOfWork.cs:line 84
   at API.Services.TokenService.ValidateRefreshToken(TokenRequestDto request) in /home/runner/work/Kavita/Kavita/API/Services/TokenService.cs:line 109
[Kavita] [2023-06-18 02:23:37.523 -04:00  44] [Information] API.Controllers.AccountController diesel logged in at "2023-06-18T02:23:37.3782990-04:00"
```

**Comment by majora2007** [comment]
This will be released in v0.7.4.
