### ISSUE TITLE
CacheSize is using Port configuration option

### ISSUE THREAD

**Issue by rboylesDev** [Kareadita/Kavita#2126]
When using a custom and large port number, exceptions around memory cache are thrown on 0.7.4

**To Reproduce**
1. Go and set the port to something large, like 28500.
2. Launch Kavita
3. Note site loads, but throws errors.

**Expected behavior**
No errors to be thrown and Cache setting respected.

**Details**

In this method for getting Cache Size, it references the Port setting. https://github.com/Kareadita/Kavita/blob/1ed8889d0837a22a9ba0ce69d4f8ac0f655db937/Kavita.Common/Configuration.cs#L304-L315

Why was I seeing a crash?

In this section of code, it converts the number to bytes and sets the memory cache size limit. https://github.com/Kareadita/Kavita/blob/1ed8889d0837a22a9ba0ce69d4f8ac0f655db937/API/Extensions/ApplicationServiceExtensions.cs#L86

Well, for 50 MB, it's 50*1024*1024 or 52,428,800.
When using a large port number, like 28500, it is trying to use the number 29,884,416,000 and since int has a max size of 2,147,483,647. This was causing it to overflow and generate a negative int.

Also, this could have gone unnoticed, but when the calculation is occurring, you are allowing the language to just assume types instead of trying to force the CacheSize setting to long, which MemoryCache would have supported... Albeit, then you'd have people wondering why Kavita is eating memory.

**Error Log message**

[Kavita] [2023-07-12 12:04:39.739 -05:00  50] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.ArgumentOutOfRangeException: value must be non-negative. (Parameter 'value')
Actual value was -633339904.
   at Microsoft.Extensions.Caching.Memory.MemoryCacheOptions.set_SizeLimit(Nullable`1 value)
   at API.Extensions.ApplicationServiceExtensions.<>c.<AddApplicationServices>b__0_2(MemoryCacheOptions options) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Extensions\ApplicationServiceExtensions.cs:line 86
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1.Configure(String name, TOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1.Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1.get_Value()
   at Microsoft.Extensions.Caching.Memory.MemoryCache..ctor(IOptions`1 optionsAccessor, ILoggerFactory loggerFactory)
   at InvokeStub_MemoryCache..ctor(Object, Object, IntPtr*)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type, Type requiredBy, Boolean isDefaultParameterRequired)
   at lambda_method1073(Closure, IServiceProvider, Object[])
   at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass6_0.<CreateControllerFactory>g__CreateController|0(ControllerContext controllerContext)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at API.Startup.<>c.<<Configure>b__4_5>d.MoveNext() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 368
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\ExceptionMiddleware.cs:line 51
```

**Comment by majora2007** [comment]
Thanks, I just saw this slip through. I've corrected to use the proper Key.
