### ISSUE TITLE
Cannot open epub file. Getting error "Incorrect EPUB 2 NCX: content source "OEBPS/part0000.xhtml" not found in EPUB manifest"

### ISSUE THREAD

**Issue by mahenkpatel** [Kareadita/Kavita#2242]
When opening an. epub file, the operation fails with error "Incorrect EPUB 2 NCX: content source "OEBPS/part0000.xhtml" not found in EPUB manifest" on the screen. The epub is fine because I can open it on my Macbook without any issues with Apple's Books app

**Logs**

The logs show below output when I try to open the book

`[Kavita] [2023-08-28 11:44:16.529 +05:30  66] [Error] API.Middleware.ExceptionMiddleware There was an exception
VersOne.Epub.Epub2NcxException: Incorrect EPUB 2 NCX: content source "OEBPS/part0000.xhtml" not found in EPUB manifest.
   at VersOne.Epub.Internal.NavigationReader.GetNavigationItems(EpubSchema epubSchema, EpubContentRef epubContentRef, List`1 navigationPoints)
   at VersOne.Epub.Internal.NavigationReader.GetNavigationItems(EpubSchema epubSchema, EpubContentRef epubContentRef, Epub2Ncx epub2Ncx)
   at VersOne.Epub.Internal.NavigationReader.GetNavigationItems(EpubSchema epubSchema, EpubContentRef epubContentRef)
   at VersOne.Epub.EpubBookRef.<GetNavigationAsync>b__32_0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at VersOne.Epub.EpubBookRef.GetNavigationAsync()
   at API.Services.BookService.GenerateTableOfContents(Chapter chapter) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 989
   at API.Controllers.BookController.GetBookChapters(Int32 chapterId) in /home/runner/work/Kavita/Kavita/API/Controllers/BookController.cs:line 131
   at lambda_method1879(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at API.Startup.<>c.<<Configure>b__4_5>d.MoveNext() in /home/runner/work/Kavita/Kavita/API/Startup.cs:line 371
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in /home/runner/work/Kavita/Kavita/API/Middleware/ExceptionMiddleware.cs:line 51`

**Setup Details**
 - Docker version 24.0.5
 - Firefox 116.0.3
 - Kavita Version 0.7.7.0

**Comment by DieselTech** [comment]
The epub isn't fine, apples reader is just ignoring the errors and correcting the bad data on the fly. You can try fixing the file in Calibre or Sigil. In Calibre you can do a epub to epub conversion and it will try to fix any problems it finds.
