### ISSUE TITLE
Exception XML version 1.1 invalid in epub

### ISSUE THREAD

**Issue by maurosch** [Kareadita/Kavita#2287]
**Describe the bug**
Added an especific epub, and it was not appearing in kavita when scanning. Checked the logs and it showed:

`[Kavita] [2023-09-20 04:20:47.042 +00:00  137] [Warning] API.Services.BookService [BookService] There was an exception when opening epub book: /data/<BOOK>.epub
System.Xml.XmlException: Version number '1.1' is invalid. Line 1, position 16.
   at VersOne.Epub.Utils.TaskExtensionMethods.ExecuteAndUnwrapAggregateException[T](Task`1 task)
   at VersOne.Epub.Internal.BookRefReader.OpenBook(String filePath)
   at VersOne.Epub.EpubReader.OpenBook(String filePath, EpubReaderOptions epubReaderOptions)
   at API.Services.BookService.ParseInfo(String filePath) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 783`

**To Reproduce**
Add epub with 1.1 XML inside

**Desktop (please complete the following information):**
kizaing/kavita Docker image

**Comment by DieselTech** [comment]
There isn't a version 1.1 of the epub spec. I would attempt to do a epub to epub conversion of your file in calibre in order to bring it up to a complying standard.

**Comment by majora2007** [comment]
This is a bad epub file. Calibre or Sigil can fix
