### ISSUE TITLE
Opt-Out not working

### ISSUE THREAD

**Issue by duracell** [Kareadita/Kavita#2384]
Besides the legal side of opt-out of such stats (especially in the eu with the gdpr laws), the opt-out page delivers a 404:
```
Flurl.Http.FlurlHttpException: Call failed with status code 404 (Not Found): POST https://stats.kavitareader.com/api/v2/stats/opt-out?installId=xxxxxxxx
   at Flurl.Http.FlurlRequest.HandleExceptionAsync(FlurlCall call, Exception ex, CancellationToken token)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
   at API.Services.Tasks.StatsService.SendCancellation() in /home/runner/work/Kavita/Kavita/API/Services/Tasks/StatsService.cs:line 195
```
Same in Webbrowser.

**Comment by majora2007** [comment]
Interesting, the api might have been moved when I was doing some cleanup on the stats project. I'll take a look and get the opt-out fixed up.
