### ISSUE TITLE
Promoted collections do not show for users

### ISSUE THREAD

**Issue by skepickle** [Kareadita/Kavita#2720]
### What happened?

A non-admin user was created with Age Rating Restriction set to the highest (X18+) and "Include Unknowns" enabled. Admin then created a collection with some series in it. From the collection's Edit->General dialog box, the "Promote" toggle was enabled and the "Save" button was pressed. The non-admin user still does not see any collections listed.

### What did you expect?

I expected that the non-admin user would be able to see a collection that was promoted, which had content in it that the user is allowed to see.

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
Feb 15 16:15:40 sensenet Kavita[926895]: [Kavita] [2024-02-15 16:15:40.082 -05:00  124] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/series/series-by-collection?collectionId=2&pageNumber=0&pageSize=200 responded 200 in 7.0592 ms
Feb 15 16:15:43 sensenet Kavita[926895]: [Kavita] [2024-02-15 16:15:43.703 -05:00  44] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/collection/update-series responded 200 in 5.1846 ms
Feb 15 16:15:43 sensenet Kavita[926895]: [Kavita] [2024-02-15 16:15:43.703 -05:00  124] [Error] Microsoft.EntityFrameworkCore.Update An exception occurred in the database while saving changes for context type 'API.Data.DataContext'.
Feb 15 16:15:43 sensenet Kavita[926895]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
Feb 15 16:15:43 sensenet Kavita[926895]:  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Feb 15 16:15:43 sensenet Kavita[926895]:    at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]: --- End of stack trace from previous location ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    --- End of inner exception stack trace ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
Feb 15 16:15:43 sensenet Kavita[926895]:  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Feb 15 16:15:43 sensenet Kavita[926895]:    at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]: --- End of stack trace from previous location ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    --- End of inner exception stack trace ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]: [Kavita] [2024-02-15 16:15:43.711 -05:00  124] [Error] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/collection/update responded 500 in 12.8231 ms
Feb 15 16:15:43 sensenet Kavita[926895]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
Feb 15 16:15:43 sensenet Kavita[926895]:  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Feb 15 16:15:43 sensenet Kavita[926895]:    at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]: --- End of stack trace from previous location ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    --- End of inner exception stack trace ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Data.UnitOfWork.CommitAsync() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Data\UnitOfWork.cs:line 92
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Services.CollectionTagService.UpdateTag(CollectionTagDto dto) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\CollectionTagService.cs:line 95
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Controllers.CollectionController.UpdateTag(CollectionTagDto updatedTag) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Controllers\CollectionController.cs:line 95
Feb 15 16:15:43 sensenet Kavita[926895]:    at lambda_method5136(Closure, Object)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 15 16:15:43 sensenet Kavita[926895]: --- End of stack trace from previous location ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Startup.<>c__DisplayClass4_0.<<Configure>b__5>d.MoveNext() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 379
Feb 15 16:15:43 sensenet Kavita[926895]: --- End of stack trace from previous location ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
Feb 15 16:15:43 sensenet Kavita[926895]: [Kavita] [2024-02-15 16:15:43.721 -05:00  124] [Error] API.Middleware.ExceptionMiddleware There was an exception
Feb 15 16:15:43 sensenet Kavita[926895]: Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
Feb 15 16:15:43 sensenet Kavita[926895]:  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Feb 15 16:15:43 sensenet Kavita[926895]:    at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]: --- End of stack trace from previous location ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    --- End of inner exception stack trace ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Data.UnitOfWork.CommitAsync() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Data\UnitOfWork.cs:line 92
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Services.CollectionTagService.UpdateTag(CollectionTagDto dto) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\CollectionTagService.cs:line 95
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Controllers.CollectionController.UpdateTag(CollectionTagDto updatedTag) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Controllers\CollectionController.cs:line 95
Feb 15 16:15:43 sensenet Kavita[926895]:    at lambda_method5136(Closure, Object)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfActionResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
Feb 15 16:15:43 sensenet Kavita[926895]: --- End of stack trace from previous location ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Startup.<>c__DisplayClass4_0.<<Configure>b__5>d.MoveNext() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 379
Feb 15 16:15:43 sensenet Kavita[926895]: --- End of stack trace from previous location ---
Feb 15 16:15:43 sensenet Kavita[926895]:    at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
Feb 15 16:15:43 sensenet Kavita[926895]:    at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\SecurityMiddleware.cs:line 25
Feb 15 16:15:43 sensenet Kavita[926895]:    at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\ExceptionMiddleware.cs:line 18
```

### Additional Notes

I've tried restarting the Kavita service, but neither the behavior not the log output changes when I attempt to promote after the restart.

**Comment by skepickle** [comment]
Nevermind... I set the journal_mode in the DB to WAL, and now everything works as expected. I'm dumb.

**Comment by DieselTech** [comment]
No worries, so just to confirm then that it's working as intended now that you enabled WAL mode?

**Comment by skepickle** [comment]
Yes, it's working now. I promoted a collection when logged in as an admin user, then logged in as a non-admin user and I could see the collection.

**Comment by majora2007** [comment]
Awesome. WAL mode by default is something I'm looking into as well.
