### ISSUE TITLE
Scrobbling not working properly

### ISSUE THREAD

**Issue by Roshri** [Kareadita/Kavita#2758]
### What happened?

I'm getting lots of scrobble issues.

Most common issue is adding a series to Want to Read is not scrobbling up. This only happens to my user, every other user on my server can scrobble want to read normally. These series have the corresponding Anilist weblink

![image](https://github.com/Kareadita/Kavita/assets/29184137/c2a29908-ed1e-4004-9600-d3b63ba07ba5)

When this mismatch happens, reading progress on one of these series won't scrobble up since it's already errored out.

Tried doing the whole Force Refresh -> Clear Media Issues and it did scrobble up the reading progress for a few series, but never the "Want to Read" status.

This has been happening for a while already and today I noticed something new.
A series showed the scrobble error, but did update on anilist, although it didn't show on my "Activity" page on AL, when searching for the series, it had the correct reading progress

![image](https://github.com/Kareadita/Kavita/assets/29184137/9c270d97-0d40-49d4-bfe7-2ff1e6979402)

![image](https://github.com/Kareadita/Kavita/assets/29184137/05bc0683-cf94-45c3-a9fc-e9269fe1cd47)

### What did you expect?

When a scrobble fails for whatever reason, if I clear the media issues, add weblink and force refresh, I need the "Want to Read" status to be able to add a series to "Plan to Read" on AL

### Kavita Version Number - Don't see your version number listed? Then your install is out of date. Please update and see if your issue still persists.

0.7.14 - Stable

### What operating system is Kavita being hosted from?

Windows

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the UI, what browsers are you seeing the problem on?

Firefox

**Comment by Roshri** [comment]
Coming from discord

I don't know if it's related but last night, one series that refused to scrobble, finally did it.
Kuso Onna ni Sachi Are never scrobbled on it's own before.

![image](https://github.com/user-attachments/assets/aa9aecda-754f-437d-a6c4-5e69e3328902)

I'm trying to locate another [issue](https://github.com/Kareadita/Kavita/issues/2885) to reference but essentially what happened to this series before was this:

- It suffered from duplication of chapters when upgrading to v0.8 (i.e. I had chapter 001 AND chapter 1)
- I manually set it to Reading on AL

After fixing the first issue with a Plex Dance, it scrobbled

**Comment by Roshri** [comment]
Adding more context from discord, I have tons of pending Scrobbling events that refuse to scrobble

```
[Kavita] [2025-03-10 13:00:07.527 -03:00  81] [Information] API.Services.Plus.ScrobblingService Scrobble Processing Details:
  Read Events: 88
  Want to Read Events: 955
  Rating Events: 0
  Users to Scrobble: 6
  Total Events to Process: 1043
[Kavita] [2025-03-10 13:00:07.619 -03:00  81] [Debug] API.Services.Plus.ScrobblingService Processing Reading Events: 0 / 1043
[Kavita] [2025-03-10 13:00:07.619 -03:00  81] [Debug] API.Services.Plus.ScrobblingService Processing Reading Events: 1 / 1043
[Kavita] [2025-03-10 13:00:07.761 -03:00  81] [Debug] API.Services.Plus.ScrobblingService Processing Reading Events: 0 / 1043
[Kavita] [2025-03-10 13:00:07.890 -03:00  81] [Information] API.Services.Plus.ScrobblingService Scrobbling Events is complete
```

**Comment by majora2007** [comment]
So just an update before I delve into this. 
1. In the v0.8.6 nightly releases, I added code to fix a ton of pending and essentially stuck events. There were a few errors in the code and some events would never get cleaned up.
2. As stated above, I also did a bulk removal of some of these. For me, I was also stuck with no progress and now scrobbling is working reliable. 


That being said, the scrobbling token error seems dubious to me and likely some fallout bug is occurring which is masking the real issue. I still do have a major overhaul to the code planned in #3685. I'll take a look and see what improvements I can make before the rework (which may or may not be in this v0.8.6 release).

**Comment by Roshri** [comment]
I'm adding new behavior I've found out in the last couple of days.

- Series that previously couldn't scrobble or  showed the Anilist token expired error, now appear as processed, but that was never reflected upstream to AL

![Image](https://github.com/user-attachments/assets/6e5fd8b1-2c7f-4863-9862-0fc3bcf1d1a2)

![Image](https://github.com/user-attachments/assets/d46e6b47-6f0c-462f-a31e-4f4f355b77ab)

- Additionally, other series that showed the same error, are no longer present on the table and haven't been scrobbled up to AL

![Image](https://github.com/user-attachments/assets/cd403c2f-cc86-49ac-88bd-6c13b98a279b)

![Image](https://github.com/user-attachments/assets/cc4dc566-13d6-49da-9f73-89655883400d)

![Image](https://github.com/user-attachments/assets/6a49360e-bdcb-4990-9051-f9981562b67f)

**Comment by majora2007** [comment]
I'll add some stuff I found this morning where multiple read events were not processed but the latest was. 

I'm at the point where I think just doing the rewrite in this release window seems to be the best choice.

**Comment by majora2007** [comment]
We did some major debugging and refactoring recently in #3863 which just went to the nightly branch. Can you monitor over the next week and report back?

**Comment by Roshri** [comment]
So far, the few new reads I got, were succesfuly scrobbled.
The old ones that had the Access Token error seem to have triggered the new notification mentioned in #3844
But after renewing the token, the old ones wouldn't scrobble no matter what I did, so I decided to wait a couple of days, but still nothing.
For now I manually matched these and will be monitoring new scrobble events to see what happens 

![Image](https://github.com/user-attachments/assets/e20953a7-98e3-4b36-907c-607113e6a5fd)

**Comment by Roshri** [comment]
It hit again last night 

```
[Kavita] [2025-06-22 20:00:04.907 -03:00  118] [Information] API.Services.Plus.ScrobblingService Scrobble Processing Details:
  Read Events: 2
  Want to Read Events: 0
  Rating Events: 0
  Users to Scrobble: 1
  Total Events to Process: 2
[Kavita] [2025-06-22 20:00:04.955 -03:00  118] [Debug] API.Services.Plus.ScrobblingService Processing Scrobble Events: 0 / 2
[Kavita] [2025-06-22 20:00:06.818 -03:00  118] [Debug] API.Services.Plus.ScrobblingService K+ API Scrobble response for series Blue Box: Successful true, ErrorMessage null, ExtraInformation: null, RateLeft: 79
[Kavita] [2025-06-22 20:00:07.818 -03:00  110] [Debug] API.Services.Plus.ScrobblingService Processing Scrobble Events: 1 / 2
[Kavita] [2025-06-22 20:00:08.030 -03:00  110] [Debug] API.Services.Plus.ScrobblingService K+ API Scrobble response for series "Okaeri, Papa": Successful false, ErrorMessage Access token is invalid, ExtraInformation: Access token is invalid, RateLeft: 79
[Kavita] [2025-06-22 20:00:08.033 -03:00  110] [Fatal] API.Services.Plus.ScrobblingService Access Token for AppUserId: 1 needs to be regenerated/renewed to continue scrobbling
Kavita.Common.KavitaException: Access token is invalid
   at API.Services.Plus.ScrobblingService.PostScrobbleUpdate(ScrobbleDto data, String license, ScrobbleEvent evt) in /home/runner/work/Kavita/Kavita/API/Services/Plus/ScrobblingService.cs:line 1146
   at API.Services.Plus.ScrobblingService.ProcessEvents(IEnumerable`1 events, ScrobbleSyncContext ctx, Func`2 createEvent) in /home/runner/work/Kavita/Kavita/API/Services/Plus/ScrobblingService.cs:line 1022
[Kavita] [2025-06-22 20:00:09.085 -03:00  118] [Debug] API.Services.Plus.ScrobblingService Saving Scrobbling Event Processing Progress
[Kavita] [2025-06-22 20:00:09.101 -03:00  118] [Information] API.Services.Plus.ScrobblingService Scrobbling Events is complete
```

**Comment by majora2007** [comment]
@Fesaa

**Comment by majora2007** [comment]
Okay we made some progress on this. It seems to be coming from a library we are using.
