### ISSUE TITLE
Again "There was an issue writing to the DB for Series XXXX" in 0.8.1.0

### ISSUE THREAD

**Issue by janaxhell** [Kareadita/Kavita#2971]
### What happened?

I had this problem in the past, but majora helped me sort it out on Discord, then it updated the 0.7.1 and apparently solved the issue, but now I'm on 0.8.1.0 and each monday morning I see tons of these errors and a lot of RAM used:

```
There was an issue writing to the DB for Series Skeeters

The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
```

Restarting the service doesn't help. 

### What did you expect?

No errors.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Other)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Other (List in "Additional Notes" box)

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
Most recent piece of log while scanning:

Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at API.Data.UnitOfWork.CommitAsync() in /home/runner/work/Kavita/Kavita/API/Data/UnitOfWork.cs:line 92
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 190
[Kavita] [2024-05-27 11:23:16.413 +02:00  274] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on Werewolf By Night: The Complete Collection, Forced: false
[Kavita] [2024-05-27 11:23:16.470 +02:00  274] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series Werewolf By Night: The Complete Collection
[Kavita] [2024-05-27 11:23:16.470 +02:00  274] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Updating 1 volumes on Werewolf By Night: The Complete Collection
[Kavita] [2024-05-27 11:23:16.470 +02:00  274] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing Werewolf By Night: The Complete Collection - Volume 2017
[Kavita] [2024-05-27 11:23:16.505 +02:00  274] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating Werewolf By Night: The Complete Collection FolderPath to /comics/Mylar/Marvel
[Kavita] [2024-05-27 11:23:16.505 +02:00  274] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating Werewolf By Night: The Complete Collection LowestFolderPath to /Marvel/Werewolf By Night The Complete Collection (2017)
```

### Additional Notes

I'm running image: jvmilazz0/kavita:latest on OMV6/Docker, I have a library of about 200k comics + 10k books.

**Comment by madscientista** [comment]
Having same issue

**Comment by DoctorD1501** [comment]
Also having the same issue (on Windows, no docker, 0.8.1.0). Also tried with a fresh install and still getting this, but after it scans in a bunch of comics - the problem did not happen right away (It managed to scan in about 30,050 books before this happened). Comic files are located on network attached storage mounted as a network drive via SMB, library type is Comicvine comics. There should not have been any underlying file changes to the files during the scan as comicrack was closed during the scan and mylar did not download anything during the scan (though even if it did, that should be handled somehow by triggering a rescan of the affected folders or something).

The comic book that gets complained about in the error then does not get added to the database on the scan and furthermore does not seem to add it back on subsequent scans. It thinks it was already added somehow? Or the folder was already successfully scanned?

**Comment by majora2007** [comment]
@DoctorD1501 That indicates that your OS is reporting changes in last write time since Kavita last scanned. If it reports that it's changed since Kavita last scanned, Kavita will dive further into the folder. 

Janaxhell's issue is different. If you need support, please create another issue or better join the discord and get some.

**Comment by DoctorD1501** [comment]
Perhaps my description of events was sort of confusing and made it seem like I was reporting a different error than the original one above. Happy to create a new issue if needed, but the error seems the same. I just wanted to add some flavor in how I got the same error in case that helped to track the issue down. I've got hundreds of errors like this one in the log. Here is one of them (and note that the comic shown in the stack trace below never added after it hits this error the first time Kavita sees it, even on subsequent scans, that was I think the point I was trying to make):

**Update: The missing series finally seemed to have scanned in, like a day later. Weird.**

```
[Kavita] [2024-06-04 19:31:41.160 -07:00  44] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on E.V.I.L. Heroes (2016), Forced: false
[Kavita] [2024-06-04 19:31:41.162 -07:00  44] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series E.V.I.L. Heroes (2016)
[Kavita] [2024-06-04 19:31:41.162 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Updating 1 volumes on E.V.I.L. Heroes (2016)
[Kavita] [2024-06-04 19:31:41.162 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Parsing E.V.I.L. Heroes (2016) - Volume 2016
[Kavita] [2024-06-04 19:31:41.162 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, E.V.I.L. Heroes (2016) - Vol 2016 Ch 1
[Kavita] [2024-06-04 19:31:41.280 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, E.V.I.L. Heroes (2016) - Vol 2016 Ch 2
[Kavita] [2024-06-04 19:31:41.363 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, E.V.I.L. Heroes (2016) - Vol 2016 Ch 3
[Kavita] [2024-06-04 19:31:41.438 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, E.V.I.L. Heroes (2016) - Vol 2016 Ch 4
[Kavita] [2024-06-04 19:31:41.491 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, E.V.I.L. Heroes (2016) - Vol 2016 Ch 5
[Kavita] [2024-06-04 19:31:41.529 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, E.V.I.L. Heroes (2016) - Vol 2016 Ch 6
[Kavita] [2024-06-04 19:31:42.609 -07:00  44] [Error] API.Services.Tasks.Scanner.ProcessSeries There was some issue when updating chapter's metadata
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at API.Data.UnitOfWork.CommitAsync() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Data\UnitOfWork.cs:line 92
   at API.Services.Tasks.Scanner.TagManagerService.GetPerson(String name, PersonRole role) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\TagManagerService.cs:line 163
   at API.Services.Tasks.Scanner.ProcessSeries.UpdatePeople(Chapter chapter, IList`1 people, PersonRole role) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.cs:line 929
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateChapterFromComicInfo(Chapter chapter, ComicInfo comicInfo, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.cs:line 853
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.cs:line 630
[Kavita] [2024-06-04 19:31:42.612 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating E.V.I.L. Heroes (2016) FolderPath to F:/Comics/Zenescope Entertainment
[Kavita] [2024-06-04 19:31:42.612 -07:00  44] [Debug] API.Services.Tasks.Scanner.ProcessSeries Updating E.V.I.L. Heroes (2016) LowestFolderPath to F:/Comics/Zenescope Entertainment/E.V.I.L. Heroes (2016)
[Kavita] [2024-06-04 19:31:43.920 -07:00  44] [Fatal] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an issue writing to the database for series E.V.I.L. Heroes (2016)
Microsoft.EntityFrameworkCore.DbUpdateConcurrencyException: The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ThrowAggregateUpdateConcurrencyExceptionAsync(RelationalDataReader reader, Int32 commandIndex, Int32 expectedRowsAffected, Int32 rowsAffected, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeResultSetWithRowsAffectedOnlyAsync(Int32 commandIndex, RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at API.Data.UnitOfWork.CommitAsync() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Data\UnitOfWork.cs:line 92
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Boolean forceUpdate) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ProcessSeries.cs:line 190
```

**Comment by janaxhell** [comment]
Small update: today, like every monday, I checked what Kavita was doing, and it was scanning library as usual, but this time for no apparent reason, without any red error (I'm writing in the afternoon, and errors were already there early in the morning all the previous times). The version is still 0.8.1.0, so I don't know why it suddenly works fine. 
Anyway I hope this issue gets sorted out, it disappeared the same random way it appeared. 
And who knows what will happen next monday.

**Comment by janaxhell** [comment]
With v0.8.2.0 no problem occurred.
The recurring weekly Library Scan task on 150,621 cbz files takes about 36 hours to complete.

**Comment by majora2007** [comment]
This issue isn't solved yet, but I do want to give you an update that I rewrote large parts of the scanner to bring more reliability and improve performance (not speed) for larger libraries like yours. 

The community and I have been testing this new scanner and tweaking for the past 3 weeks and have noticed a huge increase in reliability to completing scans without db issues. I have still seen some on my prod instance, so there is still more work to be done. 

The new scanner launches with v0.8.4.

**Comment by neulf** [comment]
I have a same question.

**Comment by XyberDAWG** [comment]
Mine was working before the latest release 0.8.4.0.

Now I seem to get about 800 series scanned in any library and I end up with the DB error mentioned by the OP.

I used to get them frequently before the major upgrade to 8. But this is the first time in a long time I've ran into them.

There was an issue writing to the DB for Series 

The database operation was expected to affect 1 row(s), but actually affected 0 row(s); data may have been modified or deleted since entities were loaded. See https://go.microsoft.com/fwlink/?LinkId=527962 for information on understanding and handling optimistic concurrency exceptions.

**Comment by janaxhell** [comment]
I have launched a library scan yesterday on 0.8.4.0 and today, after about 24hrs of job, I got red DB errors. It happened roughly after scanning 1500 series out of 8000.

**Comment by majora2007** [comment]
It's really unfortunate the users are still reporting this, even though during testing, we saw a drastic reduction of these and the FK issues. 

At this point, I can't really think of a solution to solve this. I'll probably revisit the scanner next year again for some more speed improvements and see if I can tackle this issue again when I'm hopefully smarter. 

The mitigation is to restart Kavita and restart the scan.

**Comment by janaxhell** [comment]
I can understand the frustration.
Will the rescan take over from were it was restarted?
Will it do any good to the monitoring/scheduled task of periodic library scan, or should I disable that and do it manually now and then?

**Comment by majora2007** [comment]
It really depends on your size of your library and how actively you're adding things to it to determine what setup is best. If you give some of that information, I can guide you. 

Not entirely. It will however skip series that were previously updated in the last scan.

**Comment by janaxhell** [comment]
![image](https://github.com/user-attachments/assets/cbe5c954-a907-4fbe-b873-45af5157908a)

I basically add everything that appears on Mylar minus manga and a 10% of random stuff + I add irregular italian comics that I get from emule (some are regular series, some are collection of old series released all together). Oh yes, and italian translated mangas.

**Comment by mrdmiller2** [comment]
I have the same issue as well. and running on 0.8.5.11

Once that error hits, it seems all additional processing of files stops.. .. (I have tons of those errors)

This is running in a Docker container (on linux).:


Kavita] [2025-03-26 01:43:33.968 -07:00  59] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on Killer Queen (Ohue Aguri), Forced: false
[Kavita] [2025-03-26 01:43:33.970 -07:00  59] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series Killer Queen (Ohue Aguri) with 6 files
[Kavita] [2025-03-26 01:43:33.970 -07:00  59] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, Killer Queen (Ohue Aguri) - Vol -100000 Ch 1
[Kavita] [2025-03-26 01:43:36.636 -07:00  59] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, Killer Queen (Ohue Aguri) - Vol -100000 Ch 4
[Kavita] [2025-03-26 01:43:38.990 -07:00  59] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, Killer Queen (Ohue Aguri) - Vol -100000 Ch 3
[Kavita] [2025-03-26 01:43:41.287 -07:00  59] [Debug] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Adding new chapter, Killer Queen (Ohue Aguri) - Vol -100000 Ch 6
[Kavita] [2025-03-26 01:43:41.303 -07:00  80] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/api/series/60 responded 200 in 2.9340 ms
[Kavita] [2025-03-26 01:43:41.325 -07:00  91] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /kavita/api/series/update responded 200 in 18.9223 ms
[Kavita] [2025-03-26 01:43:41.333 -07:00  80] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/api/series/metadata?seriesId=60 responded 200 in 6.2270 ms
[Kavita] [2025-03-26 01:43:41.889 -07:00  91] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /kavita/api/series/metadata responded 200 in 82.0298 ms
[Kavita] [2025-03-26 01:43:42.051 -07:00  59] [Error] Microsoft.EntityFrameworkCore.Database.Command Failed executing DbCommand (1ms) [Parameters=[@p0='7215', @p1='1578', @p2='12'], CommandType='"Text"', CommandTimeout='30']
INSERT INTO "ChapterPeople" ("ChapterId", "PersonId", "Role")
VALUES (@p0, @p1, @p2);
[Kavita] [2025-03-26 01:43:42.348 -07:00  59] [Error] Microsoft.EntityFrameworkCore.Update An exception occurred in the database while saving changes for context type 'API.Data.DataContext'.
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
[Kavita] [2025-03-26 01:43:42.351 -07:00  59] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an issue adding/updating a person
Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
 ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 19: 'FOREIGN KEY constraint failed'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)

**Comment by majora2007** [comment]
It looks like we have finally fixed this issue once and for all as of #4243. It will be out in the v0.8.9 release. If you want to take a stab and test it out on the current nightly (v0.8.8.8) feel free and let me know. Note: You cannot rollback, so please backup your config or use a fresh install for testing.
