### ISSUE TITLE
Error scanning book library: SQLite Error 5: 'database is locked'

### ISSUE THREAD

**Issue by hardwareadictos** [Kareadita/Kavita#2985]
### What happened?

Seems that i have database locks when i try to scan my book library, i have around 130000 books on epub format and it only seem to list 37000:

![image](https://github.com/Kareadita/Kavita/assets/20403906/9d81efa2-c21b-4361-818b-0801cd228eda)

Thanks in advance for the help.

### What did you expect?

Kavita being able to end the scan showing all books

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

Android

### Relevant log output

```shell
Kavita-PRO  | [Kavita] [2024-06-06 15:23:48.771 +02:00  50] [Error] Microsoft.EntityFrameworkCore.Update An exception occurred in the database while saving changes for context type 'API.Data.DataContext'.
Kavita-PRO  | Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
Kavita-PRO  |  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
Kavita-PRO  |    at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()
Kavita-PRO  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Kavita-PRO  |    at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)
Kavita-PRO  | --- End of stack trace from previous location ---
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Kavita-PRO  |    --- End of inner exception stack trace ---
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Kavita-PRO  | Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
Kavita-PRO  |  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
Kavita-PRO  |    at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()
Kavita-PRO  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Kavita-PRO  |    at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)
Kavita-PRO  | --- End of stack trace from previous location ---
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Kavita-PRO  |    --- End of inner exception stack trace ---
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Kavita-PRO  | [Kavita] [2024-06-06 15:23:48.773 +02:00  50] [Error] API.Services.TokenService There was an error updating last active for the user
Kavita-PRO  | Microsoft.EntityFrameworkCore.DbUpdateException: An error occurred while saving the entity changes. See the inner exception for details.
Kavita-PRO  |  ---> Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 5: 'database is locked'.
Kavita-PRO  |    at Microsoft.Data.Sqlite.SqliteDataRecord.Dispose()
Kavita-PRO  |    at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
Kavita-PRO  |    at System.Data.Common.DbDataReader.NextResultAsync(CancellationToken cancellationToken)
Kavita-PRO  | --- End of stack trace from previous location ---
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Kavita-PRO  |    --- End of inner exception stack trace ---
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.AffectedCountModificationCommandBatch.ConsumeAsync(RelationalDataReader reader, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Kavita-PRO  |    at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)
Kavita-PRO  |    at API.Data.UnitOfWork.CommitAsync() in /home/runner/work/Kavita/Kavita/API/Data/UnitOfWork.cs:line 92
```
```


### Additional Notes

_No response_

**Comment by majora2007** [comment]
You can fix this by turning on WAL:
https://wiki.kavitareader.com/troubleshooting/faq#q-im-seeing-database-is-locked-errors-in-my-logs

In the next stable (v0.8.2), Kavita will ship with WAL on by default.

**Comment by hardwareadictos** [comment]
> You can fix this by turning on WAL: https://wiki.kavitareader.com/troubleshooting/faq#q-im-seeing-database-is-locked-errors-in-my-logs
> 
> In the next stable (v0.8.2), Kavita will ship with WAL on by default.

Then I will wait for the next release as I'm running docker and I dont want to mess the container.

Thanks a lot 🙂
