### ISSUE TITLE
Kavita Server crashes randomly after a day or week running

### ISSUE THREAD

**Issue by Dero99** [Kareadita/Kavita#2996]
### What happened?

PWA app says server not responding

### What did you expect?

my books listed

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Mac

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
<cut>
[Kavita] [2024-06-11 19:59:02.943 -07:00  43] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 1.6252 ms
[Kavita] [2024-06-11 19:59:02.944 -07:00  114] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.5530 ms
Unhandled exception. System.ArgumentException: The supplied System.Net.SocketAddress is an invalid size for the System.Net.IPEndPoint end point. (Parameter 'socketAddress')
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAccept(SocketAddress remoteSocketAddress)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncContext.AcceptOperation.InvokeCallback(Boolean allowPooling)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Abort trap: 6

  <another cut>
[Kavita] [2024-06-12 02:08:03.782 -07:00  4] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.4698 ms
[Kavita] [2024-06-12 02:08:03.783 -07:00  125] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 1.6818 ms
Unhandled exception. System.ArgumentException: The supplied System.Net.SocketAddress is an invalid size for the System.Net.IPEndPoint end point. (Parameter 'socketAddress')
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAccept(SocketAddress remoteSocketAddress)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationSyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.AcceptCompletionCallback(IntPtr acceptedFileDescriptor, Memory`1 socketAddress, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEngine.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
Abort trap: 6
```

### Additional Notes

Running on MacOS 12.7.4
launched via Terminal in Kavita directory ./Kavita

**Comment by DieselTech** [comment]
Looks like this might be more of a .NET issue on OSX right now.

https://github.com/dotnet/runtime/issues/102663

**Comment by Dero99** [comment]
I see booting Kavita, server update is available.  Maybe this fixes my server crash issue?

[Warning] API.Services.Tasks.VersionUpdaterService Server is out of date. Current: 0.8.1.0. Available: 0.8.2

**Comment by majora2007** [comment]
I'm not sure if OP is still using Kavita, but curious if this got sorted ever? The latest Kavita is on .NET 9 and the linked issue states it was released with .NET 9.

**Comment by Dero99** [comment]
HiMoved to Ubuntu. That resolved that issue. DarrellOn Mar 20, 2025, at 8:14 AM, Joe Milazzo ***@***.***> wrote:﻿
  I'm not sure if OP is still using Kavita, but curious if this got sorted ever? The latest Kavita is on .NET 9 and the linked issue states it was released with .NET 9.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>



majora2007 left a comment (Kareadita/Kavita#2996)
I'm not sure if OP is still using Kavita, but curious if this got sorted ever? The latest Kavita is on .NET 9 and the linked issue states it was released with .NET 9.

**Comment by majora2007** [comment]
Glad to hear, I'll close this old issue out then.
