### ISSUE TITLE
Kavita Failing to Set a Base URL

### ISSUE THREAD

**Issue by Orski174** [Kareadita/Kavita#3040]
### What happened?

I haven't used Kavita in a while, went to access it and all I got was a black screen in response. Started digging around found that it's failing to set a base url as follows:

```
[Kavita] [2024-07-06 10:05:46.391 +00:00  1] [Error]  There was an error setting base url
System.NullReferenceException: Object reference not set to an instance of an object.
   at API.Startup.UpdateBaseUrlInIndex(String baseUrl) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 430
```

I tried different variations of a base url in the `appsettings.json`, even removed them all together to no avail. I should also mention that `db-wal` and `db-shm` are missing.

### What did you expect?

It's expected for a home page to load, or any page.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-07-06 00:00:11.660 +00:00  41] [Information] API.Services.Tasks.ScannerService Starting Scan of All Libraries, Forced: false
[Kavita] [2024-07-06 00:00:11.664 +00:00  113] [Information] API.Services.Tasks.CleanupService Performing cleanup of Series that are Completed and have been fully read that are in Want To Read list
[Kavita] [2024-07-06 00:00:11.678 +00:00  44] [Information] API.Services.Tasks.CleanupService Starting Cleanup
[Kavita] [2024-07-06 00:00:11.700 +00:00  44] [Information] API.Services.Tasks.CleanupService Cleaning temp directory
[Kavita] [2024-07-06 00:00:11.708 +00:00  44] [Information] API.Services.Tasks.CleanupService Performing cleanup of Cache & Temp directories
[Kavita] [2024-07-06 00:00:11.709 +00:00  44] [Information] API.Services.Tasks.CleanupService Cache and temp directory purged
[Kavita] [2024-07-06 00:00:11.709 +00:00  44] [Information] API.Services.Tasks.CleanupService Cleaning old database backups
[Kavita] [2024-07-06 00:00:11.719 +00:00  44] [Information] API.Services.Tasks.CleanupService Beginning cleanup of Database backups at "2024-07-06T00:00:11.7194894+00:00"
[Kavita] [2024-07-06 00:00:11.727 +00:00  44] [Information] API.Services.Tasks.CleanupService Finished cleanup of Database backups at "2024-07-06T00:00:11.7276191+00:00"
[Kavita] [2024-07-06 00:00:11.727 +00:00  44] [Information] API.Services.Tasks.CleanupService Cleaning deleted cover images
[Kavita] [2024-07-06 00:00:11.812 +00:00  44] [Information] API.Services.Tasks.CleanupService Performing cleanup of logs directory
[Kavita] [2024-07-06 00:00:11.815 +00:00  44] [Information] API.Services.Tasks.CleanupService Finished cleanup of logs at "2024-07-06T00:00:11.8156921+00:00"
[Kavita] [2024-07-06 00:00:11.816 +00:00  44] [Information] API.Services.Tasks.CleanupService Cleaning up any progress rows that exceed chapter page count
[Kavita] [2024-07-06 00:00:11.855 +00:00  44] [Information] API.Services.Tasks.CleanupService Cleaning up any progress rows that exceed chapter page count - complete
[Kavita] [2024-07-06 00:00:12.007 +00:00  41] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Manga
[Kavita] [2024-07-06 00:00:12.072 +00:00  44] [Information] API.Services.Tasks.CleanupService Cleanup finished
[Kavita] [2024-07-06 00:00:12.116 +00:00  113] [Warning] Microsoft.EntityFrameworkCore.Query Collection navigations are only considered null if their parent entity is null. Use 'Any' to check whether collection navigation 'Series.Progress' is empty.
[Kavita] [2024-07-06 00:00:12.140 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Manga/Solo Leveling [Webtoon] (2020-2023) (Digital) (LuCaZ) as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.159 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Manga/Erased v01-09 (2017) (Digital) (LuCaZ) as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.160 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Manga/Hunter x Hunter (Digital) (LuCaZ) as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.163 +00:00  41] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 127 milliseconds. Updating database
[Kavita] [2024-07-06 00:00:12.201 +00:00  41] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 3 series in 302 milliseconds for Manga. There were no changes
[Kavita] [2024-07-06 00:00:12.202 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan
[Kavita] [2024-07-06 00:00:12.219 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: []
[Kavita] [2024-07-06 00:00:12.220 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete
[Kavita] [2024-07-06 00:00:12.277 +00:00  41] [Information] API.Services.Tasks.ScannerService [ScannerService] Beginning file scan on Books
[Kavita] [2024-07-06 00:00:12.345 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Ready Player One Series as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.345 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Art of Computer Programming as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.345 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Parker Pyne Mysteries as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.345 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Five Nights at Freddy's - Fazbear Frights Series as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Press Here! as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Agatha Christie Library as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Hercule Poirot Series as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Miss Marple as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Bodybuilding as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Five Nights at Freddy's as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Massage as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Song of Ice and Fire Series as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Mind Body Spirit Bibles as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.346 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Charlie Bucket as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.347 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Superintendent Battle as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.347 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Harley Quin Mysteries as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.347 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Sherlock Holmes as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.347 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Legend of Zelda - Breath of the Wild the Complete Official Guide - -Expanded Edition, The as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.347 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Coraline as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.347 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Trigger Point as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.347 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Summary - The Subtle Art of Not Giving a F_ck as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.347 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Colonel Race as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.348 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/PMBOKï¿½ Guide as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.348 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Tommy and Tuppence Series as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.349 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Skipped File Scan for /data/!Hard links!/Books/Five Nights at Freddy's Series as it hasn't changed since last scan
[Kavita] [2024-07-06 00:00:12.349 +00:00  41] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished file scan in 71 milliseconds. Updating database
[Kavita] [2024-07-06 00:00:12.355 +00:00  41] [Information] API.Services.Tasks.ScannerService [ScannerService] Finished library scan of 25 series in 85 milliseconds for Books. There were no changes
[Kavita] [2024-07-06 00:00:12.355 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan
[Kavita] [2024-07-06 00:00:12.363 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 0 series that needs to be removed: []
[Kavita] [2024-07-06 00:00:12.363 +00:00  41] [Debug] API.Services.Tasks.ScannerService [ScannerService] Removing Series that were not found during the scan - complete
[Kavita] [2024-07-06 00:00:12.371 +00:00  41] [Information] API.Services.Tasks.ScannerService Scan of All Libraries Finished
[Kavita] [2024-07-06 00:00:12.406 +00:00  113] [Information] API.Services.Tasks.CleanupService Performing cleanup of Series that are Completed and have been fully read that are in Want To Read list, completed
[Kavita] [2024-07-06 02:00:12.073 +00:00  100] [Information] API.Services.Tasks.BackupService Beginning backup of Database at "2024-07-06T02:00:12.0584455+00:00"
[Kavita] [2024-07-06 02:00:12.136 +00:00  100] [Debug] API.Services.Tasks.BackupService Backing up to /app/kavita/config/backups
[Kavita] [2024-07-06 02:00:12.203 +00:00  100] [Error] API.Services.DirectoryService Unable to copy /app/kavita/config/kavita.db-shm to /app/kavita/config/temp/07_06_2024_02_00_12 as it doesn't exist
[Kavita] [2024-07-06 02:00:12.203 +00:00  100] [Error] API.Services.DirectoryService Unable to copy /app/kavita/config/kavita.db-wal to /app/kavita/config/temp/07_06_2024_02_00_12 as it doesn't exist
[Kavita] [2024-07-06 02:00:12.505 +00:00  100] [Information] API.Services.Tasks.BackupService Database backup completed
[Kavita] [2024-07-06 07:42:20.484 +00:00  50] [Information] API.Controllers.PluginController Plugin Tachiyomi-Kavita has authenticated with Orski (1)'s API Key
[Kavita] [2024-07-06 07:42:20.612 +00:00  50] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST "/api/Plugin/authenticate?apiKey=******REDACTED******&pluginName=Tachiyomi-Kavita" responded 200 in 164.9576 ms
[Kavita] [2024-07-06 09:50:05.865 +00:00  136] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 51.3053 ms
[Kavita] [2024-07-06 09:50:06.049 +00:00  132] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /favicon.ico responded 404 in 0.5867 ms
[Kavita] [2024-07-06 09:50:20.903 +00:00  132] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /home responded 200 in 13.3062 ms
[Kavita] [2024-07-06 09:50:21.022 +00:00  132] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /favicon.ico responded 404 in 0.6937 ms
[Kavita] [2024-07-06 09:51:18.913 +00:00  136] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /home responded 200 in 18.5576 ms
[Kavita] [2024-07-06 09:51:19.045 +00:00  130] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /favicon.ico responded 404 in 0.1290 ms
[Kavita] [2024-07-06 09:53:46.065 +00:00  136] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 200 in 6.5001 ms
[Kavita] [2024-07-06 09:58:07.374 +00:00  115] [Information] Microsoft.Hosting.Lifetime Application is shutting down...
[Kavita] [2024-07-06 09:58:13.009 +00:00  4] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 09:58:13.228 +00:00  4] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 09:58:13.825 +00:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2024-07-06 09:58:13.831 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Scan Library Task for daily
[Kavita] [2024-07-06 09:58:13.914 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Backup Task for daily
[Kavita] [2024-07-06 09:58:13.916 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Cleanup Task for daily
[Kavita] [2024-07-06 09:58:13.920 +00:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2024-07-06 09:58:13.945 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling stat collection daily
[Kavita] [2024-07-06 09:58:13.965 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 09:58:13.977 +00:00  6] [Fatal] API.Program Running MigrateEmailTemplates migration - Completed. This is not an error
[Kavita] [2024-07-06 09:58:14.073 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 09:58:14.084 +00:00  1] [Error]  There was an error setting base url
System.NullReferenceException: Object reference not set to an instance of an object.
   at API.Startup.UpdateBaseUrlInIndex(String baseUrl) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 430
[Kavita] [2024-07-06 09:58:14.266 +00:00  1] [Information] API.Program Starting with base url as /
[Kavita] [2024-07-06 09:58:14.319 +00:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://[::]:5000
[Kavita] [2024-07-06 09:58:14.320 +00:00  1] [Information] API.Program Kavita - v0.8.1.0
[Kavita] [2024-07-06 09:58:14.332 +00:00  1] [Information] Microsoft.Hosting.Lifetime Application started. Press Ctrl+C to shut down.
[Kavita] [2024-07-06 09:58:14.332 +00:00  1] [Information] Microsoft.Hosting.Lifetime Hosting environment: Production
[Kavita] [2024-07-06 09:58:14.332 +00:00  1] [Information] Microsoft.Hosting.Lifetime Content root path: /app/kavita
[Kavita] [2024-07-06 09:58:30.235 +00:00  6] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET / responded 304 in 8.8261 ms
[Kavita] [2024-07-06 09:59:13.261 +00:00  42] [Information] Microsoft.Hosting.Lifetime Application is shutting down...
[Kavita] [2024-07-06 09:59:18.721 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 09:59:18.928 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 09:59:19.494 +00:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2024-07-06 09:59:19.500 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Scan Library Task for daily
[Kavita] [2024-07-06 09:59:19.579 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Backup Task for daily
[Kavita] [2024-07-06 09:59:19.581 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Cleanup Task for daily
[Kavita] [2024-07-06 09:59:19.585 +00:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2024-07-06 09:59:19.609 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling stat collection daily
[Kavita] [2024-07-06 09:59:19.626 +00:00  4] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 09:59:19.637 +00:00  4] [Fatal] API.Program Running MigrateEmailTemplates migration - Completed. This is not an error
[Kavita] [2024-07-06 09:59:19.734 +00:00  4] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 09:59:19.743 +00:00  1] [Error]  There was an error setting base url
System.NullReferenceException: Object reference not set to an instance of an object.
   at API.Startup.UpdateBaseUrlInIndex(String baseUrl) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 430
[Kavita] [2024-07-06 09:59:19.907 +00:00  1] [Information] API.Program Starting with base url as /
[Kavita] [2024-07-06 09:59:19.959 +00:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://[::]:5000
[Kavita] [2024-07-06 09:59:19.960 +00:00  1] [Information] API.Program Kavita - v0.8.1.0
[Kavita] [2024-07-06 09:59:19.971 +00:00  1] [Information] Microsoft.Hosting.Lifetime Application started. Press Ctrl+C to shut down.
[Kavita] [2024-07-06 09:59:19.971 +00:00  1] [Information] Microsoft.Hosting.Lifetime Hosting environment: Production
[Kavita] [2024-07-06 09:59:19.971 +00:00  1] [Information] Microsoft.Hosting.Lifetime Content root path: /app/kavita
[Kavita] [2024-07-06 10:00:56.671 +00:00  42] [Information] Microsoft.Hosting.Lifetime Application is shutting down...
[Kavita] [2024-07-06 10:01:01.780 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 10:01:01.988 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 10:01:02.548 +00:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2024-07-06 10:01:02.553 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Scan Library Task for daily
[Kavita] [2024-07-06 10:01:02.635 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Backup Task for daily
[Kavita] [2024-07-06 10:01:02.637 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Cleanup Task for daily
[Kavita] [2024-07-06 10:01:02.643 +00:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2024-07-06 10:01:02.669 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling stat collection daily
[Kavita] [2024-07-06 10:01:02.685 +00:00  4] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 10:01:02.696 +00:00  4] [Fatal] API.Program Running MigrateEmailTemplates migration - Completed. This is not an error
[Kavita] [2024-07-06 10:01:02.795 +00:00  4] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 10:01:02.804 +00:00  1] [Error]  There was an error setting base url
System.NullReferenceException: Object reference not set to an instance of an object.
   at API.Startup.UpdateBaseUrlInIndex(String baseUrl) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 430
[Kavita] [2024-07-06 10:01:02.970 +00:00  1] [Information] API.Program Starting with base url as /
[Kavita] [2024-07-06 10:01:03.022 +00:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://[::]:5000
[Kavita] [2024-07-06 10:01:03.024 +00:00  1] [Information] API.Program Kavita - v0.8.1.0
[Kavita] [2024-07-06 10:01:03.035 +00:00  1] [Information] Microsoft.Hosting.Lifetime Application started. Press Ctrl+C to shut down.
[Kavita] [2024-07-06 10:01:03.035 +00:00  1] [Information] Microsoft.Hosting.Lifetime Hosting environment: Production
[Kavita] [2024-07-06 10:01:03.035 +00:00  1] [Information] Microsoft.Hosting.Lifetime Content root path: /app/kavita
[Kavita] [2024-07-06 10:01:35.465 +00:00  42] [Information] Microsoft.Hosting.Lifetime Application is shutting down...
[Kavita] [2024-07-06 10:01:40.583 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 10:01:40.798 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 10:01:41.359 +00:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2024-07-06 10:01:41.365 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Scan Library Task for daily
[Kavita] [2024-07-06 10:01:41.443 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Backup Task for daily
[Kavita] [2024-07-06 10:01:41.445 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Cleanup Task for daily
[Kavita] [2024-07-06 10:01:41.450 +00:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2024-07-06 10:01:41.474 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling stat collection daily
[Kavita] [2024-07-06 10:01:41.489 +00:00  4] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 10:01:41.502 +00:00  4] [Fatal] API.Program Running MigrateEmailTemplates migration - Completed. This is not an error
[Kavita] [2024-07-06 10:01:41.600 +00:00  4] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 10:01:41.609 +00:00  1] [Error]  There was an error setting base url
System.NullReferenceException: Object reference not set to an instance of an object.
   at API.Startup.UpdateBaseUrlInIndex(String baseUrl) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 430
[Kavita] [2024-07-06 10:01:41.786 +00:00  1] [Information] API.Program Starting with base url as /home/
[Kavita] [2024-07-06 10:01:41.838 +00:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://[::]:5000
[Kavita] [2024-07-06 10:01:41.839 +00:00  1] [Information] API.Program Kavita - v0.8.1.0
[Kavita] [2024-07-06 10:01:41.851 +00:00  1] [Information] Microsoft.Hosting.Lifetime Application started. Press Ctrl+C to shut down.
[Kavita] [2024-07-06 10:01:41.851 +00:00  1] [Information] Microsoft.Hosting.Lifetime Hosting environment: Production
[Kavita] [2024-07-06 10:01:41.851 +00:00  1] [Information] Microsoft.Hosting.Lifetime Content root path: /app/kavita
[Kavita] [2024-07-06 10:04:43.530 +00:00  41] [Information] Microsoft.Hosting.Lifetime Application is shutting down...
[Kavita] [2024-07-06 10:04:48.607 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 10:04:48.822 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 10:04:49.381 +00:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2024-07-06 10:04:49.388 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Scan Library Task for daily
[Kavita] [2024-07-06 10:04:49.471 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Backup Task for daily
[Kavita] [2024-07-06 10:04:49.473 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Cleanup Task for daily
[Kavita] [2024-07-06 10:04:49.478 +00:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2024-07-06 10:04:49.502 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling stat collection daily
[Kavita] [2024-07-06 10:04:49.518 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 10:04:49.530 +00:00  6] [Fatal] API.Program Running MigrateEmailTemplates migration - Completed. This is not an error
[Kavita] [2024-07-06 10:04:49.626 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 10:04:49.635 +00:00  1] [Error]  There was an error setting base url
System.NullReferenceException: Object reference not set to an instance of an object.
   at API.Startup.UpdateBaseUrlInIndex(String baseUrl) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 430
[Kavita] [2024-07-06 10:04:49.811 +00:00  1] [Information] API.Program Starting with base url as /
[Kavita] [2024-07-06 10:04:49.863 +00:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://[::]:5000
[Kavita] [2024-07-06 10:04:49.865 +00:00  1] [Information] API.Program Kavita - v0.8.1.0
[Kavita] [2024-07-06 10:04:49.876 +00:00  1] [Information] Microsoft.Hosting.Lifetime Application started. Press Ctrl+C to shut down.
[Kavita] [2024-07-06 10:04:49.876 +00:00  1] [Information] Microsoft.Hosting.Lifetime Hosting environment: Production
[Kavita] [2024-07-06 10:04:49.876 +00:00  1] [Information] Microsoft.Hosting.Lifetime Content root path: /app/kavita
[Kavita] [2024-07-06 10:05:40.296 +00:00  41] [Information] Microsoft.Hosting.Lifetime Application is shutting down...
[Kavita] [2024-07-06 10:05:45.361 +00:00  4] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 10:05:45.570 +00:00  4] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 10:05:46.140 +00:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
[Kavita] [2024-07-06 10:05:46.146 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Scan Library Task for daily
[Kavita] [2024-07-06 10:05:46.226 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Backup Task for daily
[Kavita] [2024-07-06 10:05:46.228 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling Cleanup Task for daily
[Kavita] [2024-07-06 10:05:46.233 +00:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
[Kavita] [2024-07-06 10:05:46.257 +00:00  1] [Debug] API.Services.TaskScheduler Scheduling stat collection daily
[Kavita] [2024-07-06 10:05:46.273 +00:00  6] [Information] API.Program Running Migrations
[Kavita] [2024-07-06 10:05:46.285 +00:00  6] [Fatal] API.Program Running MigrateEmailTemplates migration - Completed. This is not an error
[Kavita] [2024-07-06 10:05:46.382 +00:00  6] [Information] API.Program Running Migrations - complete
[Kavita] [2024-07-06 10:05:46.391 +00:00  1] [Error]  There was an error setting base url
System.NullReferenceException: Object reference not set to an instance of an object.
   at API.Startup.UpdateBaseUrlInIndex(String baseUrl) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 430
[Kavita] [2024-07-06 10:05:46.571 +00:00  1] [Information] API.Program Starting with base url as /
[Kavita] [2024-07-06 10:05:46.623 +00:00  1] [Information] Microsoft.Hosting.Lifetime Now listening on: http://[::]:5000
[Kavita] [2024-07-06 10:05:46.624 +00:00  1] [Information] API.Program Kavita - v0.8.1.0
[Kavita] [2024-07-06 10:05:46.637 +00:00  1] [Information] Microsoft.Hosting.Lifetime Application started. Press Ctrl+C to shut down.
[Kavita] [2024-07-06 10:05:46.637 +00:00  1] [Information] Microsoft.Hosting.Lifetime Hosting environment: Production
[Kavita] [2024-07-06 10:05:46.637 +00:00  1] [Information] Microsoft.Hosting.Lifetime Content root path: /app/kavita
```

**Comment by majora2007** [comment]
Can you include a copy of your appsettings.json with your TokenKey changed to be the string "Hello World"? Please include it with the desired baseUrl.

**Comment by Orski174** [comment]
Sure!

```
{
  "TokenKey": "Hello World",
  "Port": 5000,
  "Cache": 50,
  "AllowIFraming": false
}
```
I removed the ip and baseurl entries, so it would pick the defaults. My preferred base url is the default: `/`.

**Comment by majora2007** [comment]
I don't think you're supposed to remove them, but let me recheck the logic. It's been some time since I last looked at how it works.

You do know that you can do everything through the UI right? Kavita will update the file for you.

**Comment by Orski174** [comment]
Yes but I can't reach the UI, that's kinda the entire problem.

I can successfully reach kavita and it would return 200, but nothing shows up.

**Comment by majora2007** [comment]
That's fair. I'll try and reproduce this later today if I have a chance, otherwise @DieselTech if you have time.

**Comment by DieselTech** [comment]
Have you tried renaming the file to something different and letting kavita create a new one at startup? 

Also are you using a reverse proxy to access kavita, or going directly to it?

**Comment by Orski174** [comment]
Hi, I totally forgot about this, I did try that when I was testing and yes I'm behind a reverse proxy.

But good news, It magically worked on its own later. Not really sure what changed but it works now.

Thanks again!!
