### ISSUE TITLE
Double Dark Theme in Theme Manager

### ISSUE THREAD

**Issue by X-Xadro** [Kareadita/Kavita#3044]
### What happened?

Just updated to v0.8.2 (from the previous version) and wanted to try out Themes because i never tried it before and then i got this:

![2024-07-08 12_20_07-Kavita - User Preferences - Brave](https://github.com/Kareadita/Kavita/assets/87056274/54f6449a-5a58-41bc-b138-6353dbcaafb4)

### What did you expect?

A List of Themes to be honestly.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-07-08 12:15:29.473 +02:00  56] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.ArgumentException: An item with the same key has already been added. Key: Dark
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at API.Services.Tasks.ThemeService.GetDownloadableThemes() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\SiteThemeService.cs:line 123
   at API.Controllers.ThemeController.BrowseThemes() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Controllers\ThemeController.cs:line 94
   at lambda_method1726(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at API.Startup.<>c__DisplayClass4_0.<<Configure>b__5>d.MoveNext() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 405
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\SecurityMiddleware.cs:line 25
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\ExceptionMiddleware.cs:line 18
```

### Additional Notes

Repository: [linuxserver/docker-kavita](https://github.com/linuxserver/docker-kavita) · Tag: [v0.8.2-ls41](https://github.com/linuxserver/docker-kavita/tree/v0.8.2-ls41)

**Comment by acaranta** [comment]
updated docker image to latest 0.8.2 and got the "same" problem except it's not just 2
![image](https://github.com/user-attachments/assets/8c293cf7-9400-43a8-a597-71466e113ab3)
but dozens.

Same error show up in logs.

**Comment by majora2007** [comment]
This is a migration issue where somehow the old Dark themes weren't removed. You can either remove them in your DB or wait till the next release where I will add a custom migration to remove the old ones. This theme manager implementation required switching from how System (provided) themes worked and thus something must have slipped through and no one from nightly testing group saw this.

**Comment by acaranta** [comment]
indeed, empting the SiteTheme table and restarting the container allowed to cleanup the list and let kavita retreve/repopulate properly it's themes :)

**Comment by X-Xadro** [comment]
Can confirm, after deleting all entries from SiteTheme table and restarting the container it showed all available themes (which it did not do before) and only a single Dark theme :)

**Comment by majora2007** [comment]
Going to reopen this and add a migration so users don't need to do this manually, something I thought I had done but must have forgotten.
