### ISSUE TITLE
[epub] 400 Error - Could not find the appropriate html for that page

### ISSUE THREAD

**Issue by Fabienjulio** [Kareadita/Kavita#3055]
### What happened?

The error is similar to #2759 (at least on the UI) but I got a different log output.
![image](https://github.com/user-attachments/assets/bfb6b90a-f37e-4708-8ec0-6b62fecfe67c)

### What did you expect?

Opening the next chapter.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.1 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-07-15 07:03:18.714 +00:00  139] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/book/4/book-page?page=918 responded 400 in 132.8573 ms
[Kavita] [2024-07-15 07:03:40.985 +00:00  134] [Error] API.Services.BookService There was an issue reading one of the pages for /kavita/config/cache/4/Return Of The Mount Hua Sect - 1-1636.epub
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at API.Services.BookService.InlineStyles(HtmlDocument doc, EpubBookRef book, String apiBase, HtmlNode body) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 396
   at API.Services.BookService.ScopePage(HtmlDocument doc, EpubBookRef book, String apiBase, HtmlNode body, Dictionary`2 mappings, Int32 page) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 920
   at API.Services.BookService.GetBookPage(Int32 page, Int32 chapterId, String cachedEpubPath, String baseUrl) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 1158
[Kavita] [2024-07-15 07:03:40.991 +00:00  134] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/book/4/book-page?page=919 responded 400 in 130.3603 ms
[Kavita] [2024-07-15 07:04:40.042 +00:00  140] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /api/account/refresh-token responded 200 in 122.6311 ms
[Kavita] [2024-07-15 07:04:40.088 +00:00  133] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /hubs/messages/negotiate?negotiateVersion=1 responded 200 in 6.8558 ms
[Kavita] [2024-07-15 07:04:40.092 +00:00  140] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/device responded 200 in 35.1035 ms
[Kavita] [2024-07-15 07:04:40.102 +00:00  132] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/license/valid-license?forceCheck=false responded 200 in 27.8579 ms
```

**Comment by majora2007** [comment]
This is a common error for ePub files. Rerun the epub through caliber or sigil and it will fix up the broken internal metadata.
