### ISSUE TITLE
System.Net.Sockets.SocketException (13): Permission denied with selinux enabled when starting Kavita

### ISSUE THREAD

**Issue by Neurozone** [Kareadita/Kavita#3074]
### What happened?

Kavita fail to start when selinux is enabled on rocky linux 9.4 with aspnetcore 8

### What did you expect?

Kavita should start when doing 
systemctl start kavita

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Linux

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
systemd[1]: Started Kavita Server.
Kavita[440433]: [Kavita] [2024-07-23 14:11:18.747 +02:00  6] [Information] API.Program Running Manual Migrations
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.013 +02:00  6] [Fatal] API.Program Running MigrateWantToReadExport migration - Please be patient, this may take some time. This is not an error
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.033 +02:00  6] [Information] API.Program Running Manual Migrations - complete
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.591 +02:00  1] [Information] API.Services.TaskScheduler Scheduling reoccurring tasks
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.599 +02:00  1] [Debug] API.Services.TaskScheduler Scheduling Scan Library Task for daily
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.700 +02:00  1] [Debug] API.Services.TaskScheduler Scheduling Backup Task for daily
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.708 +02:00  1] [Debug] API.Services.TaskScheduler Scheduling Cleanup Task for daily
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.714 +02:00  1] [Information] API.Services.TaskScheduler Scheduling Auto-Update tasks
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.745 +02:00  1] [Debug] API.Services.TaskScheduler Scheduling stat collection daily
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.768 +02:00  4] [Information] API.Program Running Migrations
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.801 +02:00  4] [Fatal] API.Program Running MigrateUserLibrarySideNavStream migration - Please be patient, this may take some time. This is not an error
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.801 +02:00  4] [Fatal] API.Program Running MigrateUserLibrarySideNavStream migration - Completed. This is not an error
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.808 +02:00  4] [Fatal] API.Program Running MigrateLibrariesToHaveAllFileTypes migration - Please be patient, this may take some time. This is not an error
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.825 +02:00  4] [Fatal] API.Program Running MigrateLibrariesToHaveAllFileTypes migration - Completed. This is not an error
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.835 +02:00  4] [Fatal] API.Program Running MigrateVolumeNumber migration - Please be patient, this may take some time. This is not an error
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.842 +02:00  4] [Fatal] API.Program Running MigrateVolumeNumber migration - Completed. This is not an error
Kavita[440433]: [Kavita] [2024-07-23 14:11:19.846 +02:00  4] [Fatal] API.Program Running MigrateWantToReadImport migration - Completed. This is not an error
Kavita[440433]: [Kavita] [2024-07-23 14:11:20.037 +02:00  4] [Information] API.Program Running Migrations - complete
Kavita[440433]: [Kavita] [2024-07-23 14:11:20.273 +02:00  1] [Information] API.Program Starting with base url as /
Kavita[440433]: [Kavita] [2024-07-23 14:11:20.335 +02:00  1] [Error] Microsoft.Extensions.Hosting.Internal.Host Hosting failed to start
Kavita[440433]: System.Net.Sockets.SocketException (13): Permission denied
Kavita[440433]:   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
Kavita[440433]:   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
Kavita[440433]: --- End of stack trace from previous location ---
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Kavita[440433]: [Kavita] [2024-07-23 14:11:20.351 +02:00  1] [Fatal]  Host terminated unexpectedly
Kavita[440433]: System.Net.Sockets.SocketException (13): Permission denied
Kavita[440433]:   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
Kavita[440433]:   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportOptions.CreateDefaultBoundListenSocket(EndPoint endpoint)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketConnectionListener.Bind()
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Transport.Sockets.SocketTransportFactory.BindAsync(EndPoint endpoint, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Infrastructure.TransportManager.BindAsync(EndPoint endPoint, ConnectionDelegate connectionDelegate, EndpointConfig endpointConfig, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.<>c__DisplayClass28_0`1.<<StartAsync>g__OnBind|0>d.MoveNext()
Kavita[440433]: --- End of stack trace from previous location ---
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindEndpointAsync(ListenOptions endpoint, AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.ListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.AnyIPListenOptions.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.EndpointsStrategy.BindAsync(AddressBindContext context, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.AddressBinder.BindAsync(ListenOptions[] listenOptions, AddressBindContext context, Func`2 useHttps, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.BindAsync(CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Server.Kestrel.Core.KestrelServerImpl.StartAsync[TContext](IHttpApplication`1 application, CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
Kavita[440433]:   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
Kavita[440433]:   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Kavita[440433]:   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
Kavita[440433]:   at API.Program.Main(String[] args) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Program.cs:line 149
systemd[1]: kavita.service: Deactivated successfully.
systemd[1]: kavita.service: Consumed 3.502s CPU time.
```

### Additional Notes

rpm -qa | grep aspnet
aspnetcore-runtime-6.0-6.0.32-1.el9_4.x86_64
aspnetcore-runtime-8.0-8.0.7-1.el9_4.x86_64
aspnetcore-targeting-pack-8.0-8.0.7-1.el9_4.x86_64

env variables:
SHELL=/bin/bash
HISTCONTROL=ignoredups
HISTSIZE=1000
HOSTNAME=neurozone.fr
DOTNET_ROOT=/usr/lib64/dotnet
PWD=/home/kavita
LOGNAME=kavita
HOME=/home/kavita
LANG=C.UTF-8
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=01;37;41:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=01;36:*.au=01;36:*.flac=01;36:*.m4a=01;36:*.mid=01;36:*.midi=01;36:*.mka=01;36:*.mp3=01;36:*.mpc=01;36:*.ogg=01;36:*.ra=01;36:*.wav=01;36:*.oga=01;36:*.opus=01;36:*.spx=01;36:*.xspf=01;36:
DOTNET_BUNDLE_EXTRACT_BASE_DIR=/home/kavita/.cache/dotnet_bundle_extract
TERM=xterm
LESSOPEN=||/usr/bin/lesspipe.sh %s
USER=kavita
SHLVL=1
S_COLORS=auto
DEBUGINFOD_URLS=https://debuginfod.centos.org/
which_declare=declare -f
XDG_DATA_DIRS=/home/kavita/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share:/usr/share
PATH=/home/kavita/.local/bin:/home/kavita/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/kavita/.dotnet/tools
MAIL=/var/spool/mail/kavita
BASH_FUNC_which%%=() {  ( alias;
 eval ${which_declare} ) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot $@
}
_=/usr/bin/env

kavita.service

cat /etc/systemd/system/kavita.service
[Unit]
Description=Kavita Server
After=network.target suricata.service

[Service]
User=kavita
Group=kavita
Type=simple
WorkingDirectory=/data/Kavita
ExecStart=/data/Kavita/Kavita
TimeoutStopSec=20
KillMode=process
#Restart=on-failure
Environment=ASPNETCORE_ENVIRONMENT=Production
Environment=DOTNET_PRINT_TELEMETRY_MESSAGE=false

[Install]
WantedBy=multi-user.target

**Comment by Neurozone** [comment]
Found the solution, it was a hidden selinux rule:

`Jul 24 13:49:53 setroubleshoot[71999]: SELinux is preventing /data/Kavita/Kavita from name_bind access on the tcp_socket port 5000. For complete SELinux messages run: sealert -l 12fee786-2741-47f5-91ca-90d301101db1
Jul 24 13:49:54 setroubleshoot[71999]: SELinux is preventing /data/Kavita/Kavita from name_bind access on the tcp_socket port 5000.
*****  Plugin catchall_boolean (89.3 confidence) suggests   ******************
If you want to allow httpd to access openstack ports
Then you must tell SELinux about this by enabling the 'httpd_use_openstack' boolean.
You can read 'httpd_selinux' man page for more details.
setsebool -P httpd_use_openstack 1
*****  Plugin catchall (11.6 confidence) suggests   **************************
If you believe that Kavita should be allowed name_bind access on the port 5000 tcp_socket by default.
Then you should report this as a bug.
You can generate a local policy module to allow this access.
allow this access for now by executing:
 ausearch -c 'Kavita' --raw | audit2allow -M my-Kavita
 semodule -X 300 -i my-Kavita.pp#
`

needed to add 
allow httpd_t commplex_main_port_t:tcp_socket name_bind;

as selinux rule
