### ISSUE TITLE
When selecting "Themes" tab i get "An item with the same key has already been added. Key: Dark" error

### ISSUE THREAD

**Issue by Bartype** [Kareadita/Kavita#3084]
### What happened?

When i select the Themes tab i see this error. Also, the "Dark" theme is shown 3 times and no other themes are visible. Only the first of these 3 "Dark" themes says "Default theme shipped with Kavita". I am not able to delete the other two.

![Theme](https://github.com/user-attachments/assets/31a13013-ff57-49ee-a0de-8661cfdc023b)

### What did you expect?

The theme overhaul should show more themes as described and at least not giving this error.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.2 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

Windows

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox, Safari

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

iOS

### If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?

Other iOS Browser

### Relevant log output

```shell
at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
[Kavita] [2024-07-27 10:57:03.393 +02:00  62] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/api/account/opds-url responded 200 in 0.5897 ms
[Kavita] [2024-07-27 10:57:03.393 +02:00  55] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/api/settings/opds-enabled responded 200 in 0.4197 ms
[Kavita] [2024-07-27 10:57:03.393 +02:00  59] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/api/locale responded 200 in 0.6033 ms
[Kavita] [2024-07-27 10:57:03.394 +02:00  58] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/api/users/get-preferences responded 200 in 0.7505 ms
[Kavita] [2024-07-27 10:57:03.394 +02:00  60] [Error] API.Middleware.ExceptionMiddleware There was an exception
System.ArgumentException: An item with the same key has already been added. Key: Dark
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](List`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at API.Services.Tasks.ThemeService.GetDownloadableThemes() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\SiteThemeService.cs:line 123
   at API.Controllers.ThemeController.BrowseThemes() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Controllers\ThemeController.cs:line 94
   at lambda_method2537(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at API.Startup.<>c__DisplayClass4_0.<<Configure>b__5>d.MoveNext() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 405
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\SecurityMiddleware.cs:line 25
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\ExceptionMiddleware.cs:line 18
[Kavita] [2024-07-27 10:57:03.400 +02:00  55] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP POST /kavita/hubs/messages/negotiate?negotiateVersion=1 responded 200 in 0.1490 ms
[Kavita] [2024-07-27 10:57:03.401 +02:00  55] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/api/device responded 200 in 0.4697 ms
[Kavita] [2024-07-27 10:57:03.401 +02:00  60] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /kavita/api/license/valid-license?forceCheck=false responded 200 in 0.2366 ms
```

**Comment by majora2007** [comment]
This should be fixed as of v0.8.3 and an additional fix in v0.8.4 to fully remove those extra Dark themes (a migration bug)
