### ISSUE TITLE
Error when scanning epub books

### ISSUE THREAD

**Issue by CircleCrop** [Kareadita/Kavita#3322]
### What happened?

Some books cannot be added. "There was an exception parsing metadata There was an exception when opening epub book" displayed on `/settings#admin-media-issues`. However, these books can be opened in other epub readers like calibre.

Epub books Url: https://drive.google.com/file/d/1iNTIa2nQbxbl8ZO0e7yeWJleVVr9fbTA/view?usp=sharing

Logs:
```
[Kavita] [2024-10-31 12:34:44.264 +08:00  197] [Warning] API.Services.BookService [GetComicInfo] There was an exception parsing metadata
VersOne.Epub.EpubPackageException: Incorrect EPUB manifest: item with href = "css/main.css" is not unique.
   at VersOne.Epub.Utils.TaskExtensionMethods.ExecuteAndUnwrapAggregateException[T](Task`1 task)
   at VersOne.Epub.Internal.BookRefReader.OpenBook(String filePath)
   at VersOne.Epub.EpubReader.OpenBook(String filePath, EpubReaderOptions epubReaderOptions)
   at API.Services.BookService.GetComicInfo(String filePath) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 434
[Kavita] [2024-10-31 12:34:44.265 +08:00  197] [Warning] API.Services.BookService [BookService] There was an exception when opening epub book: /books/李光耀/经济腾飞路：李光耀回忆录 (5)/经济腾飞路：李光耀回忆录 - 李光耀.epub
VersOne.Epub.EpubPackageException: Incorrect EPUB manifest: item with href = "css/main.css" is not unique.
   at VersOne.Epub.Utils.TaskExtensionMethods.ExecuteAndUnwrapAggregateException[T](Task`1 task)
   at VersOne.Epub.Internal.BookRefReader.OpenBook(String filePath)
   at VersOne.Epub.EpubReader.OpenBook(String filePath, EpubReaderOptions epubReaderOptions)
   at API.Services.BookService.ParseInfo(String filePath) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 786
[Kavita] [2024-10-31 12:34:44.266 +08:00  197] [Error] API.Services.ReadingItemService Unable to parse any meaningful information out of file /books/李光耀/经济腾飞路：李光耀回忆录 (5)/经济腾飞路：李光耀回忆录 - 李光耀.epub
```

### What did you expect?

These epub books can be correctly opened and added.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.3 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-10-31 12:34:44.264 +08:00  197] [Warning] API.Services.BookService [GetComicInfo] There was an exception parsing metadata
VersOne.Epub.EpubPackageException: Incorrect EPUB manifest: item with href = "css/main.css" is not unique.
   at VersOne.Epub.Utils.TaskExtensionMethods.ExecuteAndUnwrapAggregateException[T](Task`1 task)
   at VersOne.Epub.Internal.BookRefReader.OpenBook(String filePath)
   at VersOne.Epub.EpubReader.OpenBook(String filePath, EpubReaderOptions epubReaderOptions)
   at API.Services.BookService.GetComicInfo(String filePath) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 434
[Kavita] [2024-10-31 12:34:44.265 +08:00  197] [Warning] API.Services.BookService [BookService] There was an exception when opening epub book: /books/李光耀/经济腾飞路：李光耀回忆录 (5)/经济腾飞路：李光耀回忆录 - 李光耀.epub
VersOne.Epub.EpubPackageException: Incorrect EPUB manifest: item with href = "css/main.css" is not unique.
   at VersOne.Epub.Utils.TaskExtensionMethods.ExecuteAndUnwrapAggregateException[T](Task`1 task)
   at VersOne.Epub.Internal.BookRefReader.OpenBook(String filePath)
   at VersOne.Epub.EpubReader.OpenBook(String filePath, EpubReaderOptions epubReaderOptions)
   at API.Services.BookService.ParseInfo(String filePath) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 786
[Kavita] [2024-10-31 12:34:44.266 +08:00  197] [Error] API.Services.ReadingItemService Unable to parse any meaningful information out of file /books/李光耀/经济腾飞路：李光耀回忆录 (5)/经济腾飞路：李光耀回忆录 - 李光耀.epub
```

**Comment by scare376** [comment]
Kavita is much more strict than other readers when it comes to epubs. https://wiki.kavitareader.com/troubleshooting/media-errors has a list of typical errors we see.

To fix most epub issues you should be able to reconvert them to epub in calibre.

**Comment by CircleCrop** [comment]
thanks
