### ISSUE TITLE
System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by DieselTech** [Kareadita/Kavita#3337]
### What happened?

Scan triggered last night at 00:00, 1300+ entries of this error was in the logs after that. 

### What did you expect?

.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

Nightly Testing Branch

### What operating system is Kavita being hosted from?

None

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-11-03 00:43:54.557 -04:00  53] [Debug] API.Services.Tasks.ScannerService [TIME] Kavita took 6 ms to process Black Hammer '45
[Kavita] [2024-11-03 00:43:54.557 -04:00  53] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Beginning series update on American Splendor Special: A Step out of the Nest, Forced: false
[Kavita] [2024-11-03 00:43:54.562 -04:00  53] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series American Splendor Special: A Step out of the Nest with 1 files
[Kavita] [2024-11-03 00:43:54.562 -04:00  53] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for American Splendor Special: A Step out of the Nest
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at System.Globalization.NumberFormatInfo.get_CurrentInfo()
   at API.Entities.Volume.GetNumberTitle() in /home/runner/work/Kavita/Kavita/API/Entities/Volume.cs:line 72
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 621
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 118
```

### Additional Notes
Filename: `American Splendor Special A Step out of the Nest 001 (1994).cbz
`
The `Comicinfo.xml` from that specific file mentioned in the logs above is here:

```xml
<?xml version="1.0"?>
<ComicInfo xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <Series>American Splendor Special: A Step out of the Nest</Series>
  <Number>1</Number>
  <Volume>1</Volume>
  <Summary>He's stared into the Monkeycam and lived to tell about it! Critically-acclaimed comics writer Harvey Pekar returns to the racks with his first 32-page comics story ever. It chronicles Harvey's adventures in New York City last spring as he's invited to appear on "Late Night with David Letterman" after a four year hiatus - only to be bumped at the last minute by Barry Manilow! Will the fists start flying? This special stand-alone storyline is full of the gentle wisdom and understated irony for which Pekar is renown.</Summary>
  <Notes>Tagged with the ninjas.walk.alone fork of ComicTagger 1.3.4 using info from Comic Vine on 2021-05-26 00:27:28.  [Issue ID 227415]</Notes>
  <Year>1994</Year>
  <Month>08</Month>
  <Day>01</Day>
  <Writer>Harvey Pekar</Writer>
  <Penciller>Joe Zabel</Penciller>
  <Inker>Joe Zabel</Inker>
  <Letterer>Gary Dumm</Letterer>
  <CoverArtist>Joe Zabel</CoverArtist>
  <Editor>Diana Schutz</Editor>
  <Publisher>Dark Horse Comics</Publisher>
  <Web>https://comicvine.gamespot.com/american-splendor-special-a-step-out-of-the-nest-1/4000-227415/</Web>
  <PageCount>37</PageCount>
  <Characters>Barry Manilow, David Letterman, Harvey Pekar, Joyce Brabner, Paul Shaffer, Sarah Jessica Parker</Characters>
  <Locations>Cleveland, New York City</Locations>
  <Pages>
    <Page Image="0" Type="FrontCover" ImageSize="441304" />
    <Page Image="1" ImageSize="497305" />
    <Page Image="2" ImageSize="388095" />
    <Page Image="3" ImageSize="417110" />
    <Page Image="4" ImageSize="406658" />
    <Page Image="5" ImageSize="410366" />
    <Page Image="6" ImageSize="437676" />
    <Page Image="7" ImageSize="409259" />
    <Page Image="8" ImageSize="447014" />
    <Page Image="9" ImageSize="426215" />
    <Page Image="10" ImageSize="380415" />
    <Page Image="11" ImageSize="366664" />
    <Page Image="12" ImageSize="369754" />
    <Page Image="13" ImageSize="395490" />
    <Page Image="14" ImageSize="408952" />
    <Page Image="15" ImageSize="432642" />
    <Page Image="16" ImageSize="408423" />
    <Page Image="17" ImageSize="409082" />
    <Page Image="18" ImageSize="423395" />
    <Page Image="19" ImageSize="450394" />
    <Page Image="20" ImageSize="455332" />
    <Page Image="21" ImageSize="443729" />
    <Page Image="22" ImageSize="437819" />
    <Page Image="23" ImageSize="406612" />
    <Page Image="24" ImageSize="411781" />
    <Page Image="25" ImageSize="439107" />
    <Page Image="26" ImageSize="424447" />
    <Page Image="27" ImageSize="413124" />
    <Page Image="28" ImageSize="400069" />
    <Page Image="29" ImageSize="428286" />
    <Page Image="30" ImageSize="424647" />
    <Page Image="31" ImageSize="387085" />
    <Page Image="32" ImageSize="418822" />
    <Page Image="33" ImageSize="422237" />
    <Page Image="34" ImageSize="377172" />
    <Page Image="35" ImageSize="479389" />
    <Page Image="36" ImageSize="132681" />
  </Pages>
</ComicInfo>
```

**Comment by majora2007** [comment]
Not sure how to reproduce. I put this xml on my system and no issues at all. The code in question is just turning a float into a string.

**Comment by majora2007** [comment]
As we now know, this issue is due to locale defaults, see https://github.com/Kareadita/Kavita/issues/3408
