### ISSUE TITLE
Both regular scan and force scan error out

### ISSUE THREAD

**Issue by YaibaToKen** [Kareadita/Kavita#3408]
### What happened?

Scan starts and finishes a couple of seconds later, not picking up on new Comics.

### What did you expect?

Scan to take longer than a few seconds and pick on new Comics.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4 - Stable

### What operating system is Kavita being hosted from?

Docker (Dockerhub Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-11-25 14:39:37.716 +00:00  243] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series Angel with 17 files
[Kavita] [2024-11-25 14:39:37.716 +00:00  243] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for Angel
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at API.Entities.Volume.GetNumberTitle() in /home/runner/work/Kavita/Kavita/API/Entities/Volume.cs:line 72
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 620
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 118
[Kavita] [2024-11-25 14:39:37.716 +00:00  243] [Debug] API.Services.Tasks.ScannerService [TIME] Kavita took 4 ms to process Angel
```

**Comment by YaibaToKen** [comment]
This does not seem to happen on the current nightly release

**Comment by YaibaToKen** [comment]
```
[Kavita] [2024-11-25 17:06:17.106 +00:00  103] [Information] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] Processing series Convergence Justice League of America with 2 files
[Kavita] [2024-11-25 17:06:17.106 +00:00  103] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for Convergence Justice League of America
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at API.Entities.Volume.GetNumberTitle() in /home/runner/work/Kavita/Kavita/API/Entities/Volume.cs:line 70
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 620
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 118
[Kavita] [2024-11-25 17:06:17.106 +00:00  103] [Debug] API.Services.Tasks.ScannerService [TIME] Kavita took 0 ms to process Convergence Justice League of America
```
This apparently still happens in the current nightly.

**Comment by ComputerWolf** [comment]
Not sure if this the same issue or something that needs a separate issue but I am experiencing something similar on both Scoop and Docker installs on Windows. My books are on a Windows mount if that makes a difference. No new books can be added and it errors out reading metadata on existing books when doing a forced scan.

```
[Kavita] [2024-11-24 23:26:00.413 -05:00  86] [Error] API.Services.Tasks.ScannerService [ScannerService] Issue occurred while setting IssueOrder for series Legends & Lattes
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at System.Runtime.CompilerServices.DefaultInterpolatedStringHandler.AppendFormatted[T](T value)
   at API.Services.Tasks.Scanner.ParseScannedFiles.UpdateSortOrder(ConcurrentDictionary`2 scannedSeries, ParsedSeries series) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ParseScannedFiles.cs:line 825
   at API.Services.Tasks.Scanner.ParseScannedFiles.UpdateSeriesSortOrder(ConcurrentDictionary`2 scannedSeries) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\Tasks\Scanner\ParseScannedFiles.cs:line 554
   ```

**Comment by joelaw9** [comment]
Getting the same error as Yaiba. Install is on a Debian LXC container, using a TrueNAS drive for manga storage.

**Comment by jeffp1717** [comment]
What happened?
Scan starts and finishes a couple of seconds later, not picking up on new Comics/Books.

What did you expect?
Scan to take longer than a few seconds and pick on new Comics/Books.

Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.
0.8.4 - Stable

What operating system is Kavita being hosted from?
Docker (Dockerhub Container) lscr.io/linuxserver/kavita

If the issue is being seen on Desktop, what OS are you running where you see the issue?
Unraid

If the issue is being seen in the UI, what browsers are you seeing the problem on?
Chrome/Firefox

If the issue is being seen on Mobile, what OS are you running where you see the issue?
None

If the issue is being seen on the Mobile UI, what browsers are you seeing the problem on?
No response

Relevant log output:
```
[Kavita] [2024-11-25 15:52:38.164 -05:00  204] [Debug] API.Services.Tasks.ScannerService [ScannerService] Found 67 files for /data/books2/Stephen King
[Kavita] [2024-11-25 15:52:38.165 -05:00  397] [Debug] API.Controllers.LibraryController Caching libraries for library_admin
[Kavita] [2024-11-25 15:52:38.167 -05:00  397] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/library/libraries responded 200 in 3.4748 ms
[Kavita] [2024-11-25 15:52:38.216 -05:00  397] [Information] Serilog.AspNetCore.RequestLoggingMiddleware HTTP GET /api/stream/sidenav?visibleOnly=true responded 200 in 6.7886 ms
[Kavita] [2024-11-25 15:52:38.207 -05:00  204] [Warning] API.Services.BookService [GetComicInfo] There was an exception parsing metadata
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at Nager.ArticleNumber.ArticleNumberHelper.IsValidIsbn13(String isbn13)
   at API.Services.BookService.GetComicInfo(String filePath) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 467
```

**Comment by majora2007** [comment]
If anyone has an epub that reproduces this, please send it to me. I have a hotfix planned for today/tomorrow, this needs to be in it. I saw this in the testing phase, but it was fixed and confirmed. So something else must be triggering this error.

**Comment by YaibaToKen** [comment]
I'm having this issue with CBZs but I can try to check my ePub lib for the error as well

**Comment by majora2007** [comment]
@YaibaToKen this isn't possible to hit with a CBZ. Create another issue for me with the stack trace. 

I have created an issue for this with the underlying library. I will need to rollback the update (which fixed another issue). 

https://github.com/vers-one/EpubReader/issues/116

**Comment by YaibaToKen** [comment]
```
[Kavita] [2024-11-26 11:54:58.701 +00:00  218] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for The Very Secret Society of Irregular Witches
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at API.Entities.Volume.GetNumberTitle() in /home/runner/work/Kavita/Kavita/API/Entities/Volume.cs:line 72
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 620
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/
```

**Comment by YaibaToKen** [comment]
> @YaibaToKen this isn't possible to hit with a CBZ. Create another issue for me with the stack trace.
> 
> I have created an issue for this with the underlying library. I will need to rollback the update (which fixed another issue).
> 
> [vers-one/EpubReader#116](https://github.com/vers-one/EpubReader/issues/116)

The stack trace at the very beginning of the issue was from a scan to my Comics lib, set as a ComicVine library though.

**Comment by majora2007** [comment]
Oops this is on me. I replied on the wrong issue. It's only 6am for me. Let me wrap this other epub issue then come back to this one.

**Comment by YaibaToKen** [comment]
No problem, I do hope however that epub I sent helps.

**Comment by majora2007** [comment]
Is anyone here on a non-US locale by chance? I can't seem to reproduce the issue on any files users are sending me.

**Comment by majora2007** [comment]
@jeffp1717 what is the OS? Are you running on docker?

**Comment by YaibaToKen** [comment]
> Is anyone here on a non-US locale by chance? I can't seem to reproduce the issue on any files users are sending me.

If you mean Kavita's locale, mine is set to English.

**Comment by majora2007** [comment]
Okay, so it seems like this could be related to docker. I spoke with jeffp1717 on discord. I tried both their and your file and was unable to reproduce the issue on my Windows machine. 

I asked in the discord for someone to test it on a non-docker setup. I'm out of time for the morning to code before work, after work I'll be looping back on this and try to make some leeway.

**Comment by majora2007** [comment]
Update: Had another user run the latest on Windows and no issues ingesting the files users have sent me. This is likely linked to docker (or perhaps unraid itself).

**Comment by majora2007** [comment]
Cancel that, we were able to get them scanned in via Unraid. I have no idea how to reproduce this issue, but there are multiple people hitting it. There must be something we aren't seeing. 

Please add more information about setups and please include the underlying or docker locale. Like if your OS is not in english, that is information I need to know. 

Please also include Library type.

**Comment by YaibaToKen** [comment]
System locale info:
![image](https://github.com/user-attachments/assets/38b52af7-d5a2-46bc-b9b3-1bb85a3e7bd3)

I'm running Kavita through Docker hosted on a DietPi install (Debian based). The OS is x86.
Image is from DockerHub: jvmilazz0/kavita:nightly
Library type is ComicVine.

I can add my compose as well, if you think it could help.

**Comment by YaibaToKen** [comment]
This does indeed seem to be a locale issue as changing my locale from `C.UTF-8` to `en_US.UTF-8` I no longer get the errors.

**Comment by ComputerWolf** [comment]
I am experiencing the issue with Docker on a Windows machine but also with Scoop. Windows is set to `en-US`, WSL is `C.UTF-8` and the Docker container itself seems to have no locale set by default.

On a fresh Docker install it scans properly the first time and then the subsequent force scan gives me many similar errors:

```
[Kavita] [2024-11-26 11:31:13.787 -05:00  93] [Warning] API.Services.BookService [GetComicInfo] There was an exception parsing metadata
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.get_NumberFormat()
   at Nager.ArticleNumber.ArticleNumberHelper.IsValidIsbn13(String isbn13)
   at API.Services.BookService.GetComicInfo(String filePath) in /home/runner/work/Kavita/Kavita/API/Services/BookService.cs:line 467
```
```
[Kavita] [2024-11-26 11:33:13.088 -05:00  93] [Error] API.Services.Tasks.ScannerService [ScannerService] Issue occurred while setting IssueOrder for series By Any Other Name
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.get_NumberFormat()
   at API.Services.Tasks.Scanner.ParseScannedFiles.UpdateSortOrder(ConcurrentDictionary`2 scannedSeries, ParsedSeries series) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ParseScannedFiles.cs:line 766
   at API.Services.Tasks.Scanner.ParseScannedFiles.UpdateSeriesSortOrder(ConcurrentDictionary`2 scannedSeries) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ParseScannedFiles.cs:line 554
```   

```
[Kavita] [2024-11-26 11:33:17.055 -05:00  93] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for Taken by Storm
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.get_NumberFormat()
   at API.Entities.Volume.GetNumberTitle() in /home/runner/work/Kavita/Kavita/API/Entities/Volume.cs:line 70
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 620
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 118
   ```
   
These all definitely could be locale based, but everything I have is US-based and nothing changed from defaults.

**Comment by YaibaToKen** [comment]
> I am experiencing the issue with Docker on a Windows machine but also with Scoop. Windows is set to `en-US`, WSL is `C.UTF-8` and the Docker container itself seems to have no locale set by default.

I had my host using C.UTF-8 and only by changing it to en_US.UTF-8 did I get the errors to stop.

**Comment by ComputerWolf** [comment]
> > I am experiencing the issue with Docker on a Windows machine but also with Scoop. Windows is set to `en-US`, WSL is `C.UTF-8` and the Docker container itself seems to have no locale set by default.
> 
> I had my host using C.UTF-8 and only by changing it to en_US.UTF-8 did I get the errors to stop.

I did just try this and it appears to have fixed the Docker install. My scan runs long, but I should have seen the errors by now. However, this could be problematic for others using Docker if it defaults to `C.UTF-8` even for US-based locales. Also, my Scoop install is just running on `en-US` Windows and also has the issue. I assume this is because Windows is not `UTF-8` but `Windows-1252`

**Comment by majora2007** [comment]
I was able to fix the issue, tested with `C.UTF-8` and validated it works. If anyone else has a different locale where you are seeing this `CultureInfo.get_NumberFormat()` error, please let me know and I can validate the fixes on that locale.

**Comment by ComputerWolf** [comment]
> I was able to fix the issue, tested with `C.UTF-8` and validated it works. If anyone else has a different locale where you are seeing this `CultureInfo.get_NumberFormat()` error, please let me know and I can validate the fixes on that locale.

Is it possible for you to test `Windows-1252`? I think this is what Windows uses when using Scoop.

**Comment by jakkarth** [comment]
Sorry to resurrect this, I'm still seeing it on 0.8.4.2,

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.get_NumberFormat()
   at Nager.ArticleNumber.ArticleNumberHelper.IsValidIsbn13(String isbn13)
   at API.Services.BookService.GetComicInfo(String filePath) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 467
```

Running inside docker on Linux. Inside the container, my locale looks like:

```
root@de1df08ce7e8:/# locale
LANG=en_US.UTF-8
LANGUAGE=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by majora2007** [comment]
> Sorry to resurrect this, I'm still seeing it on 0.8.4.2,
> 
> ```
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
>    at System.Globalization.CultureInfo.get_NumberFormat()
>    at Nager.ArticleNumber.ArticleNumberHelper.IsValidIsbn13(String isbn13)
>    at API.Services.BookService.GetComicInfo(String filePath) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\BookService.cs:line 467
> ```
> 
> Running inside docker on Linux. Inside the container, my locale looks like:
> 
> ```
> root@de1df08ce7e8:/# locale
> LANG=en_US.UTF-8
> LANGUAGE=en_US.UTF-8
> LC_CTYPE="en_US.UTF-8"
> LC_NUMERIC="en_US.UTF-8"
> LC_TIME="en_US.UTF-8"
> LC_COLLATE="en_US.UTF-8"
> LC_MONETARY="en_US.UTF-8"
> LC_MESSAGES="en_US.UTF-8"
> LC_PAPER="en_US.UTF-8"
> LC_NAME="en_US.UTF-8"
> LC_ADDRESS="en_US.UTF-8"
> LC_TELEPHONE="en_US.UTF-8"
> LC_MEASUREMENT="en_US.UTF-8"
> LC_IDENTIFICATION="en_US.UTF-8"
> LC_ALL=
> ```

There is a recorded fix in the pinned issues that will fix this.

**Comment by pjz** [comment]
I'm also still seeing this on the docker version of 0.8.4.2.  Perhaps there's some environment fix that didn't make it into the container?

Any idea when there will be a new release that will include this fix?

Update: I was setting the wrong env var on launch.  Need to set `DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true`

**Comment by majora2007** [comment]
> I'm also still seeing this on the docker version of 0.8.4.2. Perhaps there's some environment fix that didn't make it into the container?
> 
> Any idea when there will be a new release that will include this fix?

This is 100% fixed with this workaround. If you're still having issues, please reach out in our discord server and we can help you out. My time is very limited these days so the next release is going to take quite some time for me.
