### ISSUE TITLE
Can't send email : 5.7.0 Authentication Required.

### ISSUE THREAD

**Issue by LeoShivas** [Kareadita/Kavita#3433]
### What happened?

When I configure the mail settings, mails can not be sent.

I tested with different working passwords.

I tested over SSL and TLS, both of them failed.

### What did you expect?

Mail can be sent.

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4.2 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-12-02 10:59:42.039 +01:00  62] [Error] API.Middleware.ExceptionMiddleware There was an exception
MailKit.ServiceNotAuthenticatedException: 5.7.0 Authentication Required. For more information, go to
5.7.0  https://support.google.com/mail/?p=WantAuthError ffacd0b85a97d-385e8f7132csm5869281f8f.89 - gsmtp
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, CancellationToken cancellationToken, ITransferProgress progress)
   at MailKit.Net.Smtp.SmtpClient.SendAsync(FormatOptions options, MimeMessage message, MailboxAddress sender, IList`1 recipients, CancellationToken cancellationToken, ITransferProgress progress)
   at API.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\EmailService.cs:line 307
   at API.Services.EmailService.SendEmail(EmailOptionsDto userEmailOptions) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\EmailService.cs:line 316
   at API.Services.EmailService.SendTestEmail(String adminEmail) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Services\EmailService.cs:line 115
   at API.Controllers.SettingsController.TestEmailServiceUrl() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Controllers\SettingsController.cs:line 536
   at lambda_method1698(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at API.Startup.<>c__DisplayClass4_0.<<Configure>b__5>d.MoveNext() in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Startup.cs:line 411
--- End of stack trace from previous location ---
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Builder.Extensions.UsePathBaseMiddleware.InvokeCore(HttpContext context, PathString matchedPath, PathString remainingPath)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at API.Middleware.SecurityEventMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\SecurityMiddleware.cs:line 25
   at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\josep\Documents\Projects\KavitaOrg\Kavita\API\Middleware\ExceptionMiddleware.cs:line 18
```

### Additional Notes

It runs on my Kubernetes cluster. Here is the code : https://github.com/LeoShivas/GitOps/tree/main/kubernetes/kavita

![image](https://github.com/user-attachments/assets/f5d55f2d-4e3f-4c88-af23-bbaf1c3c47ac)

**Comment by scare376** [comment]
Are you using a google app password?
https://support.google.com/accounts/answer/185833?hl=en

**Comment by LeoShivas** [comment]
> Are you using a google app password? https://support.google.com/accounts/answer/185833?hl=en

Yes.

**Comment by scare376** [comment]
i was able to send a test email with no issues using a gmail account just now. all the same settings you do. its either something up with your account and you may need to reach out to google. or if the app had to be modified in order to run on kubernetes something there might have broken it and we will not support that.

**Comment by LeoShivas** [comment]
I did some tests.

I've installed a mail client in the Kavita container :
```
apt update
apt install -y ssmtp vim
```
I've configured it with the same settings from Kavita UI in the `/etc/ssmtp/ssmtp.conf` file :
```ini
root=myaccount@gmail.com
mailhub=smtp.gmail.com:465
rewriteDomain=gmail.com
hostname=kavita-5cbd657548-rc7hp
AuthUser=myaccount@gmail.com
AuthPass=myapppassword
FromLineOverride=YES
UseTLS=YES
```

I've sent a mail like this :
```
root@kavita-5cbd657548-rc7hp:/# ssmtp myaccount@gmail.com
To: myaccount@gmail.com
From: myaccount@gmail.com
Subject: test email from kavita pod

Blabla it works !
root@kavita-5cbd657548-rc7hp:/#
```

And I've successfully received my mail :
![image](https://github.com/user-attachments/assets/3027b685-8d26-4d29-b518-b743c1b37f9d)

So, I don't think it is related to my account and password (which are working) or my Kubernetes hosting limitation.

I used the `lscr.io/linuxserver/kavita` image. What image do you use ?

**Comment by LeoShivas** [comment]
Also, why some of my email settings are gone when I refresh the page ? Can it be the issue ?

![image](https://github.com/user-attachments/assets/5953403d-87f0-4cee-b5f3-fa29e9b1f59c)

**Comment by scare376** [comment]
i am using the jvmilazz0 image. the settings disappearing is more likely the reason. can you keep an eye on the logs while you update those fields to see if any errors appear?

**Comment by LeoShivas** [comment]
When I update the port field, nothing appears in the logs.

Indeed, the request is in a 400 http code :
![image](https://github.com/user-attachments/assets/13ddab28-4a3c-41f2-8aae-d569c2e823f8)

Here is the error from the Chrome console :
![image](https://github.com/user-attachments/assets/9d4bc8dc-6063-4f9a-8964-7710a06d3855)

**Comment by LeoShivas** [comment]
A forced cache clear resolved the issue. Maybe the js scripts were not up to date after some Kavita updates.

Thank you !

**Comment by scare376** [comment]
That makes sense. We tend to have issues with the translation key cache after updates so this is probably a similar case. Glad you got it working.
