### ISSUE TITLE
PDFs not showing up in library

### ISSUE THREAD

**Issue by abhemanyus** [Kareadita/Kavita#3457]
### What happened?

I have a bunch of PDFs in a nested folder structure that looks like the following:
(Library root)
 |
MCA.SLM
├── Semester-I
│   ├── MCS-211 Design and Analysis of Algorithms
│   │   ├── Block-1 Introduction to Algorithms
│   │   │   ├── Block-1 Introduction to Algorithms.pdf
│   │   │   ├── Unit-1 Basics of an Algorithm and its Properties.pdf
│   │   │   ├── Unit-2 Asymptotic Bounds.pdf
│   │   │   ├── Unit-3 Complexity Analysis of Simple Algorithms.pdf
│   │   │   └── Unit-4 Solving Recurrences.pdf

### What did you expect?

I used to be able to see all the chapters listed within my library up till a few weeks ago. After updating to the latest stable version of Kavita, they've stopped appearing in my library completely. 

### Kavita Version Number - If you don not see your version number listed, please update Kavita and see if your issue still persists.

0.8.4.2 - Stable

### What operating system is Kavita being hosted from?

Docker (LSIO Container)

### If the issue is being seen on Desktop, what OS are you running where you see the issue?

None

### If the issue is being seen on Mobile, what OS are you running where you see the issue?

None

### Relevant log output

```shell
[Kavita] [2024-12-10 18:19:42.676 +05:30  123] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for MCS
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateChapters(Series series, Volume volume, IList`1 parsedInfos, Boolean forceUpdate)
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 624
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 118
[Kavita] [2024-12-10 18:19:43.447 +05:30  123] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for Block
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateChapters(Series series, Volume volume, IList`1 parsedInfos, Boolean forceUpdate)
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 624
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 118
[Kavita] [2024-12-10 18:19:43.450 +05:30  123] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for MCS
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateChapters(Series series, Volume volume, IList`1 parsedInfos, Boolean forceUpdate)
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 624
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 118
[Kavita] [2024-12-10 18:19:43.455 +05:30  123] [Error] API.Services.Tasks.Scanner.ProcessSeries [ScannerService] There was an exception updating series for History
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Globalization.NumberFormatInfo.InitializeInvariantAndNegativeSignFlags()
   at System.Globalization.CultureInfo.GetFormat(Type formatType)
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateChapters(Series series, Volume volume, IList`1 parsedInfos, Boolean forceUpdate)
   at API.Services.Tasks.Scanner.ProcessSeries.UpdateVolumes(Series series, IList`1 parsedInfos, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 624
   at API.Services.Tasks.Scanner.ProcessSeries.ProcessSeriesAsync(IList`1 parsedInfos, Library library, Int32 totalToProcess, Boolean forceUpdate) in /home/runner/work/Kavita/Kavita/API/Services/Tasks/Scanner/ProcessSeries.cs:line 118
```

### Additional Notes

I am running kavita on a k3s cluster. The PersistentVolume being used is shared by a couple other pods in the cluster, but nothing else is writing into kavita's config or library directories.

**Comment by majora2007** [comment]
Please see this issue. This is likely due to some strange localization issue. 

https://github.com/Kareadita/Kavita/issues/3413

There is a step at the end about what to set for K8s.

**Comment by abhemanyus** [comment]
> Please see this issue. This is likely due to some strange localization issue.
> 
> #3413
> 
> There is a step at the end about what to set for K8s.

That worked, thanks!
