### ISSUE TITLE
Bug: Hangfire has distributed lock and causes all APIs to stall

### ISSUE THREAD

**Issue by majora2007** [Kareadita/Kavita#79]
```
fail: API.Middleware.ExceptionMiddleware[0]
      Timeout expired. The timeout elapsed prior to obtaining a distributed lock on the 'Could not place a lock on
 the resource 'HangFire:lock:recurring-job:ScannerService.ScanLibraries': The lock request timed out.' resource.
      Hangfire.Storage.DistributedLockTimeoutException: Timeout expired. The timeout elapsed prior to obtaining a
distributed lock on the 'Could not place a lock on the resource 'HangFire:lock:recurring-job:ScannerService.ScanLi
braries': The lock request timed out.' resource.
         at Hangfire.LiteDB.LiteDbDistributedLock.Acquire(TimeSpan timeout)
         at Hangfire.LiteDB.LiteDbDistributedLock..ctor(String resource, TimeSpan timeout, HangfireDbContext datab
ase, LiteDbStorageOptions storageOptions)
         at Hangfire.LiteDB.LiteDbConnection.AcquireDistributedLock(String resource, TimeSpan timeout)
         at Hangfire.RecurringJobExtensions.AcquireDistributedRecurringJobLock(IStorageConnection connection, Stri
ng recurringJobId, TimeSpan timeout)
         at Hangfire.RecurringJobManager.AddOrUpdate(String recurringJobId, Job job, String cronExpression, Recurr
ingJobOptions options)
         at Hangfire.RecurringJobManagerExtensions.AddOrUpdate(IRecurringJobManager manager, String recurringJobId
, Job job, String cronExpression, TimeZoneInfo timeZone, String queue)
         at Hangfire.RecurringJob.AddOrUpdate(Expression`1 methodCall, String cronExpression, TimeZoneInfo timeZon
e, String queue)
         at Hangfire.RecurringJob.AddOrUpdate(Expression`1 methodCall, Func`1 cronExpression, TimeZoneInfo timeZon
e, String queue)
         at API.Services.TaskScheduler.ScheduleTasks() in C:\Users\Joe\Documents\Projects\KavitaOrg\Kavita\API\Ser
vices\TaskScheduler.cs:line 56
         at API.Services.TaskScheduler..ctor(ICacheService cacheService, ILogger`1 logger, IScannerService scanner
Service, IUnitOfWork unitOfWork, IMetadataService metadataService, IBackupService backupService, ICleanupService c
leanupService, IDirectoryService directoryService) in C:\Users\Joe\Documents\Projects\KavitaOrg\Kavita\API\Service
s\TaskScheduler.cs:line 43
         at ResolveService(ILEmitResolverBuilderRuntimeContext , ServiceProviderEngineScope )
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceTy
pe, ServiceProviderEngineScope serviceProviderEngineScope)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serv
iceType)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.GetService(IServiceProvider sp, Type type,
 Type requiredBy, Boolean isDefaultParameterRequired)
         at lambda_method481(Closure , IServiceProvider , Object[] )
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerActivatorProvider.<>c__DisplayClass4_0.<CreateActivator
>b__0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Controllers.ControllerFactoryProvider.<>c__DisplayClass5_0.<CreateControllerF
actory>g__CreateController|0(ControllerContext controllerContext)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object
& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(Res
ourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker in
voker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Tas
k requestTask, ILogger logger)
         at API.Startup.<>c.<<Configure>b__3_2>d.MoveNext() in C:\Users\Joe\Documents\Projects\KavitaOrg\Kavita\AP
I\Startup.cs:line 114
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDele
gate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.ResponseCaching.ResponseCachingMiddleware.Invoke(HttpContext httpContext)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Builder.Extensions.MapMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swag
gerProvider)
         at API.Middleware.ExceptionMiddleware.InvokeAsync(HttpContext context) in C:\Users\Joe\Documents\Projects
\KavitaOrg\Kavita\API\Middleware\ExceptionMiddleware.cs:line 30

```

**Comment by majora2007** [comment]
It looks like this happens when i stop and start the server during development. I haven't experienced it in production yet.

**Comment by majora2007** [comment]
I figured this out. This happens when we terminate the process abruptly. In Rider, it happens when I hit stop as that performs Process.destroy(), but if I Ctrl+C in terminal, everything gracefully shutsdown.

I have implemented a way to dispose the Hangfire background service on Shutdown.

**Comment by majora2007** [comment]
My original solution did not solve it. This will not affect prod users, only local development, but it is extremely annoying.

**Comment by majora2007** [comment]
I was unable to solve this. Since it's just in development, I have disabled reoccuring tasks and deleted my local hangfire DB.
